src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>inscor__Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Price__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Price Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Customer_PO_Number__c</fullName>
        <label>Customer PO Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Sales Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <formula>inscor__Product__r.inscor__Keyword__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Keyword</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Line_Total__c</fullName>
        <formula>inscor__Quantity_Ordered__c *  inscor__Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Order__c</fullName>
        <label>Order</label>
        <referenceTo>inscor__Sales_Order__c</referenceTo>
        <relationshipName>Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity_Ordered__c</fullName>
        <label>Quantity Ordered</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{0}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ComplianceUtility.cls
public class ComplianceUtility {

    public static Map<Id, inscor__Sales_Order__c> getSalesOrderWithLineItems(Set<Id> salesOrderIds){
        Map<Id, inscor__Sales_Order__c> salesOrderMap = 
            new Map<Id, inscor__Sales_Order__c>([SELECT Id, inscor__Customer_PO_Number__c, createdDate,
                                                 (SELECT Id, inscor__Product__r.Name, inscor__Keyword__c,
                                                  inscor__Quantity_Ordered__c, inscor__Price__c, 
                                                  inscor__Line_Total__c, inscor__Product__r.inscor__HazMat__c,
                                                  inscor__Product__r.inscor__HazMat_Id__c, 
                                                  inscor__Product__r.inscor__Country_of_Origin__c,
                                                  inscor__Product__r.Description,
                                                  inscor__Product__r.IsActive,
                                                  inscor__Product__r.inscor__HTS_Code__c
                                                  FROM inscor__Order_Lines__r)
                                                 FROM inscor__Sales_Order__c
                                                 WHERE Id IN : salesOrderIds]);
        
        return salesOrderMap;
    }
    
    public static Map<Id, Account> getAccountWithContacts(Set<Id> customerIds){
        Map<Id, Account> accountMap = new Map<Id, Account>([SELECT Id, Name, ShippingStreet, ShippingCity,
                                                            ShippingPostalCode, ShippingState, ShippingCountry, 
                                                            Phone, inscor__Active__c,
                                                            (SELECT Id, Title, Name, Phone, Email FROM Contacts)
                                                            FROM Account
                                                            WHERE Id IN : customerIds]);
        
        return accountMap;
    }
    
    //This method will return map of requested accounts.
    //R-Added 02June2021 
    public static Map<Id, Account> getAccounts(Set<Id> customerIds){
        Map<Id, Account> accountMap = new Map<Id, Account>([SELECT Id, Name, ShippingStreet, ShippingCity,
                                                            ShippingPostalCode, ShippingState, ShippingCountry, 
                                                            Phone, inscor__Active__c,
                                                            (SELECT Id, Title, Name, Phone, Email FROM Contacts)
                                                            FROM Account
                                                            WHERE Id IN : customerIds]);
        
        return accountMap;
    }
    
    public static String formatDate(Date d){
        if(d != null){
            return d.year()+'-'+(d.month() < 10 ? '0'+d.month() : ''+d.month())+'-'+(d.day() < 10 ? '0'+d.day() : ''+d.day());
        }
        return '';
    }
    
    public static String formatDate(DateTime d){
        if(d != null){
            return d.year()+'-'+(d.month() < 10 ? '0'+d.month() : ''+d.month())+'-'+(d.day() < 10 ? '0'+d.day() : ''+d.day());
        }
        return '';
    }
    
    public static Decimal getDecimalValue(Decimal d){
        return d != null ? d : 0;
    }
    
    public static String getStringValue(String s){
        return s != null ? s : '';
    }
    public static String removeDotSpecialChar(String s){
        if( s != null && s != '' ){
            s = s.replace('.','');
        }
        return s;
    }
    
    public static String formatSpecialCharXML( String xmlString ){
        xmlString = xmlString.replace('&', '&amp;');
        xmlString = xmlString.replace('\'', '&apos;');
        return xmlString;
    }
    public static String formatAccountContactPhone( String xmlString ){
        
        if( xmlString != null ){
            if( xmlString.contains('+')  ){
                xmlString = xmlString.replace('+', '');
            }
            if( xmlString.contains('011')  ){
                xmlString = xmlString.replace('011', '');
            }
            if( xmlString.contains('-')  ){
                xmlString = xmlString.replace('-', '');
            }
            if( xmlString.contains(' ')  ){
                xmlString = xmlString.replace(' ', '');
            }
            if( xmlString.contains(',')  ){
                xmlString = xmlString.replace(',', '');
            }
            if( xmlString.contains('(')  ){
                xmlString = xmlString.replace('(', '');
            }
            if( xmlString.contains(')')  ){
                xmlString = xmlString.replace(')', '');
            }
            
            if( xmlString.contains('.')  ){
                xmlString = xmlString.replace('.','');
            }
            
            // Use this method always in last.
            xmlString = xmlString.replaceAll('[A-Za-z]', '');            
        }
        return xmlString != null ? xmlString : '';
    }
    public static String removeTrademarkSpecialChar(String s){
        if( s != null && s != '' ){
            s = s.replace('®','');
        }
        return s;
    }
}