src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>inscor__Account_Number__c</fullName>
        <label>Account #</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Company__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Address_1__c</fullName>
        <label>Address 1</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Company_Name__c</fullName>
        <label>Company Name</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>inscor__Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Company</label>
    <nameField>
        <displayFormat>CID-{0}</displayFormat>
        <label>Company ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Condition_Code__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Description__c</fullName>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Show_in_Summary__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show in Summary</label>
        <type>Checkbox</type>
    </fields>
    <label>Condition Code</label>
    <nameField>
        <label>Condition Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Price__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>inscor__Company__c</referenceTo>
        <relationshipLabel>Prices</relationshipLabel>
        <relationshipName>Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Condition_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipLabel>Prices</relationshipLabel>
        <relationshipName>Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Price Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Company__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Company</label>
        <referenceTo>inscor__Company__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.inscor__Customer__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.inscor__Dropship_Site__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.inscor__Dropship_Site__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.inscor__Dropship_Site__c</field>
                <operation>equals</operation>
                <valueField>Contact.inscor__Account_Shipping_Address__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Create_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Create Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>inscor__Customer_PO_Number__c</fullName>
        <label>Customer PO Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_SO__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Sales_Order_Total_Value__c</fullName>
        <label>Sales Order Total Value</label>
        <summarizedField>inscor__Sales_Order_Line__c.inscor__Line_Total__c</summarizedField>
        <summaryForeignKey>inscor__Sales_Order_Line__c.inscor__Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Sales Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Condition_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Create_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Create Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <formula>inscor__Product__r.inscor__Keyword__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Keyword</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Order_Type__c</fullName>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Outright</fullName>
                    <default>true</default>
                    <label>Outright</label>
                </value>
                <value>
                    <fullName>Exchange</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Send Repaired</fullName>
                </value>
                <value>
                    <fullName>Return Core</fullName>
                </value>
                <value>
                    <fullName>Return Part</fullName>
                </value>
                <value>
                    <fullName>Core Repair</fullName>
                </value>
                <value>
                    <fullName>Managed Repair</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Order__c</fullName>
        <label>Order</label>
        <referenceTo>inscor__Sales_Order__c</referenceTo>
        <relationshipName>Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity_Ordered__c</fullName>
        <label>Quantity Ordered</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{0}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>inscor__Create_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Create Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>inscor__Description__c</fullName>
        <label>Description</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <label>Keyword</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__UOM__c</fullName>
        <label>UOM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EA</fullName>
                </value>
                <value>
                    <fullName>FT</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>YD</fullName>
                </value>
                <value>
                    <fullName>BG</fullName>
                </value>
                <value>
                    <fullName>BX</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>DR</fullName>
                </value>
                <value>
                    <fullName>FT2</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>GL</fullName>
                </value>
                <value>
                    <fullName>GLL</fullName>
                </value>
                <value>
                    <fullName>IN2</fullName>
                </value>
                <value>
                    <fullName>KT</fullName>
                </value>
                <value>
                    <fullName>LB</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>ML</fullName>
                </value>
                <value>
                    <fullName>MM</fullName>
                </value>
                <value>
                    <fullName>OZ</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>PT</fullName>
                </value>
                <value>
                    <fullName>QT</fullName>
                </value>
                <value>
                    <fullName>RL</fullName>
                </value>
                <value>
                    <fullName>SF</fullName>
                </value>
                <value>
                    <fullName>SH</fullName>
                </value>
                <value>
                    <fullName>SI</fullName>
                </value>
                <value>
                    <fullName>SP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderHistoryControllerTest.cls
@IsTest
private class OrderHistoryControllerTest {
  @TestSetup
  static void setupData(){
    Account account = new Account();
    account.Name = 'TEST';
    account.inscor__Account_Number__c = '2';
    insert account;
    
    Contact contact = new Contact(
        FirstName = 'Jhon',
        LastName =  'Doe',
        AccountId = account.Id,
        Email = 'standarduser@testorg.com'
    );
    insert contact;
      
   	inscor__Company__c  company = new inscor__Company__c(
        inscor__Address_1__c = '1111', inscor__City__c = '1111', inscor__Company_Name__c = '1111', inscor__Zip_Code__c = '1111');
        insert company;
    
    Product2 product = new Product2(
        Name = 'Laptop X200', 
        Family = 'Hardware', 
        inscor__Keyword__c ='test',
        inscor__Description__c = 'POWER SUPPLY 12',
        inscor__UOM__c = 'EA'
    );
    insert product;

    inscor__Condition_Code__c conditionCode = new inscor__Condition_Code__c(
        Name ='Condition Code 1', 
        inscor__Show_in_Summary__c = false
    );
    insert conditionCode;

    inscor__Sales_Order__c salesOrder = new inscor__Sales_Order__c(
        inscor__Customer_PO_Number__c = 'PO21-00168',
        inscor__Contact__c = contact.Id,
        inscor__Customer__c = account.Id,
        inscor__Company__c = company.Id
    );
    insert salesOrder;

    inscor__Sales_Order_Line__c salesOrderLine = new inscor__Sales_Order_Line__c(
        inscor__Product__c = product.Id,
        inscor__Condition_Code__c = conditionCode.Id,
        inscor__Quantity_Ordered__c = 1,
        inscor__Order__c = salesOrder.Id,
        inscor__Price__c = 136
    );
    insert salesOrderLine;
    
    // for positive test
    Account account2 = new Account();
    account2.Name = 'test account';
    account2.inscor__Account_Number__c = '22';
    insert account2;
    
    Contact contact2 = new Contact(
        FirstName = 'Harry',
        LastName =  'Adim',
        AccountId = account2.Id,
        Email = 'standarduser@testorg.com',
        Is_Super_User__c = true
    );
    insert contact2;

    Product2 product2 = new Product2(
        Name = 'Laptop y29', 
        Family = 'Hardware', 
        inscor__Keyword__c ='test',
        inscor__Description__c = 'POWER SUPPLY 12',
        inscor__UOM__c = 'EA'
    );
    insert product2;

    inscor__Condition_Code__c conditionCode2 = new inscor__Condition_Code__c(
        Name ='Condition Code 2', 
        inscor__Show_in_Summary__c = false
    );
    insert conditionCode2;
    
    inscor__Sales_Order__c salesOrder2 = new inscor__Sales_Order__c(
        inscor__Customer_PO_Number__c = 'PO21-001',
        inscor__Contact__c = contact.Id,
        inscor__Customer__c = account.Id,
        inscor__Company__c = company.Id
    );
    insert salesOrder2;

    inscor__Sales_Order_Line__c salesOrderLine2 = new inscor__Sales_Order_Line__c(
        inscor__Product__c = product2.Id,
        inscor__Condition_Code__c = conditionCode2.Id,
        inscor__Quantity_Ordered__c = 1,
        inscor__Order__c = salesOrder2.Id,
        inscor__Price__c = 136
    );
    insert salesOrderLine2;

  }

  @IsTest
  static void getCustomerOrderNegativeTest(){

    Profile profile = [SELECT Id FROM Profile WHERE Name = 'Customer Community Plus Login User'];
    Contact contact = [Select Id FROM Contact WHERE Name = 'Jhon Doe' LIMIT 1];
    
    User user = new User(
        Alias = 'jhonet', 
        Email ='standarduser@testorg.com', 
        EmailEncodingKey ='UTF-8', 
        LastName ='Doe', 
        LanguageLocaleKey='en_US', 
        LocaleSidKey = 'en_US', 
        ProfileId = profile.Id,
        ContactId = contact.Id,
        TimeZoneSidKey = 'America/Los_Angeles',
        UserName = 'john@dev.com'
    );

    inscor__Sales_Order__c salesOrder = [SELECT Id, Name,
                                            inscor__Sales_Order_Total_Value__c, 
                                            inscor__Customer_PO_Number__c,  
                                            inscor__Contact__c, 
                                            inscor__Customer__c 
                                            From inscor__Sales_Order__c 
                                            WHERE inscor__Contact__c =: contact.Id LIMIT 1];

    Test.startTest();
    System.runAs(user){
        List<OrderHistoryController.OrderHistoryWrapper> result = OrderHistoryController.getCustomerOrder();
        System.assertEquals(result[0].orderNumber, salesOrder.Name);
    }
    Test.stopTest();
  }

  @IsTest
  static void getCustomerOrderPositiveTest(){

    Profile profile = [SELECT Id FROM Profile WHERE Name = 'Customer Community Plus Login User'];
    Contact contact = [Select Id FROM Contact WHERE Name = 'Jhon Doe' LIMIT 1];
        
    User user = new User(
        Alias = 'jhonet', 
        Email ='standarduser@testorg.com', 
        EmailEncodingKey ='UTF-8', 
        LastName ='Doe', 
        LanguageLocaleKey='en_US', 
        LocaleSidKey = 'en_US', 
        ProfileId = profile.Id,
        ContactId = contact.Id,
        TimeZoneSidKey = 'America/Los_Angeles',
        UserName = 'john@dev.com'
    );

    
    inscor__Sales_Order__c salesOrder = [SELECT Id, Name,
                                            inscor__Sales_Order_Total_Value__c, 
                                            inscor__Customer_PO_Number__c,  
                                            inscor__Contact__c, 
                                            inscor__Customer__c 
                                            From inscor__Sales_Order__c 
                                            WHERE inscor__Contact__c =: contact.Id LIMIT 1];
    
    Test.startTest();
    System.runAs(user){
        List<OrderHistoryController.OrderHistoryWrapper> result = OrderHistoryController.getCustomerOrder();
        System.assertEquals(result[0].orderNumber, salesOrder.Name);
    }
    Test.stopTest();
      
  }

  @IsTest
  static void getOrderBySearchNegativeTest(){

    try {
        String orderName;
        String orderAmount;
        String orderDate;
        String orderType;
        String customerPO;
        String partNumber;

        Test.startTest();
        List<OrderHistoryController.OrderHistoryWrapper> result = OrderHistoryController.getOrderBySearch(orderName, orderAmount, orderDate, orderType, customerPO, partNumber);
        Test.stopTest();
        System.assertEquals(result[0].orderNumber, orderName);
    } catch (Exception e) {
        
    }

  }

  @IsTest
  static void getOrderBySearchNegative02Test(){

    try {
        String orderName;
        String orderAmount;
        String orderDate = '1234';
        String orderType;
        String customerPO;
        String partNumber;

        Test.startTest();
        List<OrderHistoryController.OrderHistoryWrapper> result = OrderHistoryController.getOrderBySearch(orderName, orderAmount, orderDate, orderType, customerPO, partNumber);
        Test.stopTest();
        System.assertEquals(result[0].orderNumber, orderName);
    } catch (Exception e) {
        
    }

  }

    @IsTest
    static void getOrderBySearchPositiveTest(){

        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Customer Community Plus Login User'];
        Contact contact = [Select Id FROM Contact WHERE Name = 'Jhon Doe' LIMIT 1];
        
        User user = new User(
            Alias = 'jhonet', 
            Email ='standarduser@testorg.com', 
            EmailEncodingKey ='UTF-8', 
            LastName ='Doe', 
            LanguageLocaleKey='en_US', 
            LocaleSidKey = 'en_US', 
            ProfileId = profile.Id,
            ContactId = contact.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'john@dev.com'
        );

        inscor__Sales_Order__c salesOrder = [SELECT Id, Name,
                                                inscor__Sales_Order_Total_Value__c, 
                                                inscor__Customer_PO_Number__c,  
                                                inscor__Contact__c, 
                                                inscor__Customer__c,
                                                inscor__Create_Date__c
                                                From inscor__Sales_Order__c 
                                                WHERE inscor__Contact__c =: contact.Id LIMIT 1];

        inscor__Sales_Order_Line__c salesOrderLine = [SELECT Id, Name,
                                                        inscor__Product__c,
                                                        inscor__Condition_Code__c,
                                                        inscor__Quantity_Ordered__c,
                                                        inscor__Order_Type__c,
                                                        inscor__Product__r.Name,
                                                        inscor__Price__c FROM inscor__Sales_Order_Line__c
                                                        WHERE inscor__Order__c =: salesOrder.Id];

        String orderAmount = String.valueOf(salesOrder.inscor__Sales_Order_Total_Value__c);
        String orderDate = String.valueOf(salesOrder.inscor__Create_Date__c);

        
        Test.startTest();
        System.runAs(user){
            List<OrderHistoryController.OrderHistoryWrapper> result = OrderHistoryController.getOrderBySearch(salesOrder.Name, orderAmount, orderDate, salesOrderLine.inscor__Order_Type__c, salesOrder.inscor__Customer_PO_Number__c, salesOrderLine.inscor__Product__r.Name);
        }
        Test.stopTest();
            
    }      

    @IsTest
    static void getOrderBySearchPositive02Test(){

        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Customer Community Plus Login User'];
        Contact contact = [Select Id FROM Contact WHERE Name = 'Jhon Doe' LIMIT 1];
        
        User user = new User(
            Alias = 'jhonet', 
            Email ='standarduser@testorg.com', 
            EmailEncodingKey ='UTF-8', 
            LastName ='Doe', 
            LanguageLocaleKey='en_US', 
            LocaleSidKey = 'en_US', 
            ProfileId = profile.Id,
            ContactId = contact.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'john@dev.com'
        );

        inscor__Sales_Order__c salesOrder = [SELECT Id, Name,
                                                inscor__Sales_Order_Total_Value__c, 
                                                inscor__Customer_PO_Number__c,  
                                                inscor__Contact__c, 
                                                inscor__Customer__c,
                                                inscor__Create_Date__c
                                                From inscor__Sales_Order__c 
                                                WHERE inscor__Contact__c =: contact.Id LIMIT 1];

        inscor__Sales_Order_Line__c salesOrderLine = [SELECT Id, Name,
                                                        inscor__Product__c,
                                                        inscor__Condition_Code__c,
                                                        inscor__Quantity_Ordered__c,
                                                        inscor__Order_Type__c,
                                                        inscor__Product__r.Name,
                                                        inscor__Price__c FROM inscor__Sales_Order_Line__c
                                                        WHERE inscor__Order__c =: salesOrder.Id];

        String orderAmount = String.valueOf(salesOrder.inscor__Sales_Order_Total_Value__c);
        String orderDate = String.valueOf(salesOrder.inscor__Create_Date__c);

        
        Test.startTest();
        System.runAs(user){
            List<OrderHistoryController.OrderHistoryWrapper> result = OrderHistoryController.getOrderBySearch(salesOrder.Name, orderAmount, orderDate, salesOrderLine.inscor__Order_Type__c, salesOrder.inscor__Customer_PO_Number__c, null);
        }
        Test.stopTest();
            
    }      

    @IsTest
    static void getOrderLinesByIdTest(){
        try {

            inscor__Sales_Order__c salesOrder = [SELECT Id, Name,
                                                    inscor__Sales_Order_Total_Value__c, 
                                                    inscor__Customer_PO_Number__c,  
                                                    inscor__Contact__c, 
                                                    inscor__Customer__c,
                                                    inscor__Create_Date__c
                                                    From inscor__Sales_Order__c  LIMIT 1];

            inscor__Sales_Order_Line__c salesOrderLine = [SELECT Id, Name,
                                                            inscor__Product__c,
                                                            inscor__Condition_Code__c,
                                                            inscor__Quantity_Ordered__c,
                                                            inscor__Order_Type__c,
                                                            inscor__Product__r.Name,
                                                            inscor__Price__c FROM inscor__Sales_Order_Line__c
                                                            WHERE inscor__Order__c =: salesOrder.Id];

            Test.startTest();
            List<OrderHistoryController.orderLineWrapper> resultWrapperList = OrderHistoryController.getOrderLinesById(salesOrder.Id);
            Test.stopTest();
        } catch (Exception e) {
            
        }
    }
}