src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>inscor__Account_Number__c</fullName>
        <label>Account #</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_CQ__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Quotes</relationshipLabel>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Closed - Won</fullName>
                </value>
                <value>
                    <fullName>Closed - Lost</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Quote</label>
    <nameField>
        <displayFormat>QU-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead_Managment__mdt.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Lead Managment</label>
    <pluralLabel>Lead Managment</pluralLabel>
</CustomObject>

src/classes/ProcessObsoleteLeadBatchTest.cls
@isTest
public class ProcessObsoleteLeadBatchTest {
    public static final Integer COUNT_LIMIT = 100;
    
    @TestSetup
    private static void Setup(){
        //Create a Account for Customer
        Account accRec = new Account();
        accRec.Name = 'TEST Account';
        accRec.inscor__Account_Number__c = '2';  
        insert accRec;
        List<inscor__Customer_Quote__c> customerQuoteToInsertList = new List<inscor__Customer_Quote__c>();
        for(Integer i = 0; i< COUNT_LIMIT; i++) {
            inscor__Customer_Quote__c customerQuoteRec = new inscor__Customer_Quote__c();
            customerQuoteRec.inscor__Customer__c = accRec.Id;
            customerQuoteRec.inscor__Status__c = 'New';
            customerQuoteToInsertList.add(customerQuoteRec);
        }
        insert customerQuoteToInsertList;
    }
    
    @isTest
    private static void ProcessObsoleteLeadRunBatchTest(){
        Account acc = [SELECT Id,ownerId FROM Account];
        Map<String,Lead_Managment__mdt> leadManagmentSettings = new Map<String,Lead_Managment__mdt>();
        leadManagmentSettings = Lead_Managment__mdt.getall();
        Test.startTest();
        ProcessObsoleteLeadBatch batchRec = new ProcessObsoleteLeadBatch();
        SchedulableContext sc = NULL;
        //Database.executeBatch(batchRec, COUNT_LIMIT);
        batchRec.execute(sc);
        Test.stopTest();
        List<Lead> leadList = new List<Lead>([SELECT Id,Status,ownerId FROM Lead]);
        for(Lead leadRec : leadList){
            system.assertEquals(leadRec.Status,leadManagmentSettings.containsKey('Lead_Status') ? 
                leadManagmentSettings.get('Lead_Status').Value__C : 'New');
            system.assertEquals(leadRec.ownerId, leadManagmentSettings.containsKey('Lead_OwnerId') ? 
                ( leadManagmentSettings.get('Lead_OwnerId').Value__c != null ? 
                 leadManagmentSettings.get('Lead_OwnerId').Value__c : acc.ownerId) : acc.ownerId);
        }
    }
    
}