src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>inscor__Account_Number__c</fullName>
        <label>Account #</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Company__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Address_1__c</fullName>
        <label>Address 1</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Company_Name__c</fullName>
        <label>Company Name</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>inscor__Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Company</label>
    <nameField>
        <displayFormat>CID-{0}</displayFormat>
        <label>Company ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Business_Category__c</fullName>
        <label>Business Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Business_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Company__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Company</label>
        <referenceTo>inscor__Company__c</referenceTo>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_CQ__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Quotes</relationshipLabel>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Closed - Won</fullName>
                </value>
                <value>
                    <fullName>Closed - Lost</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Quote</label>
    <nameField>
        <displayFormat>QU-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Business_Category__c</fullName>
        <label>Business Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Business_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Customer_Quote__c</fullName>
        <label>Customer Quote</label>
        <referenceTo>inscor__Customer_Quote__c</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Ready to Quote</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Queued to Quote</fullName>
                </value>
                <value>
                    <fullName>Quoted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Quote Line</label>
    <nameField>
        <displayFormat>QUL-{0}</displayFormat>
        <label>Quote Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trigger_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Trigger Configuration will be used for maintaining trigger toggle for its execution.</description>
    <fields>
        <fullName>Customer_Quote_Line_Trigger_Disable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disable Customer Quote Line Trigger</description>
        <inlineHelpText>Disable Customer Quote Line Trigger</inlineHelpText>
        <label>Customer Quote Line Trigger Disable</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Configuration</label>
</CustomObject>

src/classes/CustomerQuoteLineTriggerHelperTest.cls
/**************************************************************************************************
Description: Trigger class for inscor__Customer_Quote_Line__c that will handle all types of trigger events Test Methods.
====================================================================================================
====================================================================================================
Class: CustomerQuoteLineTriggerHelperTest
====================================================================================================
====================================================================================================
History
<Version>   	<Date>             <Author Name>                <Brief description of change > 
1.0 -      		05/20/2021		    Gourav Goyal				Initial Creation     
***************************************************************************************************/
@isTest
public class CustomerQuoteLineTriggerHelperTest {
    public static final Integer COUNT_LIMIT = 10;
    
    @testSetup()
    private static void setup(){
        //Create a Account for Customer
        Account accRec = new Account();
        accRec.Name = 'TEST Account';
        accRec.inscor__Account_Number__c = '2';  
        insert accRec;
        List<inscor__Customer_Quote__c> customerQuoteToInsertList = new List<inscor__Customer_Quote__c>();
        List<inscor__Customer_Quote_Line__c> customerQuoteLineToInsertList = new List<inscor__Customer_Quote_Line__c>();
        
          inscor__Company__c  company = new inscor__Company__c(
            inscor__Address_1__c = '1111', inscor__City__c = '1111', inscor__Company_Name__c = '1111', inscor__Zip_Code__c = '1111');
        insert company;
        
        for(Integer i = 0; i< COUNT_LIMIT; i++) {
            inscor__Customer_Quote__c customerQuoteRec = new inscor__Customer_Quote__c();
            customerQuoteRec.inscor__Customer__c = accRec.Id;
            customerQuoteRec.inscor__Status__c = 'New';
            customerQuoteRec.inscor__Company__c = company.Id;
            customerQuoteToInsertList.add(customerQuoteRec);
        }
        insert customerQuoteToInsertList;
        List<Opportunity> oppList = new List<Opportunity>([SELECT Id FROM Opportunity]);
        system.assertEquals(oppList.size(), COUNT_LIMIT);
        for(inscor__Customer_Quote__c quoteRec : customerQuoteToInsertList){
            for(Integer i = 0; i< COUNT_LIMIT; i++) { 
                inscor__Customer_Quote_Line__c qouteLineRec = new inscor__Customer_Quote_Line__c();
                qouteLineRec.inscor__Customer_Quote__c = quoteRec.Id;
                qouteLineRec.inscor__Quantity__c = 10;
                qouteLineRec.inscor__Business_Category__c = 'Distribution';
                customerQuoteLineToInsertList.add(qouteLineRec);
            }  
        }
        insert customerQuoteLineToInsertList;
    }
    
    @isTest
    private static void updateCustomerQuoteOnInsertTest(){ 
        Test.startTest();
        List<inscor__Customer_Quote_Line__c> customerQuoteLineToCount 
            = new List<inscor__Customer_Quote_Line__c>([SELECT Id,inscor__Quantity__c,inscor__Business_Category__c FROM inscor__Customer_Quote_Line__c]);
        system.assertEquals(customerQuoteLineToCount.size(), (COUNT_LIMIT*COUNT_LIMIT)); 
        system.assertEquals(customerQuoteLineToCount[0].inscor__Business_Category__c, 'Distribution'); 
        system.assertEquals(customerQuoteLineToCount[0].inscor__Quantity__c, 10);
        Test.stopTest();
    }
    
    @isTest
    private static void updateCustomerScoreOnUpdateTestI(){
        List<inscor__Customer_Quote_Line__c> customerQuoteLineToUpdate 
            = new List<inscor__Customer_Quote_Line__c>([SELECT Id,inscor__Business_Category__c,inscor__Quantity__c FROM inscor__Customer_Quote_Line__c]);
        system.assertEquals(customerQuoteLineToUpdate.size(), (COUNT_LIMIT*COUNT_LIMIT)); 
        system.assertEquals(customerQuoteLineToUpdate[0].inscor__Business_Category__c, 'Distribution'); 
        system.assertEquals(customerQuoteLineToUpdate[0].inscor__Quantity__c, 10);
        //Update 
        List<inscor__Customer_Quote_Line__c> cusQuoteLineToUpdateList 
            = new List<inscor__Customer_Quote_Line__c>();
        for(inscor__Customer_Quote_Line__c qouteLineRec : customerQuoteLineToUpdate){
            qouteLineRec.inscor__Business_Category__c = 'Surplus';
            qouteLineRec.inscor__Quantity__c = 20;
            cusQuoteLineToUpdateList.add(qouteLineRec);  
        }
        test.startTest();
        update cusQuoteLineToUpdateList;
        test.stopTest();
        List<inscor__Customer_Quote_Line__c> customerQuoteLineToCount 
            = new List<inscor__Customer_Quote_Line__c>([SELECT Id,inscor__Business_Category__c,inscor__Quantity__c FROM inscor__Customer_Quote_Line__c]);
        system.assertEquals(customerQuoteLineToCount.size(), (COUNT_LIMIT*COUNT_LIMIT)); 
        system.assertEquals(customerQuoteLineToCount[0].inscor__Business_Category__c, 'Surplus'); 
        system.assertEquals(customerQuoteLineToCount[0].inscor__Quantity__c, 20);
    }
    
    @isTest
    private static void updateCustomerScoreOnUpdateTestII(){
        List<inscor__Customer_Quote_Line__c> customerQuoteLineToUpdate 
            = new List<inscor__Customer_Quote_Line__c>([SELECT Id,inscor__Business_Category__c,inscor__Quantity__c FROM inscor__Customer_Quote_Line__c]);
        system.assertEquals(customerQuoteLineToUpdate.size(), (COUNT_LIMIT*COUNT_LIMIT)); 
        system.assertEquals(customerQuoteLineToUpdate[0].inscor__Business_Category__c, 'Distribution'); 
        system.assertEquals(customerQuoteLineToUpdate[0].inscor__Quantity__c, 10);
        test.startTest();
        //Update 
        List<inscor__Customer_Quote_Line__c> cusQuoteLineToUpdateList 
            = new List<inscor__Customer_Quote_Line__c>();
        for(inscor__Customer_Quote_Line__c qouteLineRec : customerQuoteLineToUpdate){
            qouteLineRec.inscor__Business_Category__c = 'Broker';
            qouteLineRec.inscor__Quantity__c = 20;
            cusQuoteLineToUpdateList.add(qouteLineRec);  
        }
        
        update cusQuoteLineToUpdateList;
        test.stopTest();
        List<inscor__Customer_Quote_Line__c> customerQuoteLineToCount 
            = new List<inscor__Customer_Quote_Line__c>([SELECT Id,inscor__Business_Category__c,inscor__Quantity__c FROM inscor__Customer_Quote_Line__c]);
        system.assertEquals(customerQuoteLineToCount.size(), (COUNT_LIMIT*COUNT_LIMIT)); 
        system.assertEquals(customerQuoteLineToCount[0].inscor__Business_Category__c, 'Broker'); 
        system.assertEquals(customerQuoteLineToCount[0].inscor__Quantity__c, 20);
    }
    
    @isTest
    public static void triggerMethodsTest() { 
        test.StartTest();
        List<inscor__Customer_Quote_Line__c> recList = new List<inscor__Customer_Quote_Line__c>([SELECT id FROM inscor__Customer_Quote_Line__c]);
        test.stopTest();   
        delete recList;
        List<inscor__Customer_Quote_Line__c> recListToAssert = new List<inscor__Customer_Quote_Line__c>([SELECT id FROM inscor__Customer_Quote_Line__c]);
        system.assertEquals(recListToAssert.size(), 0);
        undelete recList;  
    }
    
    @isTest
    public static void triggerDisabledFlagTest() { 
        test.StartTest();
        //Trigger Disabled Coverage
        Trigger_Configuration__c tc = new Trigger_Configuration__c();
        tc.Customer_Quote_Line_Trigger_Disable__c  = TRUE;
        insert tc;
        test.stopTest(); 
        List<inscor__Customer_Quote_Line__c> recList = new List<inscor__Customer_Quote_Line__c>([SELECT id FROM inscor__Customer_Quote_Line__c]);
        delete recList;
        List<inscor__Customer_Quote_Line__c> recListToAssert = new List<inscor__Customer_Quote_Line__c>([SELECT id FROM inscor__Customer_Quote_Line__c]);
        system.assertEquals(recListToAssert.size(), 0);
    }
}