src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>inscor__Account_Number__c</fullName>
        <label>Account #</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Compliance_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>EndPoint__c</fullName>
        <label>EndPoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment_Status_Action__c</fullName>
        <label>Shipment Status Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Upload_File_Action__c</fullName>
        <label>Upload File Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Compliance Configuration</label>
</CustomObject>

src/objects/inscor__Account_Ship_Address__c.object
<CustomObject>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Account Ship Address</label>
    <nameField>
        <label>Account Ship Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Ship Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Company__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Address_1__c</fullName>
        <label>Address 1</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Company_Name__c</fullName>
        <label>Company Name</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>inscor__Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Company</label>
    <nameField>
        <displayFormat>CID-{0}</displayFormat>
        <label>Company ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Company__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Company</label>
        <referenceTo>inscor__Company__c</referenceTo>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_CQ__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Quotes</relationshipLabel>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Ship_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Address</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.inscor__Customer__c</field>
                <operation>equals</operation>
                <valueField>inscor__Account_Ship_Address__c.inscor__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>inscor__Account_Ship_Address__c</referenceTo>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Closed - Won</fullName>
                </value>
                <value>
                    <fullName>Closed - Lost</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Quote</label>
    <nameField>
        <displayFormat>QU-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Release__c.object
<CustomObject>
    <fields>
        <fullName>Compliance_Response__c</fullName>
        <label>Compliance Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Compliance_Status__c</fullName>
        <label>Compliance Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>inscor__Sales_Order__c</referenceTo>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Ship_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Address</label>
        <referenceTo>inscor__Account_Ship_Address__c</referenceTo>
        <relationshipName>Releases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Released</fullName>
                    <default>true</default>
                    <label>Released</label>
                </value>
                <value>
                    <fullName>In_Picking</fullName>
                    <label>In Picking</label>
                </value>
                <value>
                    <fullName>Picked</fullName>
                </value>
                <value>
                    <fullName>In QC</fullName>
                </value>
                <value>
                    <fullName>QCd</fullName>
                </value>
                <value>
                    <fullName>In Shipping</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Release</label>
    <nameField>
        <displayFormat>RLS-{0}</displayFormat>
        <label>Release Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Company__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Company</label>
        <referenceTo>inscor__Company__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_SO__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quote_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Number</label>
        <referenceTo>inscor__Customer_Quote__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Ship_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Address</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.inscor__Customer__c</field>
                <operation>equals</operation>
                <valueField>inscor__Account_Ship_Address__c.inscor__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>inscor__Account_Ship_Address__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In_Progress</fullName>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Partially_Allocated</fullName>
                    <label>Partially Allocated</label>
                </value>
                <value>
                    <fullName>Allocated</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Sales Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchUpdateShipmentStatusTest.cls
@isTest
private class BatchUpdateShipmentStatusTest {
	
    @testSetup()
    private static void setup(){

        Compliance_Configuration__c complianceConfigSetting = Compliance_Configuration__c.getOrgDefaults();   
        complianceConfigSetting.EndPoint__c = 'https://text-azservices.ecustoms.com/edwinimport/EdwinImportPortal.asmx';
        complianceConfigSetting.Shipment_Status_Action__c = 'http://test-tempuri.org/GetShipmentStatus';
        complianceConfigSetting.Upload_File_Action__c = 'http://test-tempuri.org/Uploadfile';
        upsert complianceConfigSetting;
        
        //Create a Account for Customer
        Account accRec = new Account();
        accRec.Name = 'TEST';
        accRec.inscor__Account_Number__c = '2';  
        insert accRec;
        
        inscor__Company__c  company = new inscor__Company__c(inscor__Address_1__c = '1111', 
                                                             inscor__City__c = '1111', 
                                                             inscor__Company_Name__c = '1111', 
                                                             inscor__Zip_Code__c = '1111');
        insert company;

        inscor__Customer_Quote__c customerQuoteRec = new inscor__Customer_Quote__c();
        customerQuoteRec.inscor__Customer__c = accRec.Id;
        customerQuoteRec.inscor__Status__c = 'New';
        customerQuoteRec.inscor__Company__c = company.Id;
        insert customerQuoteRec;
        
        inscor__Sales_Order__c salesOrderRec = new inscor__Sales_Order__c();
        salesOrderRec.inscor__Quote_Number__c = customerQuoteRec.Id;
        salesOrderRec.inscor__Customer__c = accRec.Id;
        salesOrderRec.inscor__Company__c = company.Id;
        insert salesOrderRec;
                
        inscor__Account_Ship_Address__c addRec = new inscor__Account_Ship_Address__c();
        insert addRec;
        
        inscor__Release__c releaseRec = new inscor__Release__c();
        releaseRec.inscor__Ship_To_Address__c = addRec.Id;
        releaseRec.inscor__Sales_Order__c = salesOrderRec.Id;
        releaseRec.Compliance_Status__c = 'Upload Successful';
        insert releaseRec;
    }    
    
    @isTest
    static void batchWithParamTest() {
        Test.setMock(HttpCalloutMock.class, new ComplianceMockResponseGenerator());
        Test.startTest();
        	List<inscor__Release__c> inscorList = [SELECT Id from inscor__Release__c];
        
        Database.executeBatch(new BatchUpdateShipmentStatus(new Set<Id>{inscorList[0].Id}), 200);
        Test.stopTest();
        inscorList = [SELECT Id, Compliance_Response__c from inscor__Release__c where Id =: inscorList[0].Id];
       //system.assertNotEquals(null, inscorList[0].Compliance_Response__c);
    } 

	@isTest
    static void batchWithParamTest02() {
        Test.setMock(HttpCalloutMock.class, new ComplianceMockResponseGenerator());
        Test.startTest();
        	List<inscor__Release__c> inscorList = [SELECT Id from inscor__Release__c];
        Integer intervalMinutes = 1;
        DateTime now  = DateTime.now();
        DateTime nextRunTime = now.addMinutes(intervalMinutes);
        String cronString = '' + nextRunTime.second() + ' ' + nextRunTime.minute() + ' ' + 
            nextRunTime.hour() + ' ' + nextRunTime.day() + ' ' + 
            nextRunTime.month() + ' ? ' + nextRunTime.year(); 
        System.schedule('BatchUpdateShipmentStatus -' + now.format(), cronString, new BatchUpdateShipmentStatus());
        Test.stopTest();
        inscorList = [SELECT Id, Compliance_Response__c from inscor__Release__c where Id =: inscorList[0].Id];
       //system.assertNotEquals(null, inscorList[0].Compliance_Response__c);
    }     
    
}