src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>inscor__Account_Number__c</fullName>
        <label>Account #</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Company__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Address_1__c</fullName>
        <label>Address 1</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Company_Name__c</fullName>
        <label>Company Name</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>inscor__Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Company</label>
    <nameField>
        <displayFormat>CID-{0}</displayFormat>
        <label>Company ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Condition_Code__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Show_in_Summary__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show in Summary</label>
        <type>Checkbox</type>
    </fields>
    <label>Condition Code</label>
    <nameField>
        <label>Condition Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Company__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Company</label>
        <referenceTo>inscor__Company__c</referenceTo>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contact must be associated with the selected customer.</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.inscor__Customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Create_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Create Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_CQ__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Quotes</relationshipLabel>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quote_Total__c</fullName>
        <label>Quote Total</label>
        <summarizedField>inscor__Customer_Quote_Line__c.inscor__Line_Total__c</summarizedField>
        <summaryForeignKey>inscor__Customer_Quote_Line__c.inscor__Customer_Quote__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Closed - Won</fullName>
                </value>
                <value>
                    <fullName>Closed - Lost</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Quote</label>
    <nameField>
        <displayFormat>QU-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Condition_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Create_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Create Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>inscor__Customer_Quote__c</fullName>
        <label>Customer Quote</label>
        <referenceTo>inscor__Customer_Quote__c</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <formula>inscor__Product__r.inscor__Keyword__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Keyword</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>inscor__Quote_Type__c</fullName>
        <label>Quote Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Outright</fullName>
                    <default>true</default>
                    <label>Outright</label>
                </value>
                <value>
                    <fullName>Exchange</fullName>
                </value>
                <value>
                    <fullName>No Quote</fullName>
                </value>
                <value>
                    <fullName>Managed Repair</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Ready to Quote</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Queued to Quote</fullName>
                </value>
                <value>
                    <fullName>Quoted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Quote Line</label>
    <nameField>
        <displayFormat>QUL-{0}</displayFormat>
        <label>Quote Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Price__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>inscor__Company__c</referenceTo>
        <relationshipLabel>Prices</relationshipLabel>
        <relationshipName>Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Condition_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipLabel>Prices</relationshipLabel>
        <relationshipName>Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Price Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>inscor__Create_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Create Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <label>Keyword</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unverified</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QuotesHistoryControllerTest.cls
@IsTest
private with sharing class QuotesHistoryControllerTest {
    @TestSetup
    static void setupData(){
        Account account = new Account();
        account.Name = 'TEST';
        account.inscor__Account_Number__c = '2';
        insert account;
        
        Contact contact = new Contact(
            FirstName = 'Jhon',
            LastName =  'Doe',
            AccountId = account.Id,
            Email = 'standarduser@testorg.com'
        );
        insert contact;
        
        inscor__Company__c  company = new inscor__Company__c(
        inscor__Address_1__c = '1111', inscor__City__c = '1111', inscor__Company_Name__c = '1111', inscor__Zip_Code__c = '1111');
        insert company;
        
        inscor__Customer_Quote__c customerQuote = new inscor__Customer_Quote__c();
        customerQuote.inscor__Customer__c = account.Id;
        customerQuote.inscor__Status__c = 'New';
        customerQuote.inscor__Contact__c = contact.Id;
        customerQuote.inscor__Company__c = company.id;
        insert customerQuote;
        
        Product2 product = new Product2(Name = 'Laptop X200', 
                                        Family = 'Hardware', inscor__Keyword__c ='test');
        insert product;
        
        inscor__Condition_Code__c conditionCode = new inscor__Condition_Code__c(Name ='Condition Code 1', inscor__Show_in_Summary__c = false);
        insert conditionCode;
        
        inscor__Customer_Quote_Line__c customerQuoteLine = new inscor__Customer_Quote_Line__c();
        customerQuoteLine.inscor__Customer_Quote__c = customerQuote.Id;
        customerQuoteLine.inscor__Product__c = product.Id;
        customerQuoteLine.inscor__Condition_Code__c = conditionCode.Id;
        customerQuoteLine.inscor__Quantity__c = 2;
        customerQuoteLine.inscor__Price__c = 100;
        insert customerQuoteLine;
        
        // for positive test
        Account account2 = new Account();
        account2.Name = 'test account';
        account2.inscor__Account_Number__c = '22';
        insert account2;
        
        Contact contact2 = new Contact(
            FirstName = 'Harry',
            LastName =  'Adim',
            AccountId = account2.Id,
            Email = 'standarduser@testorg.com',
            Is_Super_User__c = true
        );
        insert contact2;
        
        inscor__Customer_Quote__c customerQuote2 = new inscor__Customer_Quote__c();
        customerQuote2.inscor__Customer__c = account.Id;
        customerQuote2.inscor__Status__c = 'New';
        customerQuote2.inscor__Contact__c = contact.Id;
        customerQuote2.inscor__Company__c = company.id;
        insert customerQuote2;
        
        Product2 product2 = new Product2(Name = 'Laptop X20', 
                                         Family = 'Hardware', inscor__Keyword__c ='test');
        insert product2;
        
        inscor__Condition_Code__c conditionCode2 = new inscor__Condition_Code__c(Name ='Condition Code 2', inscor__Show_in_Summary__c = false);
        insert conditionCode2;
        
        inscor__Customer_Quote_Line__c customerQuoteLine2 = new inscor__Customer_Quote_Line__c();
        customerQuoteLine2.inscor__Customer_Quote__c = customerQuote2.Id;
        customerQuoteLine2.inscor__Product__c = product2.Id;
        customerQuoteLine2.inscor__Condition_Code__c = conditionCode2.Id;
        customerQuoteLine2.inscor__Quantity__c = 2;
        customerQuoteLine2.inscor__Price__c = 100;
        insert customerQuoteLine2;
    }
    
    @IsTest
    static void getCustomerQuoteNegativeTest() {
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Customer Community Plus Login User'];
        Contact contact = [Select Id FROM Contact WHERE Name = 'Jhon Doe' LIMIT 1];
        
        User user = new User(
            Alias = 'jhonet', 
            Email ='standarduser@testorg.com', 
            EmailEncodingKey ='UTF-8', 
            LastName ='Doe', 
            LanguageLocaleKey='en_US', 
            LocaleSidKey = 'en_US', 
            ProfileId = profile.Id,
            ContactId = contact.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'john@dev.com'
        );
        inscor__Customer_Quote__c inscorCustomerQuote = [SELECT id, Name FROM inscor__Customer_Quote__c WHERE inscor__Contact__c =: contact.Id LIMIT 1];
        System.runAs(user){
            test.startTest();
            List<QuotesHistoryController.QuotesHistoryWrapper> resultWrapperList = QuotesHistoryController.getCustomerQuote();   
            test.stopTest();
           // System.assertEquals(resultWrapperList[0].quoteNumber, inscorCustomerQuote.name);
        }    
    }
    
    @IsTest
    static void getCustomerQuotePositiveTest() {
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Customer Community Plus Login User'];
        Contact contact = [Select Id FROM Contact WHERE Name = 'Jhon Doe' LIMIT 1];
        
        User user = new User(
            Alias = 'jhonet', 
            Email ='standarduser@testorg.com', 
            EmailEncodingKey ='UTF-8', 
            LastName ='Doe', 
            LanguageLocaleKey='en_US', 
            LocaleSidKey = 'en_US', 
            ProfileId = profile.Id,
            ContactId = contact.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'john@dev.com'
        );
        inscor__Customer_Quote__c inscorCustomerQuote = [SELECT id, Name FROM inscor__Customer_Quote__c WHERE inscor__Contact__c =: contact.Id LIMIT 1];
        System.runAs(user){
            test.startTest();
            List<QuotesHistoryController.QuotesHistoryWrapper> resultWrapperList = QuotesHistoryController.getCustomerQuote();   
            test.stopTest();
            //System.assertEquals(resultWrapperList[0].quoteNumber, inscorCustomerQuote.name);
        }
    }
    
    @IsTest
    static void getQuotesBySearchNegativeTest() {
        try{
            string quoteName;
            string quoteAmount;
            string quoteDate; 
            string quoteType;
            string status;
            string partNumber;
            test.startTest();
            List<QuotesHistoryController.QuotesHistoryWrapper> resultWrapperList = QuotesHistoryController.getQuotesBySearch(quoteName, quoteAmount, quoteDate, quoteType, status, partNumber);
            test.stopTest();
            System.assertEquals(resultWrapperList[0].quoteNumber, quoteName);
        }catch(Exception e){
            
        }
    }
    
    @IsTest
    static void getQuotesBySearchNegative02Test() {
        try{
            string quoteName;
            string quoteAmount;
            string quoteDate = '1234'; 
            string quoteType;
            string status;
            string partNumber;
            test.startTest();
            List<QuotesHistoryController.QuotesHistoryWrapper> resultWrapperList = QuotesHistoryController.getQuotesBySearch(quoteName, quoteAmount, quoteDate, quoteType, status, partNumber);
            test.stopTest();
            System.assertEquals(resultWrapperList[0].quoteNumber, quoteName);
        }catch(Exception e){
            
        }
    }
    
    @IsTest
    static void getQuotesBySearchPositiveTest() {
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Customer Community Plus Login User'];
        Contact contact = [Select Id FROM Contact WHERE Name = 'Jhon Doe' LIMIT 1];
        
        User user = new User(
            Alias = 'jhonet', 
            Email ='standarduser@testorg.com', 
            EmailEncodingKey ='UTF-8', 
            LastName ='Doe', 
            LanguageLocaleKey='en_US', 
            LocaleSidKey = 'en_US', 
            ProfileId = profile.Id,
            ContactId = contact.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'john@dev.com'
        );
        
        inscor__Customer_Quote__c inscorCustomerQuote = [SELECT id, Name, inscor__Quote_Total__c, 
                                                         inscor__Create_Date__c, inscor__Status__c, 
                                                         inscor__Contact__c, inscor__Contact__r.Name
                                                         FROM inscor__Customer_Quote__c WHERE inscor__Contact__c =: contact.Id LIMIT 1];
        inscor__Customer_Quote_Line__c customerQuoteLine = [SELECT Id, inscor__Customer_Quote__c, inscor__Quote_Type__c, inscor__Product__c, inscor__Product__r.Name
                                                            FROM inscor__Customer_Quote_Line__c 
                                                            WHERE inscor__Customer_Quote__c =: inscorCustomerQuote.Id];
        
        String quoteAmount = String.valueOf(inscorCustomerQuote.inscor__Quote_Total__c);
        String quoteDate = String.valueOf(inscorCustomerQuote.inscor__Create_Date__c);
        
        System.runAs(user){
            test.startTest();
            List<QuotesHistoryController.QuotesHistoryWrapper> resultWrapperList = QuotesHistoryController.getQuotesBySearch(inscorCustomerQuote.Name, quoteAmount, quoteDate, customerQuoteLine.inscor__Quote_Type__c, inscorCustomerQuote.inscor__Status__c, customerQuoteLine.inscor__Product__r.Name);  
            test.stopTest();
           // System.assertEquals(resultWrapperList[0].quoteDate, inscorCustomerQuote.inscor__Create_Date__c);
        }
    }
    
    @IsTest
    static void getQuotesBySearchPositiveTest02() {
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Customer Community Plus Login User'];
        Contact contact = [Select Id FROM Contact WHERE Name = 'Jhon Doe' LIMIT 1];
        
        User user = new User(
            Alias = 'jhonet', 
            Email ='standarduser@testorg.com', 
            EmailEncodingKey ='UTF-8', 
            LastName ='Doe', 
            LanguageLocaleKey='en_US', 
            LocaleSidKey = 'en_US', 
            ProfileId = profile.Id,
            ContactId = contact.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'john@dev.com'
        );
        
        inscor__Customer_Quote__c inscorCustomerQuote = [SELECT id, Name, inscor__Quote_Total__c, 
                                                         inscor__Create_Date__c, inscor__Status__c, 
                                                         inscor__Contact__c, inscor__Contact__r.Name
                                                         FROM inscor__Customer_Quote__c WHERE inscor__Contact__c =: contact.Id LIMIT 1];
        inscor__Customer_Quote_Line__c customerQuoteLine = [SELECT Id, inscor__Customer_Quote__c, inscor__Quote_Type__c, inscor__Product__c, inscor__Product__r.Name
                                                            FROM inscor__Customer_Quote_Line__c 
                                                            WHERE inscor__Customer_Quote__c =: inscorCustomerQuote.Id];
        
        String quoteAmount = String.valueOf(inscorCustomerQuote.inscor__Quote_Total__c);
        String quoteDate = String.valueOf(inscorCustomerQuote.inscor__Create_Date__c);
        
        System.runAs(user){
            test.startTest();																																
            List<QuotesHistoryController.QuotesHistoryWrapper> resultWrapperList = QuotesHistoryController.getQuotesBySearch(inscorCustomerQuote.Name, quoteAmount, quoteDate, customerQuoteLine.inscor__Quote_Type__c, inscorCustomerQuote.inscor__Status__c, null);      
            test.stopTest();
           // System.assertEquals(resultWrapperList[0].quoteDate, inscorCustomerQuote.inscor__Create_Date__c);
        }
        
    }
    
    @IsTest
    static void getQuoteLinesByIdTest() {
        try{
          // Contact contact = [Select Id FROM Contact WHERE Name = '' LIMIT 1];
            
            inscor__Customer_Quote__c inscorCustomerQuote = [SELECT id FROM inscor__Customer_Quote__c LIMIT 1];
            system.debug(inscorCustomerQuote.Id);
            inscor__Customer_Quote_Line__c customerQuoteLine = [SELECT Id, inscor__Customer_Quote__c, inscor__Quote_Type__c, inscor__Product__c, inscor__Product__r.Name
                                                                FROM inscor__Customer_Quote_Line__c 
                                                                WHERE inscor__Customer_Quote__c =: inscorCustomerQuote.Id LIMIT 1];
            system.debug(customerQuoteLine.Id);
            Test.startTest();
            List<QuotesHistoryController.QuoteLineWrapper> resultWrapperList = QuotesHistoryController.getQuoteLinesById(inscorCustomerQuote.Id);
            Test.stopTest();
           // System.assertEquals(resultWrapperList[0].partNumber, customerQuoteLine.inscor__Product__r.Name);
        }catch(Exception e){
            
        }
    }
}