src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Average_Margin__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Average Margin %</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Customer_Quotes_Lines_Received__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Customer Quotes Lines Received</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Score_2__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Customer Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Orders_Lines_Received__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sales Orders Lines Received</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Sales__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer_Score_Factor__mdt.object
<CustomObject>
    <fields>
        <fullName>Ending_Number__c</fullName>
        <label>Ending Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Starting_Number__c</fullName>
        <label>Starting Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Orders Lines Received</fullName>
                    <default>true</default>
                    <label>Sales Orders Lines Received</label>
                </value>
                <value>
                    <fullName>Customer Quotes Lines Received</fullName>
                </value>
                <value>
                    <fullName>Total Sales</fullName>
                </value>
                <value>
                    <fullName>Margin</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Weightage__c</fullName>
        <label>Weightage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer Score Factor</label>
    <pluralLabel>Customer Score Factors</pluralLabel>
</CustomObject>

src/objects/inscor__Customer_Quote__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_CQ__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Quotes</relationshipLabel>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Quote</label>
    <nameField>
        <displayFormat>QU-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Customer_Quote__c</fullName>
        <label>Customer Quote</label>
        <referenceTo>inscor__Customer_Quote__c</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Quote Line</label>
    <nameField>
        <displayFormat>QUL-{0}</displayFormat>
        <label>Quote Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Invoice__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Margin_Percent__c</fullName>
        <formula>( inscor__Invoice_Value__c - inscor__Total_Lines_Cost__c ) / inscor__Invoice_Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Margin %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>inscor__Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>inscor__Sales_Order__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INVC-{0}</displayFormat>
        <label>Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vendor</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                    <default>true</default>
                    <label>All</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_SO__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Sales_Order_Total_Value__c</fullName>
        <label>Sales Order Total Value</label>
        <summarizedField>inscor__Sales_Order_Line__c.inscor__Line_Total__c</summarizedField>
        <summaryForeignKey>inscor__Sales_Order_Line__c.inscor__Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Sales Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Order__c</fullName>
        <label>Order</label>
        <referenceTo>inscor__Sales_Order__c</referenceTo>
        <relationshipName>Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{0}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CustomerScoreCalculationsBatch.cls
global class CustomerScoreCalculationsBatch implements Database.Batchable<sObject>, Schedulable {

    global CustomerScoreCalculationsBatch() {}

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator('SELECT Id FROM Account');
    }
     
    global void execute(Database.BatchableContext BC, List<Account> accList) {
        accList = populateSalesOrderLines(accList);
        accList = populateCustomerQuoteLines(accList);
        accList = populateTotalSales(accList);
        accList = populateAvgMarginPercent(accList);
        accList = customerScoreCalculations(accList);
        update accList;
    }   
     
    global void finish(Database.BatchableContext BC) {}
    
    global void execute(SchedulableContext sc) {
      Database.executeBatch(new CustomerScoreCalculationsBatch(), 200);
   }

    private static List<Account> populateSalesOrderLines(List<Account> accList){
        Map<Id, Integer> accountIdToNumberOfSOLMap = new Map<Id, Integer>();
        List<inscor__Sales_Order__c> salesOrderList = [SELECT Id FROM inscor__Sales_Order__c WHERE inscor__Customer__c IN :accList];
        for(AggregateResult aggregateResult : [SELECT COUNT(Id) NumbersOfSOL, inscor__Order__r.inscor__Customer__c AccountId FROM inscor__Sales_Order_Line__c WHERE CreatedDate = LAST_N_DAYS:30 AND inscor__Order__c IN :salesOrderList GROUP BY inscor__Order__r.inscor__Customer__c]) {
            accountIdToNumberOfSOLMap.put((Id)aggregateResult.get('AccountId'), (Integer)aggregateResult.get('NumbersOfSOL'));
        }
        
        for(Account acc : accList){
            if(accountIdToNumberOfSOLMap.containsKey(acc.Id)) {
                acc.Sales_Orders_Lines_Received__c = accountIdToNumberOfSOLMap.get(acc.Id);
            } else {
                acc.Sales_Orders_Lines_Received__c = 0;
            }
        }
        return accList;
    }

    private static List<Account> populateCustomerQuoteLines(List<Account> accList){
        Map<Id, Decimal> accountIdToNumbersOfCQLMap = new Map<Id, Decimal>();
        List<inscor__Customer_Quote__c> customerQuoteList = [SELECT Id FROM inscor__Customer_Quote__c WHERE inscor__Customer__c IN :accList];
        for(AggregateResult aggregateResult : [SELECT COUNT(Id) NumbersOfCQL, inscor__Customer_Quote__r.inscor__Customer__c AccountId FROM inscor__Customer_Quote_Line__c WHERE CreatedDate = LAST_N_DAYS:30 AND inscor__Customer_Quote__c IN :customerQuoteList GROUP BY inscor__Customer_Quote__r.inscor__Customer__c]) {
            accountIdToNumbersOfCQLMap.put((Id)aggregateResult.get('AccountId'), (Decimal)aggregateResult.get('NumbersOfCQL'));
        }

        for(Account acc : accList){
            if(accountIdToNumbersOfCQLMap.containsKey(acc.Id)) {
                acc.Customer_Quotes_Lines_Received__c = accountIdToNumbersOfCQLMap.get(acc.Id);
            } else {
                acc.Customer_Quotes_Lines_Received__c = 0;
            }
        }
        return accList;
    }

    private static List<Account> populateTotalSales(List<Account> accList) {
        Map<Id, Decimal> accountIdToTotalSalesMap = new Map<Id, Decimal>();
        for(AggregateResult aggregateResult : [SELECT SUM(inscor__Sales_Order_Total_Value__c) TotalSales, inscor__Customer__c AccountId FROM inscor__Sales_Order__c WHERE inscor__Customer__c IN :accList GROUP BY inscor__Customer__c]) {
            accountIdToTotalSalesMap.put((Id)aggregateResult.get('AccountId'), (Decimal)aggregateResult.get('TotalSales'));
        }

        for(Account acc : accList){
            if(accountIdToTotalSalesMap.containsKey(acc.Id)) {
                acc.Total_Sales__c = accountIdToTotalSalesMap.get(acc.Id);
            } else {
                acc.Total_Sales__c = 0;
            }
        }
        return accList;
    }

    private static List<Account> populateAvgMarginPercent(List<Account> accList) {
        Map<Id, Decimal> accountIdToAvgMarginPercentMap = new Map<Id, Decimal>();
        for(AggregateResult aggregateResult : [SELECT AVG(inscor__Margin_Percent__c) AverageMarginPercent, inscor__Account__c AccountId FROM inscor__Invoice__c WHERE inscor__Account__c IN :accList GROUP BY inscor__Account__c]) {
            accountIdToAvgMarginPercentMap.put((Id)aggregateResult.get('AccountId'), (Decimal)aggregateResult.get('AverageMarginPercent'));
        }

        for(Account acc : accList) {
            if(accountIdToAvgMarginPercentMap.containsKey(acc.Id)) {
                acc.Average_Margin__c = accountIdToAvgMarginPercentMap.get(acc.Id);
            } else {
                acc.Average_Margin__c = 0;
            }
        }
        return accList;
    }

    private static List<Account> customerScoreCalculations(List<Account> accList) {
        List<Customer_Score_Factor__mdt> customerScoreFactorList = [SELECT Weightage__c, Starting_Number__c, Ending_Number__c, Type__c FROM Customer_Score_Factor__mdt];
        
        Decimal numberOfSOL;
        Decimal numberOfCQL;
        Decimal totalSales;
        Decimal avgMarginPercent;
        for(Account acc : accList) {
            numberOfSOL = acc.Sales_Orders_Lines_Received__c;
            numberOfCQL = acc.Customer_Quotes_Lines_Received__c;
            totalSales = acc.Total_Sales__c;
            avgMarginPercent = acc.Average_Margin__c;
            acc.Customer_Score_2__c = 0;
            for(Customer_Score_Factor__mdt customerScoreFactor : customerScoreFactorList) {
                if(customerScoreFactor.Type__c == 'Sales Orders Lines Received' && customerScoreFactor.Starting_Number__c <= numberOfSOL && (customerScoreFactor.Ending_Number__c == null || customerScoreFactor.Ending_Number__c >= numberOfSOL)) {
                    acc.Customer_Score_2__c += customerScoreFactor.Weightage__c;
                }
                if(customerScoreFactor.Type__c == 'Customer Quotes Lines Received' && customerScoreFactor.Starting_Number__c <= numberOfCQL && (customerScoreFactor.Ending_Number__c == null || customerScoreFactor.Ending_Number__c >= numberOfCQL)) {
                    acc.Customer_Score_2__c += customerScoreFactor.Weightage__c;
                }
                if(customerScoreFactor.Type__c == 'Total Sales' && customerScoreFactor.Starting_Number__c <= totalSales && (customerScoreFactor.Ending_Number__c == null || customerScoreFactor.Ending_Number__c >= totalSales)) {
                    acc.Customer_Score_2__c += customerScoreFactor.Weightage__c;
                }
                if(customerScoreFactor.Type__c == 'Margin' && customerScoreFactor.Starting_Number__c <= avgMarginPercent && (customerScoreFactor.Ending_Number__c == null || customerScoreFactor.Ending_Number__c >= avgMarginPercent)) {
                    acc.Customer_Score_2__c += customerScoreFactor.Weightage__c;
                }
            }
        }
        return accList;
    }
}