src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AcctSeed__Billing_Format__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to configure formatting and display of fields in Billing PDF. Overrides the default Billing Format defined in Accounting Settings.</inlineHelpText>
        <label>Billing Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Billing_Format__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Billing</value>
            </filterItems>
            <infoMessage>The Type must equal &quot;Billing&quot;</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Billing_Format__c</referenceTo>
        <relationshipLabel>Accounts (Billing Format)</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>YayPay_Last_Sync_Date__c</fullName>
        <label>YayPay Last Sync Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AcctSeed__Accounting_Period__c.object
<CustomObject>
    <description>Used to capture all the financial activity that occurs during a specified time period. Accounting periods are typically defined to coincide with a calendar year month.</description>
    <fields>
        <fullName>AcctSeed__End_Date__c</fullName>
        <inlineHelpText>Accounting periods are typically used as months. This denotes the end of the period. Fiscal Months are supported. A period end date can not cross over into the start and end date range of another period.</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Start_Date__c</fullName>
        <inlineHelpText>Accounting periods are typically used as months. This denotes the beginning of the period. Fiscal Months are supported. A period beginning date can not cross over into the start and end date range of another period.</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Accounting  Period</label>
    <nameField>
        <label>Accounting Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AcctSeed__Billing__c.object
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <fields>
        <fullName>AcctSeed__Accounting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to specify accounting period for financial reporting.</inlineHelpText>
        <label>Accounting  Period</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Accounting_Period__c.AcctSeed__Status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <infoMessage>The accounting period status must be open</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Period__c</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Project_Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Billing_Format__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to designate the format of the invoice.</inlineHelpText>
        <label>Billing Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Billing_Format__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Billing</value>
            </filterItems>
            <infoMessage>The type on the PDF Format must be Billing</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Billing_Format__c</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Project_Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>YayPay_Last_Sync_Date__c</fullName>
        <label>YayPay Last Sync Date</label>
        <type>DateTime</type>
    </fields>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AcctSeed__Billing_Credit_Memo__c.object
<CustomObject>
    <description>Used to document the relationship a billing credit memo record and a billing invoice record. A billing credit memo record is created during the apply credit memo process.</description>
    <fields>
        <fullName>AcctSeed__Accounting_Period__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The accounting period associated with the billing credit memo</inlineHelpText>
        <label>Applied Accounting Period</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The accounting period must be open</errorMessage>
            <filterItems>
                <field>AcctSeed__Accounting_Period__c.AcctSeed__Status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <infoMessage>The accounting period status must be open</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Period__c</referenceTo>
        <relationshipLabel>Billing Credit Memos</relationshipLabel>
        <relationshipName>Billing_Credit_Memos</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Billing Credit Memo</label>
    <nameField>
        <displayFormat>BCM-{00000}</displayFormat>
        <label>Billing Credit Memo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Credit Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AcctSeed__Billing_Format__c.object
<CustomObject>
    <description>Used to store configuration and default settings related to the pdf generation of a record.</description>
    <fields>
        <fullName>AcctSeed__Default_Email_Template__c</fullName>
        <inlineHelpText>This is the email template used when emailing Billing PDF Invoices. Use the Template Unique Name NOT the Template Name when populating this field.</inlineHelpText>
        <label>Default Email Template</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>PDF Format</label>
    <nameField>
        <label>PDF Format Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PDF Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>YayPay_Last_Sync_Date__c</fullName>
        <label>YayPay Last Sync Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Invoice__c.object
<CustomObject>
    <fields>
        <fullName>YayPay_Last_Sync_Date__c</fullName>
        <label>YayPay Last Sync Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>inscor__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Billing Contact)</relationshipLabel>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INVC-{0}</displayFormat>
        <label>Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>inscor__Invoice__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>ILID-{0}</displayFormat>
        <label>Invoice Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Price__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Price Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>inscor__Description__c</fullName>
        <label>Description</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <label>Keyword</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unverified</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/YayPay_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Batch_Interval_Minutes__c</fullName>
        <label>Batch Interval Minutes</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Client_Key__c</fullName>
        <label>Client Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndPoint__c</fullName>
        <label>EndPoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Integration_Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Integration Enable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Records_To_Query_Batch__c</fullName>
        <label>Records To Query Batch</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_End_Time__c</fullName>
        <label>Transaction End Time</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>YayPay Configuration</label>
</CustomObject>

src/classes/YayPayOtherChargesControllerTest.cls
@isTest
public class YayPayOtherChargesControllerTest {

    @testSetup()
    private static void setup(){
        AccountTriggerHelper.TriggerDisabled = true;
        Test.setMock(HttpCalloutMock.class, new YayPayMockResponseGenerator());
        Account acc = new Account();
        acc.Name ='Test Account';
        insert acc;
        
        Contact con = new Contact();
        con.FirstName ='Test';
        con.LastName ='Contact';
        con.AccountId = acc.Id;
        con.Email ='test@etst.com';
        insert con;
        
        YayPay_Configuration__c yayPayConfigSetting = YayPay_Configuration__c.getOrgDefaults();   
        yayPayConfigSetting.EndPoint__c = 'https://developer.yaypay.com/api/v1/token';
        yayPayConfigSetting.Transaction_End_Time__c = 10;
        yayPayConfigSetting.Records_To_Query_Batch__c = '10';
        yayPayConfigSetting.Batch_Interval_Minutes__c = 10;
        yayPayConfigSetting.Is_Integration_Enable__c = true;
        yayPayConfigSetting.Client_Key__c = '45q70fmc8n1agi258vhnaoh99e';
        yayPayConfigSetting.Client_Secret__c = '1mqaafklenu997svqlcv8j7u5cifhchdbifd4fdopc759lejmj0';
        upsert yayPayConfigSetting;
        
        Product2 productRec = new Product2(Name = 'Laptop X200', 
                                     Family = 'Hardware', inscor__Keyword__c ='test', inscor__Description__c ='Test Desc.');
        insert productRec;
        
        inscor__Invoice__c inv = new inscor__Invoice__c();
        inv.inscor__Invoice_Date__c = Date.today();
        inv.inscor__Status__c ='Created';
        inv.inscor__Account__c = acc.Id;
        inv.inscor__Billing_Contact__c = con.Id;
        inv.YayPay_Last_Sync_Date__c = DateTime.now();
        insert inv;
        
        inscor__Invoice_Line__c invLine = new inscor__Invoice_Line__c();
        invLine.inscor__Price__c =200;
        invLine.inscor__Quantity__c = 2;
        invLine.inscor__Invoice__c = inv.Id;
        insert invLine;
        
        AcctSeed__Accounting_Period__c period = new AcctSeed__Accounting_Period__c();
        period.Name ='2021-06';
        period.AcctSeed__End_Date__c = date.today().addDays(10);
        period.AcctSeed__Start_Date__c = date.today();
        insert period;
        
        AcctSeed__Billing_Format__c format = new AcctSeed__Billing_Format__c();
        format.Name ='format11';
        format.AcctSeed__Default_Email_Template__c = 'Billing_Email_Template';
        format.AcctSeed__Visualforce_PDF_Page__c = 'BillingProductModernPDF';
        insert format;
        
         AcctSeed__Billing_Format__c format2 = new AcctSeed__Billing_Format__c();
        format2.Name ='format11';
        format2.AcctSeed__Default_Email_Template__c = 'Billing_Email_Template';
        format2.AcctSeed__Visualforce_PDF_Page__c = 'BillingProductModernPDF';
        format2.AcctSeed__Type__c= 'Activity Statement';
        insert format2;
        
        AcctSeed__Billing_Format__c format3= new AcctSeed__Billing_Format__c();
        format3.Name ='format11';
        format3.AcctSeed__Default_Email_Template__c = 'Billing_Email_Template';
        format3.AcctSeed__Visualforce_PDF_Page__c = 'BillingProductModernPDF';
        format3.AcctSeed__Type__c= 'Outstanding Statement';
        insert format3;
        
        AcctSeed__Billing_Format__c format4 = new  AcctSeed__Billing_Format__c();
        format4.Name ='format11';
        format4.AcctSeed__Default_Email_Template__c = 'Billing_Email_Template';
        format4.AcctSeed__Visualforce_PDF_Page__c = 'BillingProductModernPDF';
        format4.AcctSeed__Type__c= 'Billing';
        insert format4;
        
        AcctSeed__GL_Account__c accObj = new AcctSeed__GL_Account__c();
        accObj.Name ='Test';
        accObj.AcctSeed__Sub_Type_1__c = 'Liabilities';
        accObj.AcctSeed__Bank__c = TRUE;
        insert accObj;
        
         AcctSeed__GL_Account__c accObj02 = new AcctSeed__GL_Account__c();
        accObj02.Name ='Test';
        accObj02.AcctSeed__Sub_Type_1__c = 'Liabilities';
        insert accObj02;
        
        AcctSeed__Ledger__c ledger = new AcctSeed__Ledger__c();
        ledger.Name = 'Budget';
        ledger.AcctSeed__Type__c = 'Transactional';
        ledger.AcctSeed__Billing_Activity_Statement_Format__c = format2.Id;
        ledger.AcctSeed__Billing_Outstanding_Statement_Format__c = format3.Id;
        ledger.AcctSeed__Default_Bank_Account__c = accObj.Id;
        ledger.AcctSeed__Default_Billing_Format__c = format4.Id;
        insert ledger;
        
        AcctSeed__Billing__c billing = new AcctSeed__Billing__c();
        billing.AcctSeed__Status__c = 'Posted';
        billing.AcctSeed__Customer__c = acc.Id;
        billing.AcctSeed__Date__c = Date.today();
        billing.inscoras__Invoice__c = inv.Id;
        billing.AcctSeed__Accounting_Period__c = period.Id;
        billing.AcctSeed__Billing_Format__c = format.Id;
        billing.AcctSeed__Ledger__c = ledger.Id;
        //billing.AcctSeed__Type__c = 'Credit Memo';
        insert billing;
        
        AcctSeed__Billing_Line__c billLine = new AcctSeed__Billing_Line__c();
        //billLine.Name = 'Test';
        billLine.AcctSeed__Billing__c = billing.Id;
        billLine.AcctSeed__Rate__c = 2;
        billLine.AcctSeed__Hours_Units__c = 2;
        billLine.AcctSeed__Revenue_GL_Account__c = accObj02.Id;
        billLine.AcctSeed__Tax_Amount2__c = -200;
        insert billLine;  
        
        AcctSeed__Billing__c billing02 = new AcctSeed__Billing__c();
        billing02.AcctSeed__Status__c = 'Posted';
        billing02.AcctSeed__Customer__c = acc.Id;
        billing02.AcctSeed__Date__c = Date.today();
        billing02.inscoras__Invoice__c = inv.Id;
        billing02.AcctSeed__Accounting_Period__c = period.Id;
        billing02.AcctSeed__Billing_Format__c = format.Id;
        billing02.AcctSeed__Ledger__c = ledger.Id;
        //billing.AcctSeed__Type__c = 'Credit Memo';
        insert billing02;
        
        AcctSeed__Billing_Line__c billLine02 = new AcctSeed__Billing_Line__c();
        //billLine.Name = 'Test';
        billLine02.AcctSeed__Billing__c = billing02.Id;
        billLine02.AcctSeed__Rate__c = 2;
        billLine02.AcctSeed__Hours_Units__c = 2;
        billLine02.AcctSeed__Revenue_GL_Account__c = accObj02.Id;
        billLine02.AcctSeed__Tax_Amount2__c = 200;
        insert billLine02;  
        
        AcctSeed__Billing_Credit_Memo__c cMemo = new AcctSeed__Billing_Credit_Memo__c(
            AcctSeed__Accounting_Period__c = period.Id, AcctSeed__Amount__c = -20.0,
            AcctSeed__Billing_Credit_Memo__c = billing.Id, AcctSeed__Billing_Invoice__c = billing02.Id);
        insert cMemo;
    } 
    
    @isTest
    private static void getOtherChargesTest() {
        Test.startTest();
        List<String> getOtherCharges= YayPayOtherChargesController.getOtherCharges();
        Test.stopTest();
    } 
    
    @isTest
    private static void getRecordTest() {
        
        AcctSeed__Billing__c billObj = [ SELECT Id FROM AcctSeed__Billing__c LIMIT 1];
        Test.startTest();
        AcctSeed__Billing__c getRecord= YayPayOtherChargesController.getRecord(billObj.Id);
        Test.stopTest();
    } 
    
    @isTest
    private static void updateBillingCommentTest() {
        
        AcctSeed__Billing__c billObj = [ SELECT Id FROM AcctSeed__Billing__c LIMIT 1];
        Test.startTest();
        AcctSeed__Billing__c updateBillingComment= YayPayOtherChargesController.updateBillingComment(billObj.Id, 'Credit Card Fees');
        Test.stopTest();
    } 
}