src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>inscor__Account_Number__c</fullName>
        <label>Account #</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Company__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Address_1__c</fullName>
        <label>Address 1</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Company_Name__c</fullName>
        <label>Company Name</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>inscor__Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Company</label>
    <nameField>
        <displayFormat>CID-{0}</displayFormat>
        <label>Company ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Condition_Code__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Show_in_Summary__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show in Summary</label>
        <type>Checkbox</type>
    </fields>
    <label>Condition Code</label>
    <nameField>
        <label>Condition Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Exchange_Summary__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>inscor__Company__c</referenceTo>
        <relationshipLabel>Customer Exchange Summaries</relationshipLabel>
        <relationshipName>Customer_Exchange_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <formula>inscor__Original_SO_ID__r.inscor__Customer__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer</label>
        <type>Text</type>
    </fields>
    <label>Customer Exchange Summary</label>
    <nameField>
        <displayFormat>EXS-{0}</displayFormat>
        <label>Customer Exchange Summary ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Exchange Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Business_Category__c</fullName>
        <label>Business Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Business_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Company__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Company</label>
        <referenceTo>inscor__Company__c</referenceTo>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contact must be associated with the selected customer.</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.inscor__Customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_CQ__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Quotes</relationshipLabel>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Closed - Won</fullName>
                </value>
                <value>
                    <fullName>Closed - Lost</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Quote</label>
    <nameField>
        <displayFormat>QU-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Business_Category__c</fullName>
        <label>Business Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Business_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Condition_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Customer_Quote__c</fullName>
        <label>Customer Quote</label>
        <referenceTo>inscor__Customer_Quote__c</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Ready to Quote</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Queued to Quote</fullName>
                </value>
                <value>
                    <fullName>Quoted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Quote Line</label>
    <nameField>
        <displayFormat>QUL-{0}</displayFormat>
        <label>Quote Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Business_Category__c</fullName>
        <label>Business Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Business_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Company__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Company</label>
        <referenceTo>inscor__Company__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_SO__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quote_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Number</label>
        <referenceTo>inscor__Customer_Quote__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In_Progress</fullName>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Partially_Allocated</fullName>
                    <label>Partially Allocated</label>
                </value>
                <value>
                    <fullName>Allocated</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Sales Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Business_Category__c</fullName>
        <label>Business Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Business_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Condition_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <defaultValue>&apos;Open&apos;</defaultValue>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Partially_Allocated</fullName>
                    <label>Partially Allocated</label>
                </value>
                <value>
                    <fullName>Allocated</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{0}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>inscor__Business_Category__c</fullName>
        <label>Business Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Business_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unverified</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FollowUpEmailCtrlTest.cls
/**************************************************************************************************
Description: Test class for Controller class for FollowUpEmail LWCs
====================================================================================================
====================================================================================================
TestClass: 
Code Coverage: 
====================================================================================================
====================================================================================================
History
<Version>   	<Date>             <Author Name>                <Brief description of change > 
1.0 -      		08/28/2021		    Nikhil Kumar Srivastava		 Initial Creation    
***************************************************************************************************/
@IsTest
public with sharing class FollowUpEmailCtrlTest 
{
    public static final Integer COUNT_LIMIT = 5;
    public static List<Integer> daysDifference = new List<Integer>{1,2,3};

    @TestSetup
    private static void setup() 
    { 
        Account accRec = new Account();
        accRec.Name = 'Customer 101';
        accRec.inscor__Account_Number__c = '2';  
        insert accRec;

        Contact c = new Contact();
        c.FirstName = 'Customer';
        c.LastName = 'Contact 101';
        c.Email = 'customercontact101@xyz.com';
        c.AccountId = accRec.Id;
        insert c;

        List<inscor__Customer_Quote__c> customerQuoteToInsertList = new List<inscor__Customer_Quote__c>();
        List<inscor__Customer_Quote_Line__c> customerQuoteLineToInsertList = new List<inscor__Customer_Quote_Line__c>();
        
        inscor__Company__c companyInstance = new inscor__Company__c();
        companyInstance.inscor__Company_Name__c = 'inscor Company' ;
        companyInstance.inscor__Address_1__c = 'address';
        companyInstance.inscor__City__c = 'xyz';
        companyInstance.inscor__Zip_Code__c = '21321';
        insert companyInstance;
        
        for(Integer i = 0; i< COUNT_LIMIT; i++) 
        {
            inscor__Customer_Quote__c customerQuoteRec = new inscor__Customer_Quote__c();
            customerQuoteRec.inscor__Customer__c = accRec.Id;
            customerQuoteRec.inscor__Status__c = 'New';
            customerQuoteRec.inscor__Company__c = companyInstance.id;
            customerQuoteToInsertList.add(customerQuoteRec);
        }
        insert customerQuoteToInsertList;

        List<Opportunity> oppList = new List<Opportunity>([SELECT Id FROM Opportunity]);
        
        for(inscor__Customer_Quote__c quoteRec : customerQuoteToInsertList)
        {
            for(Integer i = 0; i< COUNT_LIMIT; i++) 
            { 
                inscor__Customer_Quote_Line__c qouteLineRec = new inscor__Customer_Quote_Line__c();
                qouteLineRec.inscor__Customer_Quote__c = quoteRec.Id;
                qouteLineRec.inscor__Quantity__c = 10;
                qouteLineRec.inscor__Business_Category__c = 'Distribution';
                customerQuoteLineToInsertList.add(qouteLineRec);
            }  
        }
        insert customerQuoteLineToInsertList;

        inscor__Condition_Code__c conditionCode = new inscor__Condition_Code__c(Name ='Condition Code 1', inscor__Show_in_Summary__c = false);
        insert conditionCode;
        
        List<inscor__Sales_Order__c> salesOrders = new List<inscor__Sales_Order__c>();
        
        for(Integer i = 0; i < COUNT_LIMIT; i++) 
        {
            inscor__Sales_Order__c salesOrder = new inscor__Sales_Order__c();
            salesOrder.inscor__Quote_Number__c = customerQuoteToInsertList[i].Id;
            salesOrder.inscor__Customer__c = accRec.Id;
            salesOrder.inscor__Contact__c = c.Id;
            salesOrder.inscor__Company__c = companyInstance.Id;
            salesOrder.inscor__Assigned_To__c = UserInfo.getUserId();
            salesOrders.add(salesOrder);
        }
        insert salesOrders;  
        
        Product2 product = new Product2(name = '12345', inscor__Keyword__c = 'test', inscor__Description__c = 'Test Description');
        insert product;

        List<inscor__Sales_Order_Line__c> salesOrderLines = new List<inscor__Sales_Order_Line__c>();
        for(Integer i = 0; i< COUNT_LIMIT; i++) 
        {
            inscor__Sales_Order_Line__c salesOrderLine = new inscor__Sales_Order_Line__c();
            salesOrderLine.inscor__Order__c = salesOrders[i].Id;
            salesOrderLine.inscor__Condition_Code__c = conditionCode.Id;
            salesOrderLine.inscor__Quantity_Ordered__c = 10;
            salesOrderLine.inscor__Exchange_Type__c = 'Cost Plus';
			salesOrderLine.inscor__Product__c = product.Id;          
            salesOrderLines.add(salesOrderLine);
        }
        insert salesOrderLines;

        List<inscor__Customer_Exchange_Summary__c> cess = new List<inscor__Customer_Exchange_Summary__c>();
        for(Integer i = 0; i< COUNT_LIMIT; i++) 
        {
            inscor__Customer_Exchange_Summary__c ces = new inscor__Customer_Exchange_Summary__c();
            ces.inscor__Original_SO_ID__c = salesOrders[i].Id;
            ces.inscor__Original_SO_Line__c = salesOrderLines[i].Id;
            ces.inscor__Original_Core_Due_Date__c = Math.mod(i, 2) == 0 ? Date.today().addDays(5): Date.today().addDays(1);
            ces.inscor__Exchange_Status__c = Math.mod(i, 2) == 0 ? Constants.CUSTOMER_EXCHANGE_SUMMARY_EXCHANGE_STATUS_SHIPPED : Constants.CUSTOMER_EXCHANGE_SUMMARY_EXCHANGE_STATUS_CORE_RECEIVED;
            if (i == 4) {
                ces.inscor__Original_Core_Due_Date__c = null;
            }
            ces.inscor__Original_Product__c = product.Id;
            cess.add(ces);
        }
        insert cess;
    }  
    
    @isTest
    public static void validateGetEmailRenderedTemplate()
    {
        List<inscor__Customer_Exchange_Summary__c> cess = [SELECT Id, inscor__Original_Core_Due_Date__c FROM inscor__Customer_Exchange_Summary__c LIMIT 2];
        Test.startTest();
        for(inscor__Customer_Exchange_Summary__c ces : cess)
        {
            if(ces.inscor__Original_Core_Due_Date__c != null && ces.inscor__Original_Core_Due_Date__c == Date.today().addDays(5))
            {
                System.assert(true, FollowUpEmailCtrl.checkDueDateForNext5Day(ces.Id));
            }
            else if(ces.inscor__Original_Core_Due_Date__c != null && ces.inscor__Original_Core_Due_Date__c == Date.today().addDays(1))
            {
                System.assert(true, FollowUpEmailCtrl.checkDueDateForNext1Day(ces.Id));
            }
            List<EmailBody> emailBodyList = new List<EmailBody>();
            for (Integer day : daysDifference) {
                emailBodyList.add(FollowUpEmailCtrl.getEmailRenderedTemplate(ces.Id, day));
            }
            System.assert(emailBodyList.size() > 0);
        }
        Test.stopTest();

        try 
        {
            FollowUpEmailCtrl.getEmailRenderedTemplate(null, null);
        } 
        catch (Exception e) 
        {
            System.assert(e != null);
        }
    }

    @isTest
    public static void validateSendFollowUpEmail()
    {
        Test.startTest();
        List<Account> accList = new List<Account>([SELECT Id,Name FROM Account LIMIT 1]);
        Id contactId = [SELECT Id FROM Contact LIMIT 1]?.Id;
        
        List<inscor__Customer_Exchange_Summary__c> cess = [SELECT Id 
                                                            FROM inscor__Customer_Exchange_Summary__c 
                                                            WHERE inscor__Original_Core_Due_Date__c != null AND inscor__Exchange_Status__c = :Constants.CUSTOMER_EXCHANGE_SUMMARY_EXCHANGE_STATUS_SHIPPED];
        for(inscor__Customer_Exchange_Summary__c ces : cess)
        {   
            String emailBodyJSON = JSON.serialize(FollowUpEmailCtrl.getEmailRenderedTemplate(ces.Id, 1));
            String status = FollowUpEmailCtrl.sendFollowUpEmail(ces.Id, emailBodyJSON);
            System.assert(status == FollowUpEmailCtrl.SUCCESS);
            
            emailBodyJSON = JSON.serialize(FollowUpEmailCtrl.getEmailRenderedTemplate(ces.Id, 2));
            status = FollowUpEmailCtrl.sendFollowUpEmail(ces.Id, emailBodyJSON); 
            System.assert(status == FollowUpEmailCtrl.SUCCESS);
        }
        Test.stopTest();
        try 
        {   
            inscor__Customer_Exchange_Summary__c exchangeSummary = cess[0];
            exchangeSummary.inscor__Original_Core_Due_Date__c = System.today().addDays(-5);
            update exchangeSummary;
            FollowUpEmailCtrl.getFollowUpWrapper(exchangeSummary.Id);

            String emailBodyJSON = JSON.serialize(FollowUpEmailCtrl.getEmailRenderedTemplate(cess[0].Id, 1));
            exchangeSummary.inscor__Original_Core_Due_Date__c = System.today().addDays(5);
            update exchangeSummary;
            FollowUpEmailCtrl.getFollowUpWrapper(exchangeSummary.Id);
            String status = FollowUpEmailCtrl.sendFollowUpEmail(exchangeSummary.Id, emailBodyJSON);
            exchangeSummary.inscor__Original_Core_Due_Date__c = System.today().addDays(5);
            update exchangeSummary;
            FollowUpEmailCtrl.getFollowUpWrapper(exchangeSummary.Id);
            status = FollowUpEmailCtrl.sendFollowUpEmail(exchangeSummary.Id, emailBodyJSON);
            
            exchangeSummary.inscor__Original_Core_Due_Date__c = System.today().addDays(3);
            update exchangeSummary;
            FollowUpEmailCtrl.getFollowUpWrapper(exchangeSummary.Id);
            status = FollowUpEmailCtrl.sendFollowUpEmail(exchangeSummary.Id, emailBodyJSON);
            
            exchangeSummary.inscor__Original_Core_Due_Date__c = System.today().addDays(2);
            update exchangeSummary;
            FollowUpEmailCtrl.getFollowUpWrapper(exchangeSummary.Id);
            status = FollowUpEmailCtrl.sendFollowUpEmail(exchangeSummary.Id, emailBodyJSON);
            
            exchangeSummary.inscor__Original_Core_Due_Date__c = System.today().addDays(1);
            update exchangeSummary;
            FollowUpEmailCtrl.getFollowUpWrapper(exchangeSummary.Id);
            status = FollowUpEmailCtrl.sendFollowUpEmail(exchangeSummary.Id, emailBodyJSON);
            exchangeSummary.inscor__Original_Core_Due_Date__c = System.today().addDays(0);
            update exchangeSummary;
            status = FollowUpEmailCtrl.sendFollowUpEmail(exchangeSummary.Id, emailBodyJSON);
            exchangeSummary.inscor__Original_Core_Due_Date__c = System.today().addDays(-3);
            update exchangeSummary;
            FollowUpEmailCtrl.getFollowUpWrapper(exchangeSummary.Id);
            status = FollowUpEmailCtrl.sendFollowUpEmail(exchangeSummary.Id, emailBodyJSON);
            
            System.assert(status == FollowUpEmailCtrl.SUCCESS);
            FollowUpEmailCtrl.sendFollowUpEmail(cess[0].Id, null);
        } 
        catch (Exception e) 
        {
            System.assert(e != null);
        }

        try 
        {
            FollowUpEmailCtrl.sendFollowUpEmail(null, null);
        } 
        catch (Exception e) 
        {
            System.assert(e != null);
        }
    }
    
    @isTest
    public static void testGetFollowUpWrapper(){
        Test.startTest();
        List<inscor__Customer_Exchange_Summary__c> cess = [SELECT Id FROM inscor__Customer_Exchange_Summary__c];
        for(inscor__Customer_Exchange_Summary__c ces : cess)
        {
            FollowUpEmailCtrl.FollowUpWrapper wrapper = FollowUpEmailCtrl.getFollowUpWrapper(ces.Id);
        }
        inscor__Customer_Exchange_Summary__c exchangeSummary = cess[0];
        exchangeSummary.inscor__Exchange_Status__c = Constants.CUSTOMER_EXCHANGE_SUMMARY_EXCHANGE_STATUS_CORE_RECEIVED;
        update exchangeSummary;
        FollowUpEmailCtrl.FollowUpWrapper wrapper = FollowUpEmailCtrl.getFollowUpWrapper(exchangeSummary.Id); 
        
        wrapper = FollowUpEmailCtrl.getFollowUpWrapper('');
        System.assert(!wrapper.isValid);
        Test.stopTest();
    }
}