src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AcctSeed__Billing_Format__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to configure formatting and display of fields in Billing PDF. Overrides the default Billing Format defined in Accounting Settings.</inlineHelpText>
        <label>Billing Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Billing_Format__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Billing</value>
            </filterItems>
            <infoMessage>The Type must equal &quot;Billing&quot;</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Billing_Format__c</referenceTo>
        <relationshipLabel>Accounts (Billing Format)</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Account_Number__c</fullName>
        <label>Account #</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AcctSeed__Accounting_Period__c.object
<CustomObject>
    <description>Used to capture all the financial activity that occurs during a specified time period. Accounting periods are typically defined to coincide with a calendar year month.</description>
    <fields>
        <fullName>AcctSeed__End_Date__c</fullName>
        <inlineHelpText>Accounting periods are typically used as months. This denotes the end of the period. Fiscal Months are supported. A period end date can not cross over into the start and end date range of another period.</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Start_Date__c</fullName>
        <inlineHelpText>Accounting periods are typically used as months. This denotes the beginning of the period. Fiscal Months are supported. A period beginning date can not cross over into the start and end date range of another period.</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>&quot;Open&quot; allows new transactions to be saved to this period. &quot;Closed&quot; prevents new records from being saved to this period.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Accounting  Period</label>
    <nameField>
        <label>Accounting Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AcctSeed__Billing__c.object
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <fields>
        <fullName>AcctSeed__Accounting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to specify accounting period for financial reporting.</inlineHelpText>
        <label>Accounting  Period</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Accounting_Period__c.AcctSeed__Status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <infoMessage>The accounting period status must be open</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Period__c</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Project_Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Billing_Format__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to designate the format of the invoice.</inlineHelpText>
        <label>Billing Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Billing_Format__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Billing</value>
            </filterItems>
            <infoMessage>The type on the PDF Format must be Billing</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Billing_Format__c</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Project_Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Ledger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Denotes the associated ledger.</inlineHelpText>
        <label>Ledger</label>
        <referenceTo>AcctSeed__Ledger__c</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>Used in approvals and invoices that are in process of being finalized. A posted status indicates the invoice is final and no further changes are to be made.</inlineHelpText>
        <label>Posting Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Waiting for Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <default>true</default>
                    <label>Approved</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <formula>IF(AcctSeed__Total__c &lt; 0, &apos;Credit Memo&apos;,&apos;Invoice&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>A billing can either be an Invoice or Credit memo. An invoice represents money due to your organization. A credit memo represents forgiveness of an Invoice.</inlineHelpText>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AcctSeed__Billing_Format__c.object
<CustomObject>
    <description>Used to store configuration and default settings related to the pdf generation of a record.</description>
    <fields>
        <fullName>AcctSeed__Default_Email_Template__c</fullName>
        <inlineHelpText>This is the email template used when emailing Billing PDF Invoices. Use the Template Unique Name NOT the Template Name when populating this field.</inlineHelpText>
        <label>Default Email Template</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <inlineHelpText>The type of record this PDF format is associated with.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Purchase Order</fullName>
                </value>
                <value>
                    <fullName>Activity Statement</fullName>
                </value>
                <value>
                    <fullName>Outstanding Statement</fullName>
                </value>
                <value>
                    <fullName>Packing Slip</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AcctSeed__Visualforce_PDF_Page__c</fullName>
        <inlineHelpText>The API name of the Visualforce page that is used to display the PDF rendition of the Billing.</inlineHelpText>
        <label>Visualforce PDF Page</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>PDF Format</label>
    <nameField>
        <label>PDF Format Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PDF Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AcctSeed__GL_Account__c.object
<CustomObject>
    <description>Used to document the general ledger accounts used by the financial suite accounting application. This is a traditional general ledger account.</description>
    <fields>
        <fullName>AcctSeed__Bank__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates if the GL Account can be selected to record Cash Receipts and Disbursements and used in Bank Direct Connect and Bank Reconciliation.</inlineHelpText>
        <label>Bank/Credit Card Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Sub_Type_1__c</fullName>
        <inlineHelpText>Used in conjunction with the Type field to further classify GL Accounts. Balance Sheet accounts must be Assets, Liabilities or Owners Equity.</inlineHelpText>
        <label>Sub Type 1</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>AcctSeed__Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Assets</fullName>
                </value>
                <value>
                    <fullName>Cost of Goods Sold</fullName>
                </value>
                <value>
                    <fullName>Facilities</fullName>
                </value>
                <value>
                    <fullName>Labor</fullName>
                </value>
                <value>
                    <fullName>Liabilities</fullName>
                </value>
                <value>
                    <fullName>Owners Equity</fullName>
                </value>
                <value>
                    <fullName>Product Revenue</fullName>
                </value>
                <value>
                    <fullName>Sales &amp; Marketing</fullName>
                </value>
                <value>
                    <fullName>Service Revenue</fullName>
                </value>
                <value>
                    <fullName>General &amp; Administrative</fullName>
                </value>
                <value>
                    <fullName>Operating</fullName>
                </value>
                <value>
                    <fullName>Investing</fullName>
                </value>
                <value>
                    <fullName>Financing</fullName>
                </value>
                <value>
                    <fullName>Other Income</fullName>
                </value>
                <value>
                    <fullName>Other Expense</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <inlineHelpText>Must be Balance Sheet, Revenue or Expense.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Balance Sheet</fullName>
                    <default>true</default>
                    <label>Balance Sheet</label>
                </value>
                <value>
                    <fullName>Revenue</fullName>
                </value>
                <value>
                    <fullName>Expense</fullName>
                </value>
                <value>
                    <fullName>Cash Flow</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AcctSeed__Ledger__c.object
<CustomObject>
    <description>Used to associate and aggregate financial transaction or budget entries with a specific entity.</description>
    <fields>
        <fullName>AcctSeed__Billing_Activity_Statement_Format__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the billing activity statement format here. The billing activity statement format is the PDF format used to send billing activity statements to a customer.</inlineHelpText>
        <label>Billing Activity Statement Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Billing_Format__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Activity Statement</value>
            </filterItems>
            <infoMessage>The type on the PDF Format must be Activity Statement</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Billing_Format__c</referenceTo>
        <relationshipLabel>Ledgers (Billing Activity Statement Format)</relationshipLabel>
        <relationshipName>Billing_Activity_Statement_Formats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <inlineHelpText>You can only create one transactional ledger by default. Contact Accounting Seed Support for assistance in creating additional transactional ledgers.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Budget</fullName>
                    <default>true</default>
                    <label>Budget</label>
                </value>
                <value>
                    <fullName>Transactional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger</label>
    <nameField>
        <label>Ledger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BillingsTriggerHelperTest.cls
/**************************************************************************************************
Description: Trigger class for AcctSeed__Billing__c that will handle all types of trigger events Test Methods.
====================================================================================================
====================================================================================================
Class: BillingsTriggerHelperTest
====================================================================================================
====================================================================================================
History
<Version>   	<Date>             <Author Name>                <Brief description of change > 
1.0 -      		09/03/2021		    Kushal Bagadia				Initial Creation     
***************************************************************************************************/
@isTest
private class BillingsTriggerHelperTest {
    
    @isTest
	private static void test() {
	    Account accRec = new Account();
        accRec.Name = 'TEST Account';
        accRec.inscor__Account_Number__c = '2';  
        insert accRec;
        
        AcctSeed__Accounting_Period__c accPeriod = new AcctSeed__Accounting_Period__c();
        accPeriod.Name = '2021-06';
        accPeriod.AcctSeed__Start_Date__c = System.today();
        accPeriod.AcctSeed__Status__c = 'Open';
        accPeriod.AcctSeed__End_Date__c = System.today();
        insert accPeriod;
        
        AcctSeed__Billing_Format__c billFormat = new AcctSeed__Billing_Format__c();
        billFormat.Name = 'test';
        billFormat.AcctSeed__Default_Email_Template__c =  'Billing_Email_Template';
        billFormat.AcctSeed__Visualforce_PDF_Page__c = 'BillingProductModernPDF';
        insert billFormat;
        
        AcctSeed__GL_Account__c acc = new AcctSeed__GL_Account__c();
        acc.Name = 'Test';
        acc.AcctSeed__Type__c = 'Balance Sheet';
        acc.AcctSeed__Sub_Type_1__c = 'Assets';
        acc.AcctSeed__Bank__c = true;
        insert acc;
        
        AcctSeed__Ledger__c ledger = new AcctSeed__Ledger__c();
        ledger.Name = 'test';
        ledger.AcctSeed__Type__c = 'Transactional';
        ledger.AcctSeed__Billing_Activity_Statement_Format__c = billFormat.Id;
        ledger.AcctSeed__Billing_Outstanding_Statement_Format__c = billFormat.Id;
        ledger.AcctSeed__Default_Bank_Account__c = acc.Id;
        ledger.AcctSeed__Default_Billing_Format__c = billFormat.Id;
        insert ledger;
	    
        AcctSeed__Billing__c billing = new AcctSeed__Billing__c();
        billing.AcctSeed__Shipping_State__c = 'Texas';
        billing.AcctSeed__Billing_State__c = 'Texas';
        billing.AcctSeed__Shipping_Country__c = 'United States';
        billing.AcctSeed__Billing_Country__c = 'United States';
        billing.AcctSeed__Customer__c = accRec.Id;
        billing.AcctSeed__Accounting_Period__c = accPeriod.Id;
        billing.AcctSeed__Billing_Format__c = billFormat.Id;
        // billing.AcctSeed__Default_Billing_Format__c = billFormat.Id;
        billing.AcctSeed__Ledger__c = ledger.Id;
        test.StartTest();
        insert billing;
        billing.AcctSeed__Shipping_State__c = 'Tex';
        update billing;
        delete billing;
        test.StopTest();
	}

}