src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>YayPay_Last_Sync_Date__c</fullName>
        <label>YayPay Last Sync Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>inscor__Account_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Terms</label>
        <referenceTo>inscor__Account_Terms__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Is_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>YayPay_Last_Sync_Date__c</fullName>
        <label>YayPay Last Sync Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Account_Terms__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Number_of_Days__c</fullName>
        <label># of Days</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Account Terms</label>
    <nameField>
        <label>Account Terms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Is_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_File_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is File Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>YayPay_Last_Sync_Date__c</fullName>
        <label>YayPay Last Sync Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>inscor__Account_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Terms</label>
        <referenceTo>inscor__Account_Terms__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Billing Contact)</relationshipLabel>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Customer_PO_Number__c</fullName>
        <label>Customer PO Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Total_Invoice__c</fullName>
        <formula>inscor__Invoice_Value__c + inscor__Freight_Charge__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Invoice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INVC-{0}</displayFormat>
        <label>Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/YayPay_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Batch_Interval_Minutes__c</fullName>
        <label>Batch Interval Minutes</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Records_To_Query_Batch__c</fullName>
        <label>Records To Query Batch</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>YayPay Configuration</label>
</CustomObject>

src/classes/BatchProcessInvoiceFilesToYayPay.cls
global class BatchProcessInvoiceFilesToYayPay implements Database.Batchable<sObject>,Database.AllowsCallouts,Database.Stateful {
    
    Public Set<Id> invoiceIds;
    Public Boolean processInvoiceFiles;
    Public DateTime TokenGenerateTime;
    Public DateTime TokenExpiaryTime;
    Public String accessToken;
    Public Integer tokenGenerateCount =0 ;
    Public String transactionId;
    Public List<inscor__Invoice__c> invoicesToUpdate;
    Public map<String, inscor__Invoice__c> mapInvoiceIdToInvoice;
    Public String LimitRecords;
    Public Integer batchRunInterval;
    global BatchProcessInvoiceFilesToYayPay(){
        invoiceIds = new Set<Id>();
        mapInvoiceIdToInvoice = new map<String, inscor__Invoice__c>();
        invoicesToUpdate = new list<inscor__Invoice__c>();
        processInvoiceFiles = TRUE;
        
        YayPay_Configuration__c config = YayPay_Configuration__c.getOrgDefaults();
        LimitRecords = config.Records_To_Query_Batch__c;
        batchRunInterval = (Integer)config.Batch_Interval_Minutes__c;
        
    }
    global BatchProcessInvoiceFilesToYayPay(Set<Id> Ids, Boolean processFiles ){
        invoiceIds = Ids;
        invoicesToUpdate = new list<inscor__Invoice__c>();
        mapInvoiceIdToInvoice = new map<String, inscor__Invoice__c>();
        processInvoiceFiles = processFiles;
        
        YayPay_Configuration__c config = YayPay_Configuration__c.getOrgDefaults();
        LimitRecords = config.Records_To_Query_Batch__c;
        batchRunInterval = (Integer)config.Batch_Interval_Minutes__c;     
    }
  
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = ' SELECT Id, Name, inscor__Account__c, inscor__Billing_Contact__c, inscor__Customer_PO_Number__c,'+
                  'inscor__Billing_Contact__r.Email, inscor__Account__r.Id, inscor__Invoice_Date__c, '+
                  ' inscor__Billing_Contact__r.Id, inscor__Status__c, inscor__Total_Invoice__c, '+
                  ' inscor__Account__r.inscor__Billing_Contact__r.Email, '+
                  ' inscor__Account_Terms__r.inscor__Number_of_Days__c '+
                  ' FROM  inscor__Invoice__c '+
                  ' WHERE Id != null';
        
        if(invoiceIds.size() > 0){
            query += ' AND Id IN: invoiceIds';
        }else{
            query += ' AND Is_Processed__c = TRUE AND YayPay_Last_Sync_Date__c != null AND Is_File_Processed__c = FALSE ';
        }
        query +=' ORDER BY LastModifiedDate ASC LIMIT ' + LimitRecords ;
       
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<inscor__Invoice__c> invoices){
        
        inscor__Invoice__c invObj = invoices.get(0);
        try{            
            if( TokenExpiaryTime == null || TokenExpiaryTime < System.now() ){
                
                //get Access Token for Request API.
                accessToken = YayPayAuthentication.getAccessToken(); 
                TokenExpiaryTime = System.now().addMinutes(50);
                
                //starting transaction.
                transactionId = YayPayTransactionAPIService.startTransaction( accessToken );
            }
            
            //Process Files.
                if( processInvoiceFiles ){
                    List<ContentDocumentLink> contentDocuLinks = [ SELECT ContentDocumentId, LinkedEntityId 
                                                                  FROM ContentDocumentLink 
                                                                  WHERE LinkedEntity.Type='inscor__Invoice__c' 
                                                                 AND LinkedEntityId =: invObj.Id ];
                    
                    Integer responseCodeFiles;
                    if( contentDocuLinks.size() > 0 ){
                        responseCodeFiles = YayPayAPIService.sendFilesToYayPay( contentDocuLinks, accessToken, transactionId );
                    }
                }
            
            invObj.Is_File_Processed__c = TRUE;
            invoicesToUpdate.add( invObj );
            
        }catch( exception error ){
            invObj.Is_Error__c = TRUE;
            if( !(mapInvoiceIdToInvoice.size() > 0 && mapInvoiceIdToInvoice.containsKey( invObj.Id )) ){
                invoicesToUpdate.add( invObj  );
            }
            LogService.createErrorLog('BatchProcessInvoiceFilesToYayPay.execute', NULL, error, NULL);
        }
        
    }
 
    global void finish(Database.BatchableContext bc){
        try{
            //Finish transaction.
            Integer transactionFinishCode = YayPayTransactionAPIService.finishTransaction( accessToken, transactionId ); 
            update invoicesToUpdate;           
            
        }catch( exception error ){
            LogService.createErrorLog('BatchProcessInvoiceFilesToYayPay.finish', NULL, error, NULL);
        }
    }
}