src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>inscor__Account_Number__c</fullName>
        <label>Account #</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Company__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Address_1__c</fullName>
        <label>Address 1</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Company_Name__c</fullName>
        <label>Company Name</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>inscor__Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Company</label>
    <nameField>
        <displayFormat>CID-{0}</displayFormat>
        <label>Company ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Company__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Company</label>
        <referenceTo>inscor__Company__c</referenceTo>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contact must be associated with the selected customer.</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.inscor__Customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_CQ__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Quotes</relationshipLabel>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Closed - Won</fullName>
                </value>
                <value>
                    <fullName>Closed - Lost</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Quote</label>
    <nameField>
        <displayFormat>QU-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Company__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Company</label>
        <referenceTo>inscor__Company__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.inscor__Customer__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.inscor__Dropship_Site__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.inscor__Dropship_Site__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.inscor__Dropship_Site__c</field>
                <operation>equals</operation>
                <valueField>Contact.inscor__Account_Shipping_Address__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Customer_PO_Number__c</fullName>
        <label>Customer PO Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_SO__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quote_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Number</label>
        <referenceTo>inscor__Customer_Quote__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In_Progress</fullName>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Partially_Allocated</fullName>
                    <label>Partially Allocated</label>
                </value>
                <value>
                    <fullName>Allocated</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Sales Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Condition_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <formula>inscor__Product__r.inscor__Keyword__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Keyword</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <defaultValue>&apos;Open&apos;</defaultValue>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Partially_Allocated</fullName>
                    <label>Partially Allocated</label>
                </value>
                <value>
                    <fullName>Allocated</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{0}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <label>Keyword</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unverified</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__UOM__c</fullName>
        <label>UOM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EA</fullName>
                </value>
                <value>
                    <fullName>FT</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>YD</fullName>
                </value>
                <value>
                    <fullName>BG</fullName>
                </value>
                <value>
                    <fullName>BX</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>DR</fullName>
                </value>
                <value>
                    <fullName>FT2</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>GL</fullName>
                </value>
                <value>
                    <fullName>GLL</fullName>
                </value>
                <value>
                    <fullName>IN2</fullName>
                </value>
                <value>
                    <fullName>KT</fullName>
                </value>
                <value>
                    <fullName>LB</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>ML</fullName>
                </value>
                <value>
                    <fullName>MM</fullName>
                </value>
                <value>
                    <fullName>OZ</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>PT</fullName>
                </value>
                <value>
                    <fullName>QT</fullName>
                </value>
                <value>
                    <fullName>RL</fullName>
                </value>
                <value>
                    <fullName>SF</fullName>
                </value>
                <value>
                    <fullName>SH</fullName>
                </value>
                <value>
                    <fullName>SI</fullName>
                </value>
                <value>
                    <fullName>SP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BackOrdersControllerTest.cls
@IsTest
private class BackOrdersControllerTest {
    @TestSetup
    static void setupData(){
        Account account = new Account();
        account.Name = 'TEST1';
        account.inscor__Account_Number__c = '2';  
        insert account;
        
        Contact contact = new Contact(
            FirstName = 'Jhon',
            LastName =  'Doe1',
            AccountId = account.Id,
            Email = 'standarduser@testorg.com'
        );
        insert contact;
        
        inscor__Company__c  company = new inscor__Company__c(
        inscor__Address_1__c = '1111', inscor__City__c = '1111', inscor__Company_Name__c = '1111', inscor__Zip_Code__c = '1111');
        insert company;

        inscor__Customer_Quote__c customerQuote = new inscor__Customer_Quote__c();
        customerQuote.inscor__Customer__c = account.Id;
        customerQuote.inscor__Status__c = 'New';
        customerQuote.inscor__Company__c = company.Id;
        insert customerQuote;
        
        inscor__Sales_Order__c salesOrder = new inscor__Sales_Order__c();
        salesOrder.inscor__Quote_Number__c = customerQuote.Id;
        salesOrder.inscor__Customer__c = account.Id;
        salesOrder.inscor__Contact__c = contact.Id;
        salesOrder.inscor__Customer_PO_Number__c = 'PO21-00164';
        salesOrder.inscor__Company__c = company.Id;
        insert salesOrder;
        
        Product2 product = new Product2(Name = 'Laptop X7600', 
                                           Family = 'Hardware', inscor__Keyword__c ='test',
                                           inscor__UOM__c = 'EA');
        insert product;
        
        inscor__Condition_Code__c conditionCode = new inscor__Condition_Code__c(Name ='Condition Code 1', inscor__Show_in_Summary__c = false);
        insert conditionCode;
        
        inscor__Sales_Order_Line__c salesOrderLine = new inscor__Sales_Order_Line__c();
        salesOrderLine.inscor__Order__c = salesOrder.Id;
        salesOrderLine.inscor__Condition_Code__c = conditionCode.Id;
        salesOrderLine.inscor__Quantity_Ordered__c = 10;
        salesOrderLine.inscor__Product__c = product.Id;
        salesOrderLine.inscor__Promised_Date__c = Date.newInstance(2022, 12, 5);
        insert salesOrderLine;
        
        // For Is_Super_User__c = true in contact

        Account account2 = new Account();
        account2.Name = 'test Account1';
        account2.inscor__Account_Number__c = '23';
        account2.inscor__Hide_from_CQ__c = false;
        insert account2;
        
        Contact contact2 = new Contact(
            FirstName = 'Harry',
            LastName =  'Adim',
            AccountId = account2.Id,
            Email = 'standarduser@testorg.com',
            Is_Super_User__c = true
        );
        insert contact2;

        inscor__Customer_Quote__c customerQuote2 = new inscor__Customer_Quote__c();
        //customerQuote2.inscor__Customer__c = account2.Id;
        customerQuote2.inscor__Customer__c = account.Id;
        customerQuote2.inscor__Status__c = 'New';
        customerQuote2.inscor__Company__c = company.Id;
        insert customerQuote2;
        
        inscor__Sales_Order__c salesOrder2 = new inscor__Sales_Order__c();
        salesOrder2.inscor__Quote_Number__c = customerQuote2.Id;
        salesOrder2.inscor__Customer__c = account.Id;
        salesOrder2.inscor__Contact__c = contact.Id;
        salesOrder2.inscor__Customer_PO_Number__c = 'PO21-00168';
        salesOrder2.inscor__Company__c = company.Id;
        
        insert salesOrder2;
        
        Product2 product2 = new Product2(
            Name = 'Laptop y45', 
            Family = 'Hardware', inscor__Keyword__c ='test',
            inscor__UOM__c = 'EA'
        );
        insert product2;
        
        inscor__Condition_Code__c conditionCode2 = new inscor__Condition_Code__c(Name ='Condition Code 12', inscor__Show_in_Summary__c = false);
        insert conditionCode2;
        
        inscor__Sales_Order_Line__c salesOrderLine2 = new inscor__Sales_Order_Line__c();
        salesOrderLine2.inscor__Order__c = salesOrder2.Id;
        salesOrderLine2.inscor__Condition_Code__c = conditionCode2.Id;
        salesOrderLine2.inscor__Quantity_Ordered__c = 10;
        salesOrderLine2.inscor__Product__c = product2.Id;
        salesOrderLine2.inscor__Expected_Ship_Date__c = Date.newInstance(2022, 12, 10); 

        insert salesOrderLine2;
        
    }

    @IsTest
    static void getBackOrderIdsPositiveTest(){
        
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Customer Community Plus Login User'];
        Contact contact = [Select Id FROM Contact WHERE Name = 'Harry Adim'];

        User user = new User(
            Alias = 'jhonet', 
            Email ='standarduser@testorg.com', 
            EmailEncodingKey ='UTF-8', 
            LastName ='Maxx', 
            LanguageLocaleKey='en_US', 
            LocaleSidKey = 'en_US', 
            ProfileId = profile.Id,
            ContactId = contact.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'maxx@dev.com'
        );
        insert user;
        Test.startTest();
        System.runAs(user){
            BackOrdersController.getBackOrderIds();
            BackOrdersController.getOrders();
        }
        Test.stopTest();

    }

    @IsTest
    static void getBackOrderIdsNegativeTest(){

        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Customer Community Plus Login User'];
        Contact contact = [Select Id FROM Contact WHERE Name = 'Jhon Doe1'];

        User user = new User(
            Alias = 'jhonet', 
            Email ='standarduser@testorg.com', 
            EmailEncodingKey ='UTF-8', 
            LastName ='Doe', 
            LanguageLocaleKey='en_US', 
            LocaleSidKey = 'en_US', 
            ProfileId = profile.Id,
            ContactId = contact.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'john@dev.com'
        );
        
        Test.startTest();
        System.runAs(user){
            BackOrdersController.getBackOrderIds();
            BackOrdersController.getOrders();
        }
        Test.stopTest();
        
    }

    @IsTest
    static void getOrdersTest(){

        inscor__Sales_Order__c salesOrder = [SELECT Id FROM inscor__Sales_Order__c WHERE inscor__Customer_PO_Number__c = 'PO21-00168'];
        
        Test.startTest();
        BackOrdersController.getOrderLinesById(salesOrder.Id);
        Test.stopTest();
        
    }

    @IsTest
    static void createBackOrderWrapperTest(){

        inscor__Sales_Order__c salesOrder = [SELECT Id, Name, 
                                                inscor__Sales_Order_Total_Value__c, 
                                                inscor__Create_Date__c, 
                                                inscor__Customer_PO_Number__c, inscor__Sales_Order__c.inscor__Contact__r.Name 
                                                FROM inscor__Sales_Order__c 
                                                WHERE inscor__Customer_PO_Number__c = 'PO21-00168'];
        
        Test.startTest();
        BackOrdersController.createBackOrderWrapper(salesOrder);
        Test.stopTest();
        
    }
   
    @IsTest
    static void getOrdersBySearchTest(){
        try{
            String custPO = '';
            String orderDate = null;
            Test.startTest();
            List<BackOrdersController.BackOrderWrapper> resultWrapperList = BackOrdersController.getOrdersBySearch(custPO, orderDate);
            Test.stopTest();
            inscor__Condition_Code__c conditionCode = [SELECT Id, Name FROM inscor__Condition_Code__c WHERE Name = 'Condition Code 12'];

             inscor__Sales_Order_Line__c salesOrderLine = [SELECT Id, Name, 
                                                            inscor__Order__r.inscor__Customer_PO_Number__c, 
                                                            inscor__Create_Date__c FROM inscor__Sales_Order_Line__c
                                                            WHERE inscor__Condition_Code__c =: conditionCode.Id];
            
            //System.assertEquals(resultWrapperList[0].custPo, salesOrderLine.inscor__Order__r.inscor__Customer_PO_Number__c);
            System.assertEquals(resultWrapperList[0].orderDate, salesOrderLine.inscor__Create_Date__c);
        }catch(Exception e) {

        }
    }
}