src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Average_Margin__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Average Margin %</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Customer_Quotes_Lines_Received__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Customer Quotes Lines Received</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Parts_Ordered__c</fullName>
        <label>Number of Parts Ordered</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Parts_Requested__c</fullName>
        <label>Number of Parts Requested</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Orders_Lines_Received__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sales Orders Lines Received</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Sales__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_CQ__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Quotes</relationshipLabel>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Quote</label>
    <nameField>
        <displayFormat>QU-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Customer_Quote__c</fullName>
        <label>Customer Quote</label>
        <referenceTo>inscor__Customer_Quote__c</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Line_Total__c</fullName>
        <formula>inscor__Quantity__c *  inscor__Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer Quote Line</label>
    <nameField>
        <displayFormat>QUL-{0}</displayFormat>
        <label>Quote Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Invoice__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Margin_Percent__c</fullName>
        <formula>( inscor__Invoice_Value__c - inscor__Total_Lines_Cost__c ) / inscor__Invoice_Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Margin %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INVC-{0}</displayFormat>
        <label>Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_SO__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Sales Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Line_Total__c</fullName>
        <formula>inscor__Quantity_Ordered__c *  inscor__Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Order__c</fullName>
        <label>Order</label>
        <referenceTo>inscor__Sales_Order__c</referenceTo>
        <relationshipName>Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity_Ordered__c</fullName>
        <label>Quantity Ordered</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{0}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountUtility.cls
public class AccountUtility {
    /**
     * description : used when customer quote will trigger
     */
    public static void updateCustomerQuoteOrderLineCount(Set<String> accountIds) {
        try{
            Set<String> accIdSet = accountIds;
            if(accIdSet.size() > 0) {
                Map<Id, Decimal> accountIdToNumberOfCQLMap = new Map<Id, Decimal>();
                Map<Id, Decimal> accountIdToNumberOfPartsRequestedMap = new Map<Id, Decimal>();
                for(AggregateResult aggregateResult : [SELECT COUNT(Id) NumbersOfCQL, Sum(inscor__Quantity__c) partsRequested, inscor__Customer_Quote__r.inscor__Customer__c AccountId 
                                                        FROM inscor__Customer_Quote_Line__c 
                                                        WHERE CreatedDate = LAST_N_DAYS:365 AND inscor__Customer_Quote__r.inscor__Customer__c IN :accIdSet 
                                                        GROUP BY inscor__Customer_Quote__r.inscor__Customer__c]) {
                    accountIdToNumberOfCQLMap.put((Id)aggregateResult.get('AccountId'), (Decimal)aggregateResult.get('NumbersOfCQL'));
                    accountIdToNumberOfPartsRequestedMap.put((Id)aggregateResult.get('AccountId'), (Decimal)aggregateResult.get('partsRequested'));
                }

                List<Account> accUpdateList = new List<Account>();
                List<Account> accountsToUpdate = new List<Account>();
                for(String accountId : accountIds){
                    Account acc = new Account(Id = accountId);
                    if (accountIdToNumberOfPartsRequestedMap.containsKey(acc.Id)) {
                        acc.Number_of_Parts_Requested__c = accountIdToNumberOfPartsRequestedMap.get(acc.Id);
                    }
                    if(accountIdToNumberOfCQLMap.containsKey(acc.Id)) {
                        acc.Customer_Quotes_Lines_Received__c = accountIdToNumberOfCQLMap.get(acc.Id);
                    } else {
                        acc.Customer_Quotes_Lines_Received__c = 0;
                    }
                    accountsToUpdate.add(acc);
                }
                update accountsToUpdate;
            }
        } catch(Exception error) {
            System.debug('error:' + error.getMessage());
            LogService.createErrorLog('AccountUtility.apxc', NULL, error, NULL);	
        } 
    }

    /**
     * description : method used to update account fields when Sales Order Line Item Changed or Inserted
     */
    public static void updateCustomerSalesOrderValues(Set<String> accountIds) {
        try{
            //Set<String> accIdSet = getAccountIds(salesOrders);
            if(accountIds.size() > 0) {
                Map<Id, Decimal> accountIdToNumberOfSOLMap = new Map<Id, Decimal>();
                Map<Id, Decimal> accountIdToTotalSalesMap = new Map<Id, Decimal>();
                Map<Id, Decimal> accountIdToNumberOfPartsRequestedMap = new Map<Id, Decimal>();
                for(AggregateResult aggregateResult : [SELECT COUNT(Id) NumbersOfSOL, Sum(inscor__Quantity_Ordered__c) partsRequested,
                                                       SUM(inscor__Line_Total__c) TotalSales,
                                                       inscor__Order__r.inscor__Customer__c AccountId 
                                                       FROM inscor__Sales_Order_Line__c 
                                                       WHERE CreatedDate = LAST_N_DAYS:365 
                                                       AND inscor__Order__r.inscor__Customer__c IN :accountIds
                                                       GROUP BY inscor__Order__r.inscor__Customer__c]) {
                    accountIdToNumberOfSOLMap.put((Id)aggregateResult.get('AccountId'), (Integer)aggregateResult.get('NumbersOfSOL'));
                    accountIdToTotalSalesMap.put((Id)aggregateResult.get('AccountId'), (Decimal)aggregateResult.get('TotalSales'));
                    accountIdToNumberOfPartsRequestedMap.put((Id)aggregateResult.get('AccountId'), (Decimal)aggregateResult.get('partsRequested'));
                }
                List<Account> accountsToUpdate = new List<Account>();
                for(String accountId : accountIds){
                    if (accountIdToNumberOfSOLMap.containsKey(accountId)) {
                        Account acc = new Account(Id = accountId);
                        acc.Number_of_Parts_Ordered__c = accountIdToNumberOfPartsRequestedMap.get(acc.Id);
                        acc.Sales_Orders_Lines_Received__c = accountIdToNumberOfSOLMap.get(acc.Id);
                        acc.Total_Sales__c = accountIdToTotalSalesMap.get(acc.Id);
                        accountsToUpdate.add(acc);
                    }  
                }
                update accountsToUpdate;
            }
        } catch(Exception error) {
            LogService.createErrorLog('SalesOrdersTriggerHelper.apxc', NULL, error, NULL);	
        } 
    }

    /**
     * description : method used when Invoice will trigger
     */
    public static void updateCustomeMargin(Set<String> accIdSet) {
        try{
            //Set<String> accIdSet = getAccountIds(invoices);
            if(accIdSet.size() > 0) {
                Map<Id, Decimal> accountIdToAvgMarginPercentMap = new Map<Id, Decimal>();
                for(AggregateResult aggregateResult : [SELECT AVG(inscor__Margin_Percent__c) AverageMarginPercent, inscor__Account__c AccountId 
                                                        FROM inscor__Invoice__c 
                                                        WHERE CreatedDate = LAST_N_DAYS:365 AND inscor__Account__c IN :accIdSet GROUP BY inscor__Account__c]) {
                    accountIdToAvgMarginPercentMap.put((Id)aggregateResult.get('AccountId'), (Decimal)aggregateResult.get('AverageMarginPercent'));
                }
                List<Account> accUpdateList = new List<Account>();
                for(String accId : accIdSet){
                    Account acc = new Account(Id = accId);
                    if(accountIdToAvgMarginPercentMap.containsKey(acc.Id)) {
                        acc.Average_Margin__c = accountIdToAvgMarginPercentMap.get(acc.Id);
                    } else {
                        acc.Average_Margin__c = 0;
                    }
                    accUpdateList.add(acc);
                }
                update accUpdateList;
            }
        } catch(Exception error) {
            LogService.createErrorLog('InvoiceTriggerHandler.apxc', NULL, error, NULL);	
        } 
    }
}