src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>inscor__Account_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Terms</label>
        <referenceTo>inscor__Account_Terms__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Ship_Terms__c</fullName>
        <label>Ship Terms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Shipping_Terms</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__VAT__c</fullName>
        <inlineHelpText>For recording of the VAT Registration number.</inlineHelpText>
        <label>VAT</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Allocation__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>inscor__Sales_Order__c</referenceTo>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>ALL-{0}</displayFormat>
        <label>Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Release__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Account_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Terms</label>
        <referenceTo>inscor__Account_Terms__c</referenceTo>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Acct__c</fullName>
        <inlineHelpText>If this field is left blank when changing Ship Method then the default Acct # will be filled in automatically.</inlineHelpText>
        <label>Acct #</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_City__c</fullName>
        <label>Billing City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_Country__c</fullName>
        <label>Billing Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_Postal_Code__c</fullName>
        <label>Billing Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_State__c</fullName>
        <label>Billing State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_Street__c</fullName>
        <label>Billing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Contact_Phone__c</fullName>
        <label>Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>inscor__Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Date_Shipped__c</fullName>
        <label>Date Shipped</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>inscor__Dropship_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dropship to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__External_Comments_rt__c</fullName>
        <label>External Comments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>inscor__Freight_Charge__c</fullName>
        <label>Freight Charge</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Release_Value__c</fullName>
        <label>Release Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>inscor__Sales_Order__c</referenceTo>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Ship_Terms__c</fullName>
        <label>Ship Terms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Shipping_Terms</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Shipped_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipped Method</label>
        <referenceTo>inscor__Ship_Method__c</referenceTo>
        <relationshipName>Releases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__State__c</fullName>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Street__c</fullName>
        <label>Street</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>inscor__Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Release</label>
    <nameField>
        <displayFormat>RLS-{0}</displayFormat>
        <label>Release Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Release_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Release__c</fullName>
        <label>Release</label>
        <referenceTo>inscor__Release__c</referenceTo>
        <relationshipName>Release_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Release Line</label>
    <nameField>
        <displayFormat>RLSL-{0}</displayFormat>
        <label>Release Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Release Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Account_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Terms</label>
        <referenceTo>inscor__Account_Terms__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Acct__c</fullName>
        <inlineHelpText>If this field is left blank when changing Ship Method then the default Acct # will be filled in automatically.</inlineHelpText>
        <label>Ship Acct#</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_City__c</fullName>
        <label>Billing City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.inscor__Customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders (Billing Contact)</relationshipLabel>
        <relationshipName>Sales_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_Country__c</fullName>
        <label>Billing Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_Postal_Code__c</fullName>
        <label>Billing Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_State__c</fullName>
        <label>Billing State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_Street__c</fullName>
        <label>Billing Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>inscor__Contact_Phone__c</fullName>
        <label>Shipping Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>inscor__Customer_PO_Number__c</fullName>
        <label>Customer PO Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_SO__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Dropship_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Use this to dropship to another Account.</inlineHelpText>
        <label>Dropship to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders (Dropship to Account)</relationshipLabel>
        <relationshipName>Sales_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Ship_Terms__c</fullName>
        <label>Ship Terms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Shipping_Terms</valueSetName>
        </valueSet>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Sales Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CommercialInvoicePDFSaveAsFileController.cls
public class CommercialInvoicePDFSaveAsFileController {
    
    public inscor__Release__c release{get;set;}
    public List< inscor__Release_Line__c > releaseLines{get;set;}
    public  inscor__Form_Options__c formOptions{get;set;}
    public String imageUrl{get;set;} 
    public Decimal totalAmount{get;set;} 
    public String shippingAddressAccountName{get;set;} 
    
    public CommercialInvoicePDFSaveAsFileController(ApexPages.StandardController stdController) {
        
        String releaseRecordId = ApexPages.currentPage().getParameters().get('Id');
        system.debug('releaseRecordId >> '+releaseRecordId);
        this.release = [Select Id, inscor__Freight_Charge__c, Name, inscor__Sales_Order__r.inscor__Customer__r.Name,
                        inscor__Billing_Street__c, inscor__Billing_City__c, inscor__Billing_State__c, 
                        inscor__Billing_Country__c, inscor__Billing_Postal_Code__c, inscor__Billing_Contact__r.Phone, 
                        inscor__Street__c, inscor__City__c, inscor__State__c, inscor__Country__c, inscor__Zip_Code__c,
                        inscor__Contact_Phone__c, inscor__Date_Shipped__c, inscor__Sales_Order__r.inscor__Customer_PO_Number__c, 
                        inscor__Acct__c, inscor__Sales_Order__r.Name, inscor__Sales_Order__r.inscor__Dropship_to_Account__r.Name, inscor__Shipped_Method__r.Name,
                        inscor__Account_Terms__r.Name, inscor__Ship_Terms__c, inscor__Billing_Contact__r.Name, inscor__Sales_Order__r.inscor__Customer__r.inscor__VAT__c, 
                        inscor__Release_Value__c, inscor__External_Comments_rt__c, inscor__AWB__c FROM inscor__Release__c where Id =: releaseRecordId];
        if(this.release.inscor__Sales_Order__r.inscor__Dropship_to_Account__r.Name != null){
            this.shippingAddressAccountName = this.release.inscor__Sales_Order__r.inscor__Dropship_to_Account__r.Name;
        }else{
            this.shippingAddressAccountName = this.release.inscor__Sales_Order__r.inscor__Customer__r.Name;
        }
         totalAmount = 0;
        if(release.inscor__Freight_Charge__c != null){
            totalAmount = release.inscor__Release_Value__c + release.inscor__Freight_Charge__c;
        }else{
            totalAmount = release.inscor__Release_Value__c;
        }
        setReleaseLines(releaseRecordId);
        imageUrl = 'https://mobiledemand-barcode.azurewebsites.net/barcode/image?content=' + this.release.Name + '&size=50&symbology=CODE_128&format=png&text=false';
        setfooter();
        
    }
    
    private void setReleaseLines(String releaseId){
        releaseLines = [SELECT Id, Name, inscor__Allocation__r.inscor__Inventory_Line__r.inscor__Product__r.Name,
                        inscor__Allocation__r.inscor__Inventory_Line__r.inscor__Serial_Number__c,
                        inscor__Allocation__r.inscor__Inventory_Line__r.inscor__Batch_LOT__c,
                        inscor__Allocation__r.inscor__Inventory_Line__r.inscor__Product__r.inscor__HTS_Code__c,
                        inscor__Allocation__r.inscor__Inventory_Line__r.inscor__Product__r.ECCN_Value__c, 
                        inscor__Allocation__r.inscor__Inventory_Line__r.inscor__Condition_Code__r.Name,
                        inscor__Allocation__r.inscor__Inventory_Line__r.inscor__Product__r.inscor__Description__c,
                        inscor__Allocation__r.inscor__Inventory_Line__r.inscor__UOM__c,
                        inscor__Quantity__c, inscor__Price__c, inscor__Line_Value__c, inscor__Part_Number__c
                        FROM inscor__Release_Line__c
                        WHERE inscor__Release__c =:releaseId];
    }
    
    private void setfooter(){
        formOptions = [select id, name, inscor__Footer__c, inscor__Body_1__c from inscor__Form_Options__c where name='Packing Slip (Priced)' limit 1];
        String formattedFooter = formOptions.inscor__Body_1__c == null ? '' : formOptions.inscor__Body_1__c.remove('<p>')
            .replaceAll('</p>', '<br/>')
            .removeEnd('<br/>');
        formOptions.inscor__Footer__c = formattedFooter;
    }
    

}