src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>inscor__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Activity__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Activity_Type__c</fullName>
        <label>Activity Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Receiving</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>ACQ Cost Change</fullName>
                </value>
                <value>
                    <fullName>Rep Cost Change</fullName>
                </value>
                <value>
                    <fullName>Qty Change</fullName>
                </value>
                <value>
                    <fullName>Receiving RMA</fullName>
                </value>
                <value>
                    <fullName>Cancel Shipment</fullName>
                </value>
                <value>
                    <fullName>Issued Credit</fullName>
                </value>
                <value>
                    <fullName>New Inventory</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Return Inventory</fullName>
                </value>
                <value>
                    <fullName>Return Core</fullName>
                </value>
                <value>
                    <fullName>Core Repair</fullName>
                </value>
                <value>
                    <fullName>Send Repaired</fullName>
                </value>
                <value>
                    <fullName>Release Protected Inventory</fullName>
                </value>
                <value>
                    <fullName>Cancel Receipt</fullName>
                </value>
                <value>
                    <fullName>Cancel Exchange</fullName>
                </value>
                <value>
                    <fullName>Material Issue WIP</fullName>
                </value>
                <value>
                    <fullName>Material Return WIP</fullName>
                </value>
                <value>
                    <fullName>Inventory Import</fullName>
                </value>
                <value>
                    <fullName>Labor WIP</fullName>
                </value>
                <value>
                    <fullName>WIP Parts Reject</fullName>
                </value>
                <value>
                    <fullName>Return EX Core</fullName>
                </value>
                <value>
                    <fullName>Consignor Payable</fullName>
                </value>
                <value>
                    <fullName>WO Invoice</fullName>
                </value>
                <value>
                    <fullName>Owner Adjustment</fullName>
                </value>
                <value>
                    <fullName>Misc Charge WIP</fullName>
                </value>
                <value>
                    <fullName>Lease Invoice</fullName>
                </value>
                <value>
                    <fullName>Expense Report</fullName>
                </value>
                <value>
                    <fullName>Voucher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Customer_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer/Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transaction Activities</relationshipLabel>
        <relationshipName>Transaction_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__INVC_Date__c</fullName>
        <label>INVC Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>inscor__INVC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>INVC #</label>
        <referenceTo>inscor__Invoice__c</referenceTo>
        <relationshipLabel>Transaction Activities</relationshipLabel>
        <relationshipName>Transaction_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>inscor__Line_Value__c</fullName>
        <label>Line Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>inscor__Receivable_Amount__c</fullName>
        <label>Receivable Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Transaction Activity</label>
    <nameField>
        <displayFormat>AID-{0}</displayFormat>
        <label>Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Invoice__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Billing Contact)</relationshipLabel>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INVC-{0}</displayFormat>
        <label>Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>inscor__Invoice__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>ILID-{0}</displayFormat>
        <label>Invoice Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Price__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Price Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/YayPay_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Batch_Interval_Minutes__c</fullName>
        <label>Batch Interval Minutes</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Client_Key__c</fullName>
        <label>Client Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndPoint__c</fullName>
        <label>EndPoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Records_To_Query_Batch__c</fullName>
        <label>Records To Query Batch</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_End_Time__c</fullName>
        <label>Transaction End Time</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>YayPay Configuration</label>
</CustomObject>

src/classes/TransactionActivityTriggerHelperTest.cls
@isTest
private class TransactionActivityTriggerHelperTest {
	
    @testSetup()
    private static void setup(){
		Account acc = new Account();
        acc.Name ='Test Account';
        insert acc;
        
        Contact con = new Contact();
        con.FirstName ='Test';
        con.LastName ='Contact';
        con.AccountId = acc.Id;
        con.Email ='test@etst.com';
        insert con;
        
        YayPay_Configuration__c yayPayConfigSetting = YayPay_Configuration__c.getOrgDefaults();   
        yayPayConfigSetting.EndPoint__c = 'https://developer.yaypay.com/api/v1/token';
        yayPayConfigSetting.Transaction_End_Time__c = 10;
        yayPayConfigSetting.Records_To_Query_Batch__c = '10';
        yayPayConfigSetting.Batch_Interval_Minutes__c = 10;
        yayPayConfigSetting.Client_Key__c = '45q70fmc8n1agi258vhnaoh99e';
        yayPayConfigSetting.Client_Secret__c = '1mqaafklenu997svqlcv8j7u5cifhchdbifd4fdopc759lejmj0';
        upsert yayPayConfigSetting;
    }    
    
    @isTest
    static void batchWithParamTest() {
       
        Account acc = [ SELECT Id FROM Account LIMIT 1];
        Contact con = [ SELECT Id FROM Contact LIMIT 1];
        inscor__Invoice__c inv = new inscor__Invoice__c();
        inv.inscor__Invoice_Date__c = Date.today();
        inv.inscor__Status__c ='Created';
        inv.inscor__Account__c = acc.Id;
        inv.inscor__Billing_Contact__c = con.Id;
        insert inv;
        
        inscor__Invoice_Line__c invLine = new inscor__Invoice_Line__c();
        invLine.inscor__Price__c =200;
        invLine.inscor__Quantity__c = 2;
        invLine.inscor__Invoice__c = inv.Id;
        
        Test.setMock(HttpCalloutMock.class, new YayPayMockResponseGenerator());
        Test.startTest();
        insert invLine;
        Test.stopTest();
    } 
    
    
    @isTest
    static void batchWithoutParamTest() {
        Account acc = [ SELECT Id FROM Account LIMIT 1];
        Contact con = [ SELECT Id FROM Contact LIMIT 1];
        inscor__Invoice__c inv = new inscor__Invoice__c();
        inv.inscor__Invoice_Date__c = Date.today();
        inv.inscor__Status__c ='Created';
        inv.inscor__Account__c = acc.Id;
        inv.inscor__Billing_Contact__c = con.Id;
        insert inv;
        
        inscor__Activity__c payment = new inscor__Activity__c();
        payment.inscor__Activity_Type__c = 'Receiving';
        payment.inscor__Customer_Vendor__c = acc.Id;
        payment.inscor__INVC_Date__c = Date.today();
        payment.inscor__Receivable_Amount__c = 50;
        payment.inscor__INVC__c = inv.Id;
        insert payment; 
        
        inscor__Invoice_Line__c invLine = new inscor__Invoice_Line__c();
        invLine.inscor__Price__c =200;
        invLine.inscor__Quantity__c = 2;
        invLine.inscor__Invoice__c = inv.Id;
        insert invLine;
        
        inv.inscor__Status__c ='Paid';
        update inv;
        Test.setMock(HttpCalloutMock.class, new YayPayMockResponseGenerator());
        Test.startTest();
        payment.inscor__Line_Value__c = 300;
        update payment;
       
        Test.stopTest();
    }    
}