src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>inscor__Account_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Terms</label>
        <referenceTo>inscor__Account_Terms__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Account_Ship_Address__c.object
<CustomObject>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__State__c</fullName>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Street__c</fullName>
        <label>Street</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Account Ship Address</label>
    <nameField>
        <label>Account Ship Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Ship Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Release__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Account_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Terms</label>
        <referenceTo>inscor__Account_Terms__c</referenceTo>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Dropship_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dropship Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.inscor__Dropship_to_Account__c</field>
                <operation>equals</operation>
                <valueField>inscor__Account_Ship_Address__c.inscor__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>inscor__Account_Ship_Address__c</referenceTo>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Dropship_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dropship to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Incoterms__c</fullName>
        <label>Incoterms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Incoterms</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>inscor__Sales_Order__c</referenceTo>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Ship_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If wanting to use the default Acct # when setting/changing Ship Method, make sure that Acct # is blank. If Acct # is filled in then it will not be automatically set.</inlineHelpText>
        <label>Ship Method</label>
        <referenceTo>inscor__Ship_Method__c</referenceTo>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Ship_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Address</label>
        <referenceTo>inscor__Account_Ship_Address__c</referenceTo>
        <relationshipName>Releases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__State__c</fullName>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Street__c</fullName>
        <label>Street</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Release</label>
    <nameField>
        <displayFormat>RLS-{0}</displayFormat>
        <label>Release Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Release_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Line_Value__c</fullName>
        <formula>inscor__Quantity__c *  inscor__Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity__c</fullName>
        <formula>IF(ISPICKVAL(inscor__Release__r.inscor__Release_Type__c, &apos;Sales Order&apos;),inscor__Allocation__r.inscor__Quantity_Allocated__c + inscor__Allocation__r.inscor__Quantity_Shipped__c,
IF(ISPICKVAL(inscor__Release__r.inscor__Release_Type__c, &apos;Repair Order&apos;), IF(ISBLANK(inscor__RO_Issue__c),inscor__Repair_Order_Line__r.inscor__Quantity_to_Repair__c,inscor__RO_Issue__r.inscor__Quantity_to_Issue__c),
IF(ISPICKVAL(inscor__Release__r.inscor__Release_Type__c, &apos;Credit&apos;), inscor__Allocation__r.inscor__Quantity_Invoiced__c, 
if(ISPICKVAL(inscor__Release__r.inscor__Release_Type__c, &apos;Purchase Order&apos;), inscor__Purchase_Order_Line__r.inscor__Quantity__c, inscor__Quantity_To_Ship__c ))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>inscor__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order Line</label>
        <referenceTo>inscor__Sales_Order_Line__c</referenceTo>
        <relationshipName>Release_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Release Line</label>
    <nameField>
        <displayFormat>RLSL-{0}</displayFormat>
        <label>Release Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Release Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Account_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Terms</label>
        <referenceTo>inscor__Account_Terms__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_SO__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Dropship_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If a Dropship to Account has been selected, use this to override the default address with any of the optional shipping addresses.</inlineHelpText>
        <label>Dropship Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.inscor__Dropship_to_Account__c</field>
                <operation>equals</operation>
                <valueField>inscor__Account_Ship_Address__c.inscor__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>inscor__Account_Ship_Address__c</referenceTo>
        <relationshipLabel>Sales Orders (Dropship Site)</relationshipLabel>
        <relationshipName>Sales_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Dropship_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Use this to dropship to another Account.</inlineHelpText>
        <label>Dropship to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders (Dropship to Account)</relationshipLabel>
        <relationshipName>Sales_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Incoterms__c</fullName>
        <label>Incoterms - RETIRED</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Incoterms</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Ship_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If wanting to use the default Acct # when setting/changing Ship Method, make sure that Acct # is blank. If Acct # is filled in then it will not be automatically set.</inlineHelpText>
        <label>Ship Method</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>inscor__Ship_Method__c.inscor__Account__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.inscor__Customer__c</field>
                <operation>equals</operation>
                <valueField>inscor__Ship_Method__c.inscor__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>inscor__Ship_Method__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Ship_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Address</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.inscor__Customer__c</field>
                <operation>equals</operation>
                <valueField>inscor__Account_Ship_Address__c.inscor__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>inscor__Account_Ship_Address__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Sales Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{0}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchProcessReleaseToShipment.cls
global class BatchProcessReleaseToShipment implements Database.Batchable<sObject>,Database.AllowsCallouts,Database.Stateful, Schedulable {
    
    Public Set<Id> releaseIds;
    global BatchProcessReleaseToShipment(){
        releaseIds = new Set<Id>();
    }
    global BatchProcessReleaseToShipment(Set<Id> Ids){
        releaseIds = Ids;
    }
    
    global void execute(SchedulableContext sc) {
    	Database.executeBatch(new BatchProcessReleaseToShipment(releaseIds), 20);
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Name, LastModifiedBy.Name, '+
            'inscor__Account_Terms__c, inscor__Account_Terms__r.Name, inscor__Incoterms__c, '+
            'inscor__Sales_Order__c, inscor__Sales_Order__r.inscor__Customer__c, '+
            'inscor__Ship_To_Address__r.inscor__Country__c,'+
            'inscor__Ship_To_Address__r.inscor__State__c, inscor__Dropship_Site__c,'+
            'inscor__Dropship_to_Account__r.ShippingCountry, inscor__Dropship_to_Account__c,'+
            'inscor__Dropship_Site__r.inscor__Street__c, inscor__Dropship_Site__r.inscor__City__c,'+
            'inscor__Dropship_Site__r.inscor__Postal_Code__c,'+
            'inscor__Dropship_Site__r.inscor__Country__c, inscor__Dropship_Site__r.inscor__State__c,'+
            'inscor__Dropship_to_Account__r.ShippingState, '+
            ' inscor__Ship_Method__r.Name, ' +
                    '( SELECT Id, inscor__Quantity__c, inscor__Line_Value__c,  ' +
					'inscor__Sales_Order_Line__c, inscor__Sales_Order_Line__r.Id, ' +
                    ' inscor__Sales_Order_Line__r.inscor__Product__r.Name, ' +
                    ' inscor__Sales_Order_Line__r.inscor__Keyword__c, ' +
                    ' inscor__Sales_Order_Line__r.inscor__Quantity_Ordered__c, '+
                    ' inscor__Sales_Order_Line__r.inscor__Price__c, '+
                    ' inscor__Sales_Order_Line__r.inscor__Line_Total__c, ' +
                    ' inscor__Sales_Order_Line__r.inscor__Product__r.inscor__HazMat__c, ' +
                    ' inscor__Sales_Order_Line__r.inscor__Product__r.inscor__HazMat_Id__c, ' +
                    ' inscor__Sales_Order_Line__r.inscor__Product__r.inscor__Country_of_Origin__c, ' +
                    ' inscor__Sales_Order_Line__r.inscor__Product__r.Description, ' +
                    ' inscor__Sales_Order_Line__r.inscor__Product__r.IsActive, ' +
                    ' inscor__Sales_Order_Line__r.inscor__Product__r.inscor__HTS_Code__c, ' +
            		' inscor__Sales_Order_Line__r.inscor__Product__r.inscor__Non_Inventory_Item__c, ' +
            		' inscor__Sales_Order_Line__r.inscor__Product__r.inscor__ECCN__r.Name, ' +
                    ' inscor__Sales_Order_Line__r.inscor__Order__r.inscor__Customer_PO_Number__c, ' +
                    ' inscor__Sales_Order_Line__r.inscor__Order__r.Id, ' +
                    ' inscor__Sales_Order_Line__r.inscor__Order__r.createdDate, inscor__Quantity_To_Ship__c '+
                    ' FROM inscor__Release_Lines__r '+
            		' WHERE inscor__Sales_Order_Line__r.inscor__Product__r.inscor__Non_Inventory_Item__c = FALSE )' +
            'FROM  inscor__Release__c '+
            'WHERE inscor__Sales_Order__c != null';
        
        if(releaseIds.size() > 0){
            query += ' AND Id IN: releaseIds';
        }
        //system.assert(false,query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<inscor__Release__c> releases){
        ReleaseToShipmentAPIService.sendShipmentToCompliance(releases);
    }
    
    global void finish(Database.BatchableContext bc){
        Integer intervalMinutes = 1;
        DateTime now  = DateTime.now();
        DateTime nextRunTime = now.addMinutes(intervalMinutes);
        String cronString = '' + nextRunTime.second() + ' ' + nextRunTime.minute() + ' ' + 
            nextRunTime.hour() + ' ' + nextRunTime.day() + ' ' + 
            nextRunTime.month() + ' ? ' + nextRunTime.year(); 
        System.schedule('BatchUpdateShipmentStatus -' + now.format('yyyy-MM-dd HH:mm:ss'), cronString, new BatchUpdateShipmentStatus());
        //Database.executeBatch(new BatchUpdateShipmentStatus(releaseIds), 20);
    }
}