src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>inscor__Account_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Terms</label>
        <referenceTo>inscor__Account_Terms__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Compliance_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>EIMType__c</fullName>
        <label>EIMType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exporter_TPID__c</fullName>
        <label>Exporter TPID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exporter_TPName__c</fullName>
        <label>Exporter TPName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FreightChargesFor__c</fullName>
        <label>FreightChargesFor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FreightPrepaidCollect__c</fullName>
        <label>FreightPrepaidCollect</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mode_of_Transport_Code__c</fullName>
        <label>Mode of Transport Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OriginCountry__c</fullName>
        <label>OriginCountry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OriginState__c</fullName>
        <label>OriginState</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Place_of_Loading__c</fullName>
        <label>Place of Loading</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PortofExit__c</fullName>
        <label>PortofExit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReasonForExport__c</fullName>
        <label>ReasonForExport</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipFrom_TPID__c</fullName>
        <label>ShipFrom TPID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipFrom_TPName__c</fullName>
        <label>ShipFrom TPName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipmentCurrency__c</fullName>
        <label>ShipmentCurrency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Singed_by__c</fullName>
        <label>Singed by</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubmissionEnvironment__c</fullName>
        <label>SubmissionEnvironment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Compliance Configuration</label>
</CustomObject>

src/objects/inscor__Account_Ship_Address__c.object
<CustomObject>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__State__c</fullName>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Street__c</fullName>
        <label>Street</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Account Ship Address</label>
    <nameField>
        <label>Account Ship Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Ship Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Release__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Account_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Terms</label>
        <referenceTo>inscor__Account_Terms__c</referenceTo>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Dropship_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dropship Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.inscor__Dropship_to_Account__c</field>
                <operation>equals</operation>
                <valueField>inscor__Account_Ship_Address__c.inscor__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>inscor__Account_Ship_Address__c</referenceTo>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Incoterms__c</fullName>
        <label>Incoterms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Incoterms</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>inscor__Sales_Order__c</referenceTo>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Ship_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If wanting to use the default Acct # when setting/changing Ship Method, make sure that Acct # is blank. If Acct # is filled in then it will not be automatically set.</inlineHelpText>
        <label>Ship Method</label>
        <referenceTo>inscor__Ship_Method__c</referenceTo>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Ship_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Address</label>
        <referenceTo>inscor__Account_Ship_Address__c</referenceTo>
        <relationshipName>Releases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__State__c</fullName>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Street__c</fullName>
        <label>Street</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Release</label>
    <nameField>
        <displayFormat>RLS-{0}</displayFormat>
        <label>Release Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Release_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Release__c</fullName>
        <label>Release</label>
        <referenceTo>inscor__Release__c</referenceTo>
        <relationshipName>Release_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Release Line</label>
    <nameField>
        <displayFormat>RLSL-{0}</displayFormat>
        <label>Release Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Release Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Account_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Terms</label>
        <referenceTo>inscor__Account_Terms__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Customer_PO_Number__c</fullName>
        <label>Customer PO Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Dropship_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If a Dropship to Account has been selected, use this to override the default address with any of the optional shipping addresses.</inlineHelpText>
        <label>Dropship Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.inscor__Dropship_to_Account__c</field>
                <operation>equals</operation>
                <valueField>inscor__Account_Ship_Address__c.inscor__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>inscor__Account_Ship_Address__c</referenceTo>
        <relationshipLabel>Sales Orders (Dropship Site)</relationshipLabel>
        <relationshipName>Sales_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Incoterms__c</fullName>
        <label>Incoterms - RETIRED</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Incoterms</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Ship_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If wanting to use the default Acct # when setting/changing Ship Method, make sure that Acct # is blank. If Acct # is filled in then it will not be automatically set.</inlineHelpText>
        <label>Ship Method</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>inscor__Ship_Method__c.inscor__Account__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.inscor__Customer__c</field>
                <operation>equals</operation>
                <valueField>inscor__Ship_Method__c.inscor__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>inscor__Ship_Method__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Ship_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Address</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.inscor__Customer__c</field>
                <operation>equals</operation>
                <valueField>inscor__Account_Ship_Address__c.inscor__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>inscor__Account_Ship_Address__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Sales Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ComplianceRequestHelper.cls
public class ComplianceRequestHelper {
    

    public static String createRequestXMLToSendShipment(inscor__Release__c release, 
                                                        inscor__Sales_Order__c salesOrder,
                                                        Account customer)
    {
        
        Contact con;
        if(customer.Contacts.size() > 0){
            con = customer.Contacts[0];
        }
        
        String termsofSaleCode = release.inscor__Account_Terms__c != null ? String.valueOf(release.inscor__Account_Terms__c).substring(0,8) : '';
        String destCountry;
        String destState;
        if(release.inscor__Ship_To_Address__c != null){
            destCountry = release.inscor__Ship_To_Address__r.inscor__Country__c;
            destState = release.inscor__Ship_To_Address__r.inscor__State__c;
        }else if(release.inscor__Dropship_Site__c != null){
            destCountry = release.inscor__Dropship_Site__r.inscor__Country__c;
            destState = release.inscor__Dropship_Site__r.inscor__State__c;
        }
        
        destCountry = CountryStateUtility.getCountryCode(destCountry);
        destState = CountryStateUtility.getStateCode(destState);
        
        Compliance_Configuration__c config = Compliance_Configuration__c.getOrgDefaults(); 
        
        String customerXML = '<TPID>'+customer.Id+'</TPID>'+
                              '<TPName>'+ComplianceUtility.getStringValue(customer.Name)+'</TPName>'+
                              '<TPAddress>'+ComplianceUtility.getStringValue(customer.ShippingStreet)+'</TPAddress>'+
                              '<TPCity>'+ComplianceUtility.getStringValue(customer.ShippingCity)+'</TPCity>'+
                              '<TPZipPostCode>'+ComplianceUtility.getStringValue(customer.ShippingPostalCode)+'</TPZipPostCode>'+
                              '<TPState>'+ComplianceUtility.getStringValue(customer.ShippingState)+'</TPState>'+
                              '<TPCountry>'+ComplianceUtility.getStringValue( destCountry )+'</TPCountry>'+
                              '<TPTelephone>'+ComplianceUtility.formatAccountContactPhone(customer.Phone)+'</TPTelephone>';
                                
        if(release.inscor__Dropship_Site__c != null){
            customerXML = '<TPID>'+customer.Id+'</TPID>'+
                              '<TPName>'+ComplianceUtility.getStringValue(customer.Name)+'</TPName>'+
                              '<TPAddress>'+ComplianceUtility.getStringValue(release.inscor__Dropship_Site__r.inscor__Street__c)+'</TPAddress>'+
                              '<TPCity>'+ComplianceUtility.getStringValue(release.inscor__Dropship_Site__r.inscor__City__c)+'</TPCity>'+
                              '<TPZipPostCode>'+ComplianceUtility.getStringValue(release.inscor__Dropship_Site__r.inscor__Postal_Code__c)+'</TPZipPostCode>'+
                              '<TPState>'+ComplianceUtility.getStringValue(release.inscor__Dropship_Site__r.inscor__State__c)+'</TPState>'+
                              '<TPCountry>'+ComplianceUtility.getStringValue( destCountry )+'</TPCountry>'+
                              '<TPTelephone>'+ComplianceUtility.formatAccountContactPhone(customer.Phone)+'</TPTelephone>';
                                
       
        
        }
        
            if(con != null){
                customerXML += '<ContactName>'+ComplianceUtility.getStringValue(con.Name)+'</ContactName>'+
                                '<ContactTitle>'+ComplianceUtility.getStringValue(con.Title)+'</ContactTitle>'+
                                '<ContactPhone>'+ComplianceUtility.formatAccountContactPhone(con.Phone)+'</ContactPhone>'+
                                '<ContactEmail>'+ComplianceUtility.getStringValue(con.Email)+'</ContactEmail>';
            }
        
        String requestXML = '<![CDATA[';
        
        requestXML += '<?xml version="1.0" encoding="UTF-8"?>'+
                       '<Shipment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://edm.visualcompliance.com/edwinimport/xml/VD-EDM%20Shipment%20V2.1.xsd">'+
                           '<EIMReferenceID>'+release.Name+'</EIMReferenceID>'+
                           '<EIMType>'+ config.EIMType__c +'</EIMType>'+
                           '<SubmissionEnvironment>'+config.SubmissionEnvironment__c+'</SubmissionEnvironment>'+
                           '<ShipmentRefNo>'+release.Name+'</ShipmentRefNo>'+
                           '<ClientShipmentReference>'+release.Name+'</ClientShipmentReference>'+
                           '<Exporter>'+
                              '<TPID>'+ config.Exporter_TPID__c +'</TPID>'+
                              '<TPName>'+ config.Exporter_TPName__c +'</TPName>'+
                           '</Exporter>'+
                           '<Shipfrom>'+
                              '<TPID>'+ config.ShipFrom_TPID__c +'</TPID>'+
                              '<TPName>'+ config.ShipFrom_TPName__c +'</TPName>'+
                           '</Shipfrom>'+
                    '<ModeofTransport>'+  config.Mode_of_Transport_Code__c +'</ModeofTransport>' +
                           '<IsContainer />'+
                           '<OriginCountry>'+ config.OriginCountry__c +'</OriginCountry>'+
                           '<OriginState>'+ config.OriginState__c +'</OriginState>'+
                           '<ShipDateTime>'+ComplianceUtility.formatDate(Date.today())+'</ShipDateTime>'+
                           '<PortofExit>'+ config.PortofExit__c +'</PortofExit>'+
                           '<DestCountry>'+destCountry+'</DestCountry>'+
                           '<DestState>'+destState+'</DestState>'+
                           '<SignedBy>'+config.Singed_by__c+'</SignedBy>'+
                           '<ReasonForExport>'+ config.ReasonForExport__c +'</ReasonForExport>'+
                           '<RoutedTransaction />'+
                           '<IsHazmat />'+
                           '<FTZ />'+
                           '<PortofUnloading />'+
                     '<PlaceOfLoading>'+config.Place_of_Loading__c+'</PlaceOfLoading>'+
                           '<ImporterOfRecord>'+customerXML+'</ImporterOfRecord>'+
                           '<ShipmentConsignee>'+customerXML+'</ShipmentConsignee>'+
                           '<PartiesRelated />'+
                           '<ShipmentInvoiceNumber>'+release.Name+'</ShipmentInvoiceNumber>'+
                           '<ShipmentInvoiceDate>'+ComplianceUtility.formatDate(Date.today())+'</ShipmentInvoiceDate>'+
                           '<ShipmentPONumber>'+ComplianceUtility.getStringValue(salesOrder.inscor__Customer_PO_Number__c)+'</ShipmentPONumber>'+
                           '<ShipmentPODate>'+ComplianceUtility.formatDate(salesOrder.createdDate)+'</ShipmentPODate>'+
                           '<ShipmentCurrency>'+ config.ShipmentCurrency__c +'</ShipmentCurrency>'+
                           '<TermsofSale>'+
                              '<TermsofSaleCode>'+termsofSaleCode+'</TermsofSaleCode>'+
                              '<TermsofSaleDesc>'+ComplianceUtility.getStringValue(release.inscor__Account_Terms__r.Name)+'</TermsofSaleDesc>'+
                           '</TermsofSale>'+
                           '<IncoTerms>'+ComplianceUtility.getStringValue(release.inscor__Incoterms__c)+'</IncoTerms>'+
                           '<FreightCharges>'+
                              '<FreightChargesFor>'+ config.FreightChargesFor__c +'</FreightChargesFor>'+
                              '<FreightPrepaidCollect>'+ config.FreightPrepaidCollect__c +'</FreightPrepaidCollect>'+
                           '</FreightCharges>'+
                      '<Conveyance>'+ComplianceUtility.getStringValue( ComplianceUtility.removeTrademarkSpecialChar( release.inscor__Ship_Method__r.Name ) )+'</Conveyance>'+
                           '<ShipmentDetails>';
                                    Integer counter = 1;
                                    for( inscor__Release_Line__c reLI: release.inscor__Release_Lines__r ){
                                            requestXML += '<DetailLine>'+
                                                '<LineNumber>'+counter+'</LineNumber>'+
                                                '<PartNo>'+ComplianceUtility.getStringValue(reLI.inscor__Sales_Order_Line__r.inscor__Product__r.Name)+'</PartNo>'+
                                                '<ShortDescription>'+ComplianceUtility.getStringValue(reLI.inscor__Sales_Order_Line__r.inscor__Keyword__c)+'</ShortDescription>'+
                                                '<LineQuantity>'+ComplianceUtility.getDecimalValue(reLI.inscor__Quantity__c)+'</LineQuantity>'+
                                                '<LineQuantityUnit>'+ config.LineQuantityUnit__c +'</LineQuantityUnit>'+
                                                '<LineUnitCost>'+ComplianceUtility.getDecimalValue(reLI.inscor__Sales_Order_Line__r.inscor__Price__c)+'</LineUnitCost>'+
                                                '<LineCurrency>'+config.Shipment_Line_Unit_Price_Currency__c+'</LineCurrency>'+
                                                '<LineValue>'+ComplianceUtility.getDecimalValue(reLI.inscor__Line_Value__c)+'</LineValue>'+
                                                '<LineIsHazmat>'+reLI.inscor__Sales_Order_Line__r.inscor__Product__r.inscor__HazMat__c+'</LineIsHazmat>'+
                                                '<HazmatUNNo>'+ComplianceUtility.getStringValue(reLI.inscor__Sales_Order_Line__r.inscor__Product__r.inscor__HazMat_Id__c)+'</HazmatUNNo>'+
                                                '<DFMCode>'+config.DFM_Code__c+'</DFMCode>'+
                                                '<CountryOriginCode>'+ComplianceUtility.getStringValue(reLI.inscor__Sales_Order_Line__r.inscor__Product__r.inscor__Country_of_Origin__c)+'</CountryOriginCode>'+
                                                '<HSCode>'+ComplianceUtility.getStringValue( ComplianceUtility.removeDotSpecialChar(reLI.inscor__Sales_Order_Line__r.inscor__Product__r.inscor__HTS_Code__c) )+'</HSCode>'+
                                                '<ECCN>'+ComplianceUtility.getStringValue(reLI.inscor__Sales_Order_Line__r.inscor__Product__r.inscor__ECCN__r.Name)+'</ECCN>'+
                                                '<LongDescription>'+ComplianceUtility.getStringValue(reLI.inscor__Sales_Order_Line__r.inscor__Product__r.Description)+'</LongDescription>'+
                                                '<HSQty1>'+ComplianceUtility.getDecimalValue(reLI.inscor__Quantity__c)+'</HSQty1>'+
                                                '<HSUnit1>'+config.LineQuantityUnit__c+'</HSUnit1>'+
                                                '</DetailLine>';
                                            counter++;
                                    }
                              
            requestXML+= '</ShipmentDetails>'+
                        '</Shipment>';
        requestXML += ']]>';
        return requestXML;
        
    }
    
    public static String createRequestXMLToSendItem(Product2 productObj){
        
        String requestXML = '<![CDATA[';
        
        requestXML += '<?xml version="1.0" encoding="utf-8"?>'+
                            '<Items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://edm.visualcompliance.com/edwinimport/xml/VD-EDM%20Item%20V2.1.xsd">'+
                                '<Item>'+
                                    '<PartNumber>'+ComplianceUtility.getStringValue(productObj.Name)+'</PartNumber>'+
                                    '<ClientReferenceNumber>'+ComplianceUtility.getStringValue(productObj.Name)+'</ClientReferenceNumber>'+
                                    '<ShortDescription>'+ComplianceUtility.getStringValue(productObj.inscor__Keyword__c)+'</ShortDescription>'+
                                    '<LongDescription>'+ComplianceUtility.getStringValue(productObj.inscor__Description__c)+'</LongDescription>'+
                                    '<OriginCountry>'+ComplianceUtility.getStringValue(CountryStateUtility.getCountryCode(productObj.inscor__Country_of_Origin__c))+'</OriginCountry>'+
                                    '<IsHazmat>'+productObj.inscor__HazMat__c+'</IsHazmat>'+
                                    '<HazmatID>'+ComplianceUtility.getStringValue(productObj.inscor__HazMat_Id__c)+'</HazmatID>'+
                                    '<isInactive>'+!productObj.IsActive+'</isInactive>'+
                                '</Item>'+
                            '</Items>';
        requestXML += ']]>';
        return requestXML;
    }
    
    
    
    //This method will return XML String for Contact.
    //Added 02June2021 
     public static String createRequestXMLToContactWithAccount(Contact con, Account customer) {
        
         String shippingCountry = ComplianceUtility.getStringValue(customer.ShippingCountry);
        
         shippingCountry = CountryStateUtility.getCountryCode(shippingCountry);
         
        String customerXML = '<TPID>'+customer.Id+'</TPID>'+
                              '<TPName>'+ComplianceUtility.getStringValue(customer.Name)+'</TPName>'+
                              '<TPAddress>'+ComplianceUtility.getStringValue(customer.ShippingStreet)+'</TPAddress>'+
                              '<TPCity>'+ComplianceUtility.getStringValue(customer.ShippingCity)+'</TPCity>'+
                              '<TPZipPostCode>'+ComplianceUtility.getStringValue(customer.ShippingPostalCode)+'</TPZipPostCode>'+
                              '<TPState>'+ComplianceUtility.getStringValue(customer.ShippingState)+'</TPState>'+
                              '<TPCountry>'+shippingCountry+'</TPCountry>'+
                              '<TPTelephone>'+ComplianceUtility.formatAccountContactPhone(customer.Phone)+'</TPTelephone>';
                                
        
         String contactXML = '<ContactType>'+'PRIMARY'+'</ContactType>'+
                            '<ContactName>'+ComplianceUtility.getStringValue(con.Name)+'</ContactName>'+
                             '<ContactTitle>'+ComplianceUtility.getStringValue(con.Title)+'</ContactTitle>'+
                             '<ContactPhone>'+ComplianceUtility.formatAccountContactPhone(con.Phone)+'</ContactPhone>'+
                             '<ContactEmail>'+ComplianceUtility.getStringValue(con.Email)+'</ContactEmail>';
           
        
        String requestXML = '<![CDATA[';
        
        requestXML += '<?xml version="1.0" encoding="UTF-8"?>'+
                       '<TradePartners xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://edm.visualcompliance.com/edwinimport/xml/VD-EDM%20TradePartner%20V2.1.xsd">'+
                           '<TradePartner>'+customerXML+
                           '<Contacts>'+
                            '<ContactDetail>'+ contactXML+'</ContactDetail>'+
                           '</Contacts>';
            requestXML+= '</TradePartner>'+
                        '</TradePartners>';
        requestXML += ']]>';
        return requestXML;
        
    }
}