src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DNBI__DnB_DUNS_NO__c</fullName>
        <label>D&amp;B DUNS Number</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DNBI__DnB_Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>YayPay_Error_Message__c</fullName>
        <label>YayPay Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>YayPay_Last_Sync_Date__c</fullName>
        <label>YayPay Last Sync Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>inscor__Account_Region__c</fullName>
        <label>Account Region</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Account_Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Account_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Terms</label>
        <referenceTo>inscor__Account_Terms__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Credit_Limit__c</fullName>
        <label>Credit Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AcctSeed__Billing__c.object
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <fields>
        <fullName>AcctSeed__Billing_Comment__c</fullName>
        <inlineHelpText>A comment which is included on the pdf invoice generated for the customer.</inlineHelpText>
        <label>Billing Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Credit_Memo_Applied_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Indicates the amount applied from a single or multiple credit memos.</inlineHelpText>
        <label>Credit Memo Applied Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The organization you would like to pay you for your product or service.</inlineHelpText>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Type__c</field>
                <operation>contains</operation>
                <value>Customer, Customer and Vendor</value>
            </filterItems>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>Date the Billing is issued to the customer.</inlineHelpText>
        <label>Billing Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Received_Amount__c</fullName>
        <inlineHelpText>Indicates the amount of cash applied from a single or multiple cash receipts.</inlineHelpText>
        <label>Received Amount</label>
        <summarizedField>AcctSeed__Billing_Cash_Receipt__c.AcctSeed__Applied_Amount__c</summarizedField>
        <summaryForeignKey>AcctSeed__Billing_Cash_Receipt__c.AcctSeed__Billing__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>Used in approvals and invoices that are in process of being finalized. A posted status indicates the invoice is final and no further changes are to be made.</inlineHelpText>
        <label>Posting Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Waiting for Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <default>true</default>
                    <label>Approved</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AcctSeed__Total__c</fullName>
        <inlineHelpText>Grand Total for Billing.</inlineHelpText>
        <label>Total</label>
        <summarizedField>AcctSeed__Billing_Line__c.AcctSeed__Total__c</summarizedField>
        <summaryForeignKey>AcctSeed__Billing_Line__c.AcctSeed__Billing__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <formula>IF(AcctSeed__Total__c &lt; 0, &apos;Credit Memo&apos;,&apos;Invoice&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>A billing can either be an Invoice or Credit memo. An invoice represents money due to your organization. A credit memo represents forgiveness of an Invoice.</inlineHelpText>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Internal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>YayPay_Error_Message__c</fullName>
        <label>YayPay Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>YayPay_Last_Sync_Date__c</fullName>
        <label>YayPay Last Sync Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>inscoras__Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>inscor__Invoice__c</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AcctSeed__Billing_Credit_Memo__c.object
<CustomObject>
    <description>Used to document the relationship a billing credit memo record and a billing invoice record. A billing credit memo record is created during the apply credit memo process.</description>
    <fields>
        <fullName>AcctSeed__Amount__c</fullName>
        <label>Applied Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Applied_Date__c</fullName>
        <inlineHelpText>Used to specify the applied date for financial reporting.</inlineHelpText>
        <label>Applied Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Billing_Credit_Memo__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Credit Memo</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The type field of the billing must be &quot;Credit Memo&quot;</errorMessage>
            <filterItems>
                <field>AcctSeed__Billing__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Credit Memo</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Billing__c</referenceTo>
        <relationshipLabel>Applied Invoices to Credit Memo</relationshipLabel>
        <relationshipName>Billing_Credit_Memos</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Billing_Invoice__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Invoice</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The type field of the billing must be &quot;Invoice&quot;</errorMessage>
            <filterItems>
                <field>AcctSeed__Billing__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Invoice</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Billing__c</referenceTo>
        <relationshipLabel>Applied Credit Memos to Invoice</relationshipLabel>
        <relationshipName>Billing_Credit_Memos1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Billing Credit Memo</label>
    <nameField>
        <displayFormat>BCM-{00000}</displayFormat>
        <label>Billing Credit Memo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Credit Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Is_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>YayPay_Last_Sync_Date__c</fullName>
        <label>YayPay Last Sync Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Is_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>YayPay_Error_Message__c</fullName>
        <label>YayPay Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>YayPay_Last_Sync_Date__c</fullName>
        <label>YayPay Last Sync Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>inscor__Account_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Terms</label>
        <referenceTo>inscor__Account_Terms__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Billing Contact)</relationshipLabel>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INVC-{0}</displayFormat>
        <label>Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Price__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Account_Region__c</fullName>
        <label>Account Region</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Account_Region</valueSetName>
        </valueSet>
    </fields>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Price Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchProcessBillingToYayPay.cls
global class BatchProcessBillingToYayPay implements Database.Batchable<sObject>,Database.AllowsCallouts,Database.Stateful, Schedulable {
    
    Public Set<Id> billingIds;
    Public DateTime tokenGenerateTime;
    Public DateTime tokenExpiaryTime;
    Public String accessToken;
    Public Integer tokenGenerateCount =0 ;
    Public String transactionId;
    Public List<AcctSeed__Billing__c> billingsToUpdate;
    
    global BatchProcessBillingToYayPay(){
        billingIds = new Set<Id>();
        billingsToUpdate = new list<AcctSeed__Billing__c>();
    }
    global BatchProcessBillingToYayPay(Set<Id> Ids){
        billingIds = Ids;
        billingsToUpdate = new list<AcctSeed__Billing__c>();
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = ' SELECT Id, Name, AcctSeed__Customer__c, IsDeleted, Internal__c, YayPay_Last_Sync_Date__c, '+
                        ' AcctSeed__Date__c, AcctSeed__Total__c, AcctSeed__Credit_Memo_Applied_Amount__c, ' +
                        ' ( SELECT Id, Name, AcctSeed__Amount__c, AcctSeed__Applied_Date__c, ' +
                        ' AcctSeed__Billing_Credit_Memo__c, AcctSeed__Billing_Invoice__c, '+
                        ' AcctSeed__Billing_Invoice__r.inscoras__Invoice__c, ' +
                        ' AcctSeed__Billing_Invoice__r.inscoras__Invoice__r.Yaypay_Last_Sync_date__c, ' +
                        ' AcctSeed__Billing_Invoice__r.AcctSeed__Received_Amount__c, ' +
            			' AcctSeed__Billing_Invoice__r.AcctSeed__Billing_Comment__c ' +
                        ' FROM AcctSeed__Billing_Credit_Memos__r ) '+
                        ' FROM  AcctSeed__Billing__c '+
                        ' WHERE Id != null';
        
        if(billingIds.size() > 0){
            query += ' AND Id IN: billingIds';
        }else{
            query += ' AND Is_Processed__c = FALSE '
           		  + ' AND AcctSeed__Total__c != 0 AND AcctSeed__Customer__c != null AND AcctSeed__Status__c = \'Posted\' ' +
                  +	' AND AcctSeed__Type__c = \'Credit Memo\' ';
                  //+ ' AND Internal__c = FALSE ';
        }
        query += '  ORDER By Is_Error__c ASC,LastModifiedDate DESC LIMIT 10';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<AcctSeed__Billing__c> billings ){
        
        List<YayPay_Other_Charges_Configuration__mdt> YayPayOtherCharges = [ SELECT Id, DeveloperName, MasterLabel 
                                                                            FROM YayPay_Other_Charges_Configuration__mdt ];
        Map<String, YayPay_Other_Charges_Configuration__mdt> mapYayPayOtherCharges = new Map<String, YayPay_Other_Charges_Configuration__mdt>();
        
        for( YayPay_Other_Charges_Configuration__mdt meta : YayPayOtherCharges ){
            mapYayPayOtherCharges.put( meta.MasterLabel, meta );
        }
        if( !YayPayUtility.sendYayPayCallout() ){
            return;
        }
        if( billings.size() > 0 ){
            AcctSeed__Billing__c billObj = billings.get(0);
            if( TokenExpiaryTime == null || TokenExpiaryTime < System.now() ){
                        //get Access Token for Request API.
                        accessToken = YayPayAuthentication.getAccessToken(); 
                        TokenExpiaryTime = System.now().addMinutes(50);
                        //starting transaction.
                        transactionId = YayPayTransactionAPIService.startTransaction( accessToken );
                    }
            if( billObj.Internal__c && billObj.YayPay_Last_Sync_Date__c != null ){
                YayPayAPIService.deleteRecordsFromYayPay( New List<String>{ billObj.Id }, 'payments', accessToken, transactionId );
                billObj.YayPay_Last_Sync_Date__c = System.now();
                billObj.Is_Processed__c = TRUE;
                billingsToUpdate.add( billObj );
            }else if( !billObj.Internal__c ){
                try{      
                    
                    set<String> invoiceNumbers = new set<String>();
                    Boolean notHasInvoiceAndSynced = false;
                    for( AcctSeed__Billing_Credit_Memo__c cm : billObj.AcctSeed__Billing_Credit_Memos__r ){
                     
                        notHasInvoiceAndSynced = cm.AcctSeed__Billing_Invoice__r.inscoras__Invoice__r.Yaypay_Last_Sync_date__c == null ? TRUE : FALSE;
                        if( notHasInvoiceAndSynced ){
                            if( !mapYayPayOtherCharges.containsKey( cm.AcctSeed__Billing_Invoice__r.AcctSeed__Billing_Comment__c ) ){
                                billObj.Is_Error__c = TRUE;
                                billObj.YayPay_Error_Message__c = 'invoice on related billing not found';
                                billingsToUpdate.add( billObj );
                                return;
                            }
                        }
                        if( cm.AcctSeed__Billing_Invoice__c != null ){
                            invoiceNumbers.add( cm.AcctSeed__Billing_Invoice__r.inscoras__Invoice__c );
                        }
                    }
                    
                    String errorString;
                    
                    if( String.isBlank(errorString) ){                    
                        
                        set<String> customerIds = new set<String>();
                        
                        list<AcctSeed__Billing__c> billingList = new list<AcctSeed__Billing__c>(); 
                        billingList.add( billObj );
                        
                        for( AcctSeed__Billing__c bill : billingList ){
                            customerIds.add( bill.AcctSeed__Customer__c );
                        }                    
                        
                        list<Account> accountList = [ SELECT Id, Name, Site, ShippingCity, ShippingState, ParentId,
                                                     inscor__Billing_Contact__r.Email, inscor__Account_Terms__r.Name,
                                                     DNBI__DnB_DUNS_NO__c, inscor__Credit_Limit__c, inscor__Account_Region__c,
                                                     DNBI__DnB_Payment_Terms__c, AcctSeed__Taxpayer_Identification_Number__c,
                                                     ShippingPostalCode, ShippingStreet, ShippingCountry,Phone, Website
                                                     FROM Account WHERE Id IN :customerIds ];
                        
                        //Process Customer.
                        Integer responseCodeCustomer = YayPayAPIService.sendCustomerToYayPay( accountList, accessToken, transactionId );
                        
                        //Process Billing.
                        Integer responseCodeBilling;
                        if( billingList.size() > 0 ){
                            responseCodeBilling = YayPayAPIService.sendBillingToYayPay( billingList, accessToken, transactionId );
                        }     
                        
                        billObj.YayPay_Last_Sync_Date__c = System.now();
                        billObj.Is_Processed__c = TRUE;
                    }
                    else{
                        billObj.YayPay_Error_Message__c = errorString;
                        billObj.Is_Processed__c = TRUE;
                    }
                    billingsToUpdate.add( billObj );
                    
                    
                    String invoiceQuery = ' SELECT Id, Name, inscor__Account__c, inscor__Billing_Contact__c, inscor__Customer_PO_Number__c,'+
                        'inscor__Billing_Contact__r.Email, inscor__Account__r.Id, inscor__Invoice_Date__c, '+
                        ' inscor__Billing_Contact__r.Id, inscor__Status__c, inscor__Total_Invoice__c, '+
                        ' ( SELECT Id, Name, inscor__Quantity__c, inscor__Price__c, inscor__Item__r.inscor__Description__c,'+
                        '  inscor__Item__r.Name, inscor__Extended_Price__c FROM inscor__Invoice_Lines__r ), '+
                        ' ( SELECT Id, Name, inscor__Receivable_Amount__c, inscor__External_Reference_ID__c, '+
                        ' inscor__INVC_Date__c, inscor__Line_Value__c, inscor__INVC__r.Id, inscor__Customer_Vendor__r.Id'+
                        '  FROM inscor__Transaction_Activities__r ) '+
                        ' FROM  inscor__Invoice__c '+
                        ' WHERE Id IN :invoiceNumbers';
                    list<inscor__Invoice__c> relatedInvoices = Database.query(invoiceQuery);
                    
                    List<inscor__Invoice__c> invoicesToUpdate = new List<inscor__Invoice__c>();
                    for( inscor__Invoice__c invObj : relatedInvoices ){
                        try{
                            String errorStringInvoice = BatchProcessInvoiceToYayPay.validateInvoiceRequest( invObj );
                            if( String.isBlank(errorString) ){
                                Integer responseCodeInvoice = YayPayAPIService.sendInvoiceToYayPay( invObj, accessToken, transactionId );
                                invObj.YayPay_Last_Sync_Date__c = System.now();
                                invObj.Is_Processed__c = TRUE;
                            }else{
                                invObj.YayPay_Error_Message__c = errorStringInvoice;
                                invObj.Is_Processed__c = TRUE;
                            }
                            invoicesToUpdate.add( invObj );
                        }catch( exception e ){
                            invObj.Is_Processed__c = TRUE;
                            if( ! invoicesToUpdate.contains( invObj ) ){
                                invoicesToUpdate.add( invObj  );
                            }
                        }
                        
                    }
                    update invoicesToUpdate;
                }
                catch( exception error ){
                    billObj.Is_Processed__c = TRUE;
                    if( ! billingsToUpdate.contains( billObj ) ){
                        billingsToUpdate.add( billObj  );
                    }
                    LogService.createErrorLog('BatchProcessBillingToYayPay.execute', NULL, error, NULL);
 }
            }
        }            
    }
    
    global void execute(SchedulableContext sc) {
        Database.executeBatch(new BatchProcessBillingToYayPay(), 1 );
    }
    
    global void finish(Database.BatchableContext bc){
        try{
            //Finish transaction.
            Integer transactionFinishCode = YayPayTransactionAPIService.finishTransaction( accessToken, transactionId ); 
            update billingsToUpdate;
        }catch( exception error ){
            LogService.createErrorLog('BatchProcessBillingToYayPay.finish', NULL, error, NULL);
        }
    }
}