src/objects/AcctSeed__Billing__c.object
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <fields>
        <fullName>AcctSeed__Billing_Country__c</fullName>
        <label>Billing Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Billing_State__c</fullName>
        <label>Billing State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Shipping_Country__c</fullName>
        <label>Shipping Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Shipping_State__c</fullName>
        <label>Shipping State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country_Codes__mdt.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Country Code</label>
    <pluralLabel>Country Codes</pluralLabel>
</CustomObject>

src/objects/State_Code__mdt.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <referenceTo>Country_Codes__mdt</referenceTo>
        <relationshipLabel>State Codes</relationshipLabel>
        <relationshipName>State_Codes</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>State Code</label>
    <pluralLabel>State Codes</pluralLabel>
</CustomObject>

src/objects/Trigger_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Trigger Configuration will be used for maintaining trigger toggle for its execution.</description>
    <fields>
        <fullName>Billing_Trigger_Disabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing Trigger Disabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Configuration</label>
</CustomObject>

src/classes/BillingsTriggerHelper.cls
/**************************************************************************************************
Description: Trigger Helper class for AcctSeed__Billing__c that will handle all types of trigger events.
====================================================================================================
====================================================================================================
TestClass: BillingsTriggerHelperTest
Code Coverage: 92%
====================================================================================================
====================================================================================================
History
<Version>   	<Date>             <Author Name>                <Brief description of change > 
1.0 -      		09/03/2021		    Kushal Bagadia				Initial Creation    
***************************************************************************************************/
public class BillingsTriggerHelper implements TriggerHandler {
    
    /*Allows unit tests (or other code) to disable this trigger for the transaction */
    
    public static Boolean TriggerDisabled = false;
        
        /*Checks to see if the trigger has been disabled either by custom setting or by running code*/
        
        public Boolean IsDisabled() {
            /*Use the option below if you set up Custom Settings to controll Triggers*/
            Trigger_Configuration__c configSetting = Trigger_Configuration__c.getInstance();   
            if(configSetting.Billing_Trigger_Disabled__c == true) {
                return true;
            } else {
                return TriggerDisabled;
            }
        }
    
    /* CALLING */
    public void BeforeInsert(SObject[] newList) {
        BillingsTriggerHelper.updateCountryAndState((List<AcctSeed__Billing__c>)newList);
    }
    
    public void BeforeUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
        BillingsTriggerHelper.updateCountryAndState((List<AcctSeed__Billing__c>)newMap.values());
    }
    
    public void BeforeDelete(Map<Id, SObject> oldMap) {}
    
    public void AfterInsert(Map<Id, SObject> newMap) {
    }
    
    public void AfterUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {  
    }
    
    public void AfterDelete(Map<Id, SObject> oldMap) {  }
    
    public void AfterUndelete(Map<Id, SObject> oldMap) {}
    
    public static void updateCountryAndState(List<AcctSeed__Billing__c> newList){
        for(AcctSeed__Billing__c billing : newList){
            if(billing.AcctSeed__Billing_Country__c != null && Country_Codes__mdt.getInstance(billing.AcctSeed__Billing_Country__c.replaceAll(' ', '_')) != null){
                billing.AcctSeed__Billing_Country__c = Country_Codes__mdt.getInstance(billing.AcctSeed__Billing_Country__c.replaceAll(' ', '_')).Country_Code__c;
            }
            if(billing.AcctSeed__Shipping_Country__c != null && Country_Codes__mdt.getInstance(billing.AcctSeed__Shipping_Country__c.replaceAll(' ', '_')) != null){
                billing.AcctSeed__Shipping_Country__c = Country_Codes__mdt.getInstance(billing.AcctSeed__Shipping_Country__c.replaceAll(' ', '_')).Country_Code__c;
            }
            if(billing.AcctSeed__Billing_Country__c == 'US' && billing.AcctSeed__Billing_State__c != null && State_Code__mdt.getInstance(billing.AcctSeed__Billing_State__c.replaceAll(' ', '_')) != null){
                billing.AcctSeed__Billing_State__c = State_Code__mdt.getInstance(billing.AcctSeed__Billing_State__c.replaceAll(' ', '_')).State_Code__c;
            }
            if(billing.AcctSeed__Shipping_Country__c == 'US' && billing.AcctSeed__Shipping_State__c != null && State_Code__mdt.getInstance(billing.AcctSeed__Shipping_State__c.replaceAll(' ', '_')) != null){
                billing.AcctSeed__Shipping_State__c = State_Code__mdt.getInstance(billing.AcctSeed__Shipping_State__c.replaceAll(' ', '_')).State_Code__c;
            }
        }
    }
}