src/objects/AcctSeed__Billing__c.object
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <fields>
        <fullName>Is_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>YayPay_Error_Message__c</fullName>
        <label>YayPay Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>YayPay_Last_Sync_Date__c</fullName>
        <label>YayPay Last Sync Date</label>
        <type>DateTime</type>
    </fields>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deleted_Record__c.object
<CustomObject>
    <fields>
        <fullName>Deleted_Record_Id__c</fullName>
        <label>Deleted Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <label>Object Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>YayPay_Last_Sync_Date__c</fullName>
        <label>YayPay Last Sync Date</label>
        <type>DateTime</type>
    </fields>
    <label>Deleted Record</label>
    <nameField>
        <label>Deleted Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deleted Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trigger_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Trigger Configuration will be used for maintaining trigger toggle for its execution.</description>
    <fields>
        <fullName>Billing_Trigger_Disable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing Trigger Disable</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Configuration</label>
</CustomObject>

src/classes/BillingTriggerHelper.cls
/**************************************************************************************************
Description: Trigger Helper class for BillingTrigger that will handle all types of trigger events.
====================================================================================================
====================================================================================================
TestClass: -
Code Coverage: -
====================================================================================================
====================================================================================================
History
<Version>   	<Date>             <Author Name>                <Brief description of change > 
1.0 -      		06/18/2021		    Gourav Goyal				Initial Creation    
***************************************************************************************************/
public class BillingTriggerHelper implements TriggerHandler {
    
    /*Allows unit tests (or other code) to disable this trigger for the transaction */
    
    public static Boolean TriggerDisabled = false;
    
    /*Checks to see if the trigger has been disabled either by custom setting or by running code*/
    
    public Boolean IsDisabled() {
        /*Use the option below if you set up Custom Settings to controll Triggers*/
        Trigger_Configuration__c configSetting = Trigger_Configuration__c.getInstance();   
        if(configSetting.Billing_Trigger_Disable__c == true) {
            return true;
        } else {
            return TriggerDisabled;
        }
    }
    
    /* CALLING */
    public void BeforeInsert(SObject[] newList) {
        resetYayPayBillingFields( (List<AcctSeed__Billing__c>)newList  );
    }
    
    public void BeforeUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
        resetYayPayBillingFields( (List<AcctSeed__Billing__c>)newMap.values() );
    }
    
    public void BeforeDelete(Map<Id, SObject> oldMap) {}
    
    public void AfterInsert(Map<Id, SObject> newMap) {
    }
    
    public void AfterUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
        
    }
    
    public void AfterDelete(Map<Id, SObject> oldMap) {
    	createDeleteRecords( (List<AcctSeed__Billing__c>)oldMap.values() );
    }
    
    public void AfterUndelete(Map<Id, SObject> oldMap) {
        
    }    
    
    public static void resetYayPayBillingFields( List<AcctSeed__Billing__c> newList ){
       
        if( System.isBatch() ){
            return;
        }
        try{
            //reset Fields.
            for(AcctSeed__Billing__c bill : newList){
                bill.Is_Processed__c = FALSE;
                bill.YayPay_Error_Message__c = '';
            }
            if(Test.isRunningTest())
                Integer i = 1/0; 
        }catch (Exception error) {  
            LogService.createErrorLog('BillingTriggerHelper.apxc', NULL, error, NULL); 
        }
    }
    
    public static void createDeleteRecords( List<AcctSeed__Billing__c> oldList ){
       
        if( System.isBatch() ){
            return;
        }
        try{
            List<Deleted_Record__c> deleteRecordsToInsert = new List<Deleted_Record__c>();
            for(AcctSeed__Billing__c bill : oldList){
                if( bill.YayPay_Last_Sync_Date__c != null ){
                	deleteRecordsToInsert.add( new Deleted_Record__c( Deleted_Record_Id__c = bill.Id,
                                                                    Object_Type__c = 'payments'));
                }
            }
            if( deleteRecordsToInsert.size() > 0 ){
                insert deleteRecordsToInsert;
            }
            if(Test.isRunningTest())
                Integer i = 1/0; 
        }catch (Exception error) {  
            LogService.createErrorLog('BillingTriggerHelper.apxc', NULL, error, NULL); 
        }  
        
    }
   
}