src/objects/Compliance_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>EndPoint__c</fullName>
        <label>EndPoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Integration_Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Integration Enable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Shipment_Status_Action__c</fullName>
        <label>Shipment Status Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Upload_File_Action__c</fullName>
        <label>Upload File Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Compliance Configuration</label>
</CustomObject>

src/objects/inscor__Alternate__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Alternate_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Alternate Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Alternates</relationshipLabel>
        <relationshipName>Alternates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>inscor__Company__c</referenceTo>
        <relationshipLabel>Alternates</relationshipLabel>
        <relationshipName>Alternates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Relationship_New__c</fullName>
        <description>Relationship New Field</description>
        <label>Relationship</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Relationship</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Relationship_Other_Side__c</fullName>
        <label>Relationship For Other Side</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Relationship</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Show_both_sides_in_Part_Research__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>If checked, an additional record will be created with the Primary and Alternate Part Number reversed.</inlineHelpText>
        <label>Create Records for Both Sides?</label>
        <type>Checkbox</type>
    </fields>
    <label>Alternate</label>
    <nameField>
        <displayFormat>AID-{0}</displayFormat>
        <label>Alternate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alternates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Company__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Address_1__c</fullName>
        <label>Address 1</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Company_Name__c</fullName>
        <label>Company Name</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>inscor__Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Company</label>
    <nameField>
        <displayFormat>CID-{0}</displayFormat>
        <label>Company ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Compliance_Response__c</fullName>
        <label>Compliance Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <label>Keyword</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductTriggerHelperTest.cls
@isTest
private class ProductTriggerHelperTest {
	
    @testSetup()
    private static void setup(){

        Compliance_Configuration__c complianceConfigSetting = Compliance_Configuration__c.getOrgDefaults();   
        complianceConfigSetting.EndPoint__c = 'https://text-azservices.ecustoms.com/edwinimport/EdwinImportPortal.asmx';
        complianceConfigSetting.Shipment_Status_Action__c = 'http://test-tempuri.org/GetShipmentStatus';
        complianceConfigSetting.Upload_File_Action__c = 'http://test-tempuri.org/Uploadfile';
        complianceConfigSetting.Is_Integration_Enable__c = true;
        upsert complianceConfigSetting;
        
    }    
    
    @isTest
    static void batchWithParamTest() {
        Product2 prod = new Product2(Name = 'Laptop X200', 
                                     Family = 'Hardware', inscor__Keyword__c ='test');
        
        
        Test.setMock(HttpCalloutMock.class, new ComplianceMockResponseGenerator());
        Test.startTest();
        insert prod;
        Test.stopTest();
        list<Product2> productList = [SELECT Id, Compliance_Response__c from Product2 where Id =: prod.Id];
        system.assertNotEquals(null, productList[0].Compliance_Response__c);
    } 
    
    
    @isTest
    static void batchWithoutParamTest() {
        Product2 prod = new Product2(Name = 'Test Product 2', 
                                     Family = 'Hardware', inscor__Keyword__c ='test');
        
        
        Test.setMock(HttpCalloutMock.class, new ComplianceMockResponseGenerator());
        Test.startTest();
        insert prod;
        Test.stopTest();
        list<Product2> productList = [SELECT Id, Compliance_Response__c from Product2 where Id =: prod.Id];
        system.assertNotEquals(null, productList[0].Compliance_Response__c);
    }

    @IsTest
    static void testConditionCodes(){
        
        Test.startTest();
        Product2 prod = new Product2(Name = 'Laptop X200', 
                                     Family = 'Hardware', inscor__Keyword__c ='test', NE__c = true);
        insert prod;
        String prodId = prod.Id;

        inscor__Company__c  company = new inscor__Company__c(
            inscor__Address_1__c = '1111', inscor__City__c = '1111', inscor__Company_Name__c = '1111', inscor__Zip_Code__c = '1111');
        insert company;

        inscor__Alternate__c alternate = new inscor__Alternate__c();
        alternate.inscor__Alternate_Product__c = prod.id;
        alternate.inscor__Company__c = company.Id;
        alternate.inscor__Relationship_New__c = 'Superseded By';
        alternate.inscor__Relationship_Other_Side__c = 'Superseded By';
        alternate.inscor__Show_both_sides_in_Part_Research__c = true;
        insert alternate;
        prod.OH__c = true;
        update prod;
        List<Condition_Code__c> conditionCodes = [SELECT Id FROM Condition_Code__c WHERE Part_Master__c = :prod.Id];
        //delete prod; //all condition codes related to it should also deleted
        //ProductTriggerHelper.deleteCondtionCodeOnDelete(new Set<Id>{prod.Id});

        conditionCodes = [SELECT Id FROM Condition_Code__c WHERE Part_Master__c = :prodId];
        Test.stopTest();
        
    }
}