src/objects/Customer_Exchange_Summary_Form_Response__c.object
<CustomObject>
    <description>This will be a Child object of Customer Exchange Summary which will store the responses from Customer.</description>
    <fields>
        <fullName>AC_CSN__c</fullName>
        <description>AC CSN</description>
        <inlineHelpText>AC CSN</inlineHelpText>
        <label>AC CSN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AC_TSN__c</fullName>
        <description>AC TSN</description>
        <inlineHelpText>AC TSN</inlineHelpText>
        <label>AC TSN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AWB__c</fullName>
        <description>AWB</description>
        <inlineHelpText>AWB</inlineHelpText>
        <label>AWB</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Aircraft_Model__c</fullName>
        <description>Aircraft Model - will store Aircraft Model</description>
        <inlineHelpText>Aircraft Model</inlineHelpText>
        <label>Aircraft Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Aircraft_SN__c</fullName>
        <description>Aircraft SN</description>
        <inlineHelpText>Aircraft SN</inlineHelpText>
        <label>Aircraft SN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Address__c</fullName>
        <formula>IF(NOT(ISBLANK(Customer_Exchange_Summary__r.inscor__Original_SO_ID__r.inscor__Customer__r.BillingStreet)),      Customer_Exchange_Summary__r.inscor__Original_SO_ID__r.inscor__Customer__r.BillingStreet + &apos;, &apos;, &apos;&apos;) 
+ 
IF(NOT(ISBLANK(Customer_Exchange_Summary__r.inscor__Original_SO_ID__r.inscor__Customer__r.BillingCity)),        Customer_Exchange_Summary__r.inscor__Original_SO_ID__r.inscor__Customer__r.BillingCity + &apos;, &apos;,&apos;&apos;) 
+
IF(NOT(ISBLANK(Customer_Exchange_Summary__r.inscor__Original_SO_ID__r.inscor__Customer__r.BillingState)),       Customer_Exchange_Summary__r.inscor__Original_SO_ID__r.inscor__Customer__r.BillingState + &apos;, &apos;, &apos;&apos;) 
+
IF(NOT(ISBLANK(Customer_Exchange_Summary__r.inscor__Original_SO_ID__r.inscor__Customer__r.BillingPostalCode)),Customer_Exchange_Summary__r.inscor__Original_SO_ID__r.inscor__Customer__r.BillingPostalCode + &apos;, &apos;, &apos;&apos;) 
+
IF(NOT(ISBLANK(Customer_Exchange_Summary__r.inscor__Original_SO_ID__r.inscor__Customer__r.BillingCountry)),     Customer_Exchange_Summary__r.inscor__Original_SO_ID__r.inscor__Customer__r.BillingCountry, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSN_Value__c</fullName>
        <description>CSN Value</description>
        <inlineHelpText>CSN Value</inlineHelpText>
        <label>CSN Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSO_Value__c</fullName>
        <description>CSO Value</description>
        <inlineHelpText>CSO Value</inlineHelpText>
        <label>CSO Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSO__c</fullName>
        <description>CSO</description>
        <inlineHelpText>CSO</inlineHelpText>
        <label>CSO/CSN</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CSN</fullName>
                </value>
                <value>
                    <fullName>CSO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <description>Carrier</description>
        <inlineHelpText>Carrier</inlineHelpText>
        <label>Carrier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FedEx</fullName>
                </value>
                <value>
                    <fullName>UPS</fullName>
                </value>
                <value>
                    <fullName>DHL</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Exchange_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer Exchange Summary</description>
        <inlineHelpText>Customer Exchange Summary</inlineHelpText>
        <label>Customer Exchange Summary</label>
        <referenceTo>inscor__Customer_Exchange_Summary__c</referenceTo>
        <relationshipLabel>Customer Exchange Summary Form Responses</relationshipLabel>
        <relationshipName>Customer_From_Customer_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <description>Customer Name - Name of Customer</description>
        <inlineHelpText>Customer Name</inlineHelpText>
        <label>Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_PO_Number__c</fullName>
        <description>Customer PO Number - will store PO Number</description>
        <inlineHelpText>Customer PO Number</inlineHelpText>
        <label>Customer PO Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Part Number - will store Part Number</description>
        <inlineHelpText>Original Part Number</inlineHelpText>
        <label>PN</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Customer Exchange Summary Form Responses</relationshipLabel>
        <relationshipName>PN</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SN__c</fullName>
        <description>SN - will store SN.</description>
        <inlineHelpText>SN</inlineHelpText>
        <label>SN</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TSN_Value__c</fullName>
        <description>TSN Value</description>
        <inlineHelpText>TSN Value</inlineHelpText>
        <label>TSN Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TSO_Value__c</fullName>
        <description>TSO Value</description>
        <inlineHelpText>TSO Value</inlineHelpText>
        <label>TSO Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TSO__c</fullName>
        <description>TSO</description>
        <inlineHelpText>TSO</inlineHelpText>
        <label>TSO/TSN</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TSN</fullName>
                </value>
                <value>
                    <fullName>TSO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Exchange Summary Form Response</label>
    <nameField>
        <displayFormat>CFR-{000000000}</displayFormat>
        <label>Customer Exchange Summary Form Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Exchange Summary Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Condition_Code__c.object
<CustomObject>
    <label>Condition Code</label>
    <nameField>
        <label>Condition Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Exchange_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Customer_PO_Number__c</fullName>
        <description>Sales order Customer PO</description>
        <formula>inscor__Original_SO_ID__r.inscor__Customer_PO_Number__c</formula>
        <label>Customer PO Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Expected_Core_Serial_Number__c</fullName>
        <label>Expected Core Serial Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Original_SO_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original SO ID</label>
        <referenceTo>inscor__Sales_Order__c</referenceTo>
        <relationshipLabel>Customer Exchange Summaries</relationshipLabel>
        <relationshipName>Customer_Exchange_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Exchange Summary</label>
    <nameField>
        <displayFormat>EXS-{0}</displayFormat>
        <label>Customer Exchange Summary ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Exchange Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order__c.object
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Sales Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Condition_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Expected_Core_Serial_Number__c</fullName>
        <label>Expected Core Serial Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Order__c</fullName>
        <label>Order</label>
        <referenceTo>inscor__Sales_Order__c</referenceTo>
        <relationshipName>Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity_Ordered__c</fullName>
        <label>Quantity Ordered</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{0}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CoreExchangeFormResponsePDFCtrl.cls
global class CoreExchangeFormResponsePDFCtrl {
    
    public Customer_Exchange_Summary_Form_Response__c coreExchangeFormResponse{get; set;}
    public List<inscor__Sales_Order_Line__c> salesOrderLines{get; set;}
    public string ipAddress {get; set;}
    public String imageUrl{get;set;} 
    //public String carrier{get;set;}
    
    public CoreExchangeFormResponsePDFCtrl() {
        String coreExchangeFormResponseId = ApexPages.currentPage().getParameters().get('id');
        if(String.isNotBlank(coreExchangeFormResponseId)){
            this.coreExchangeFormResponse = getCoreExchangeFormResponseById(coreExchangeFormResponseId);
            //this.carrier = (String)this.coreExchangeFormResponse.Carrier__c;
            system.debug(JSON.serializePretty(this.coreExchangeFormResponse));
            
            setSalesOrderLines(this.coreExchangeFormResponse.Customer_Exchange_Summary__c);
            ipAddress = getIpAddress();
            //imageUrl = 'https://www.webarcode.com/barcode/image.php?code=' + this.coreExchangeFormResponse.Customer_Exchange_Summary__r.inscor__Original_SO_ID__r.Name + '&type=C128B&xres=1&height=100&width=300&font=3&output=png';
			imageUrl = 'https://mobiledemand-barcode.azurewebsites.net/barcode/image?content=' + this.coreExchangeFormResponse.Customer_Exchange_Summary__r.inscor__Original_SO_ID__r.Name + '&size=50&symbology=CODE_128&format=png&text=false';
        
        }
    }
    
    public Customer_Exchange_Summary_Form_Response__c getCoreExchangeFormResponseById(Id coreExchangeFormResponseId){
        Customer_Exchange_Summary_Form_Response__c coreExchangeFormResponse = [SELECT 
                                                                               Id,
                                                                               Customer_Exchange_Summary__c,
                                                                               Customer_Exchange_Summary__r.Customer_PO_Number__c,
                                                                               Customer_Exchange_Summary__r.inscor__Original_SO_ID__r.Name,
                                                                               Customer_Name__c,
                                                                               Billing_Address__c,
                                                                               Aircraft_Model__c,
                                                                               Aircraft_SN__c,
                                                                               Carrier__c,
                                                                               AC_CSN__c,
                                                                               AWB__c,
                                                                               AC_TSN__c,
                                                                               SN__c,
                                                                               PN__c,
                                                                               TSO__c,
                                                                               Cso__c,
                                                                               TSO_Value__c, TSN_Value__c, CSO_Value__c, CSN_Value__c
                                                                               FROM Customer_Exchange_Summary_Form_Response__c 
                                                                               WHERE Id = :coreExchangeFormResponseId];
        return coreExchangeFormResponse;
    }
    
    /**
     * @author : Vinod Kumar Sharma
     * @date : 10/09/2021
     * description : this method used to get all the sales order lines with the id from exchange summary
     **/
    public void setSalesOrderLines(Id customerExchangeSummaryId){
        salesOrderLines = [SELECT Id, inscor__Quantity_Ordered__c, inscor__Product__r.Name, 
                           inscor__Expected_Core_Serial_Number__c, inscor__Condition_Code__r.Name  
                           FROM inscor__Sales_Order_Line__c 
                           WHERE inscor__Order__c IN (SELECT inscor__Original_SO_ID__c 
                                                      FROM inscor__Customer_Exchange_Summary__c 
                                                      WHERE Id =: customerExchangeSummaryId)];
    }
    
    public String getIpAddress(){
        String ipAddress = ApexPages.currentPage().getHeaders().get('True-Client-IP');
        
        if (ipAddress == '' || ipAddress == null) {
            ipAddress = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP');
        }
        if (ipAddress == '' || ipAddress == null) {
            ipAddress = ApexPages.currentPage().getHeaders().get('X-Forwarded-For');
        }
        
        return ipAddress;
    }
    
    

    @AuraEnabled
    public static String getCurrentPageReference()
    {
        PageReference pageRef;
        String baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
        pageRef = new PageReference(baseUrl+'/apex/CoreExchangeFormResponsePDF');
        pageRef.setRedirect(true);
        System.debug(pageRef);
        return String.valueOf(pageRef);
    }
    
}