src/objects/Customer_Exchange_Summary_Form_Response__c.object
<CustomObject>
    <description>This will be a Child object of Customer Exchange Summary which will store the responses from Customer.</description>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Customer Exchange Summary Form Response</label>
    <nameField>
        <displayFormat>CFR-{000000000}</displayFormat>
        <label>Customer Exchange Summary Form Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Exchange Summary Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Company__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Address_1__c</fullName>
        <label>Address 1</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Company_Name__c</fullName>
        <label>Company Name</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>inscor__Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Company</label>
    <nameField>
        <displayFormat>CID-{0}</displayFormat>
        <label>Company ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CoreExchangeFormResponsePDFCtrlTest.cls
@isTest
public class CoreExchangeFormResponsePDFCtrlTest {
	@testSetup
    public static void setupData(){
        
        inscor__Company__c companyInstance = new inscor__Company__c();
        companyInstance.inscor__Company_Name__c = 'inscor Company' ;
        companyInstance.inscor__Address_1__c = 'address';
        companyInstance.inscor__City__c = 'xyz';
        companyInstance.inscor__Zip_Code__c = '21321';
        insert companyInstance;
        
        Customer_Exchange_Summary_Form_Response__c exchangeSummaryInstance = new Customer_Exchange_Summary_Form_Response__c();
        exchangeSummaryInstance.Name__c = 'er';
        insert exchangeSummaryInstance;
        
        }
    
    @isTest
    static void insertRecord(){
        List<Customer_Exchange_Summary_Form_Response__c> CustomerExchangeSummaryFormResponseList = [SELECT Id from Customer_Exchange_Summary_Form_Response__c];
        System.debug('Customer_Exchange_Summary_Form_Response__c->' + CustomerExchangeSummaryFormResponseList);
        Test.startTest();
        PageReference coreExchangeFormResponsePage = Page.coreExchangeFormResponsePDF;
        Test.setCurrentPage(coreExchangeFormResponsePage);
        coreExchangeFormResponsePage.getParameters().put('id', CustomerExchangeSummaryFormResponseList[0].Id);
        
         ApexPages.StandardController sc = new ApexPages.StandardController(CustomerExchangeSummaryFormResponseList[0]);
        try{
           CoreExchangeFormResponsePDFCtrl ext = new CoreExchangeFormResponsePDFCtrl();
        }catch(Exception e){
            System.debug(e);
        }         
       
         Test.stopTest();
    }
    @isTest
    static void testGetCurrentPageReference(){
        Test.startTest();
        CoreExchangeFormResponsePDFCtrl.getCurrentPageReference();
          Test.stopTest();
    }
}