src/objects/Customer_Exchange_Summary_Form_Response__c.object
<CustomObject>
    <description>This will be a Child object of Customer Exchange Summary which will store the responses from Customer.</description>
    <fields>
        <fullName>Customer_Exchange_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer Exchange Summary</description>
        <inlineHelpText>Customer Exchange Summary</inlineHelpText>
        <label>Customer Exchange Summary</label>
        <referenceTo>inscor__Customer_Exchange_Summary__c</referenceTo>
        <relationshipLabel>Customer Exchange Summary Form Responses</relationshipLabel>
        <relationshipName>Customer_From_Customer_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field used to lock the response so customer will not able to fill the exchange form again</description>
        <inlineHelpText>Field used to lock the response so customer will not able to fill the exchange form again</inlineHelpText>
        <label>Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Exchange Summary Form Response</label>
    <nameField>
        <displayFormat>CFR-{000000000}</displayFormat>
        <label>Customer Exchange Summary Form Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Exchange Summary Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Exchange_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Request_More_Information_JSON__c</fullName>
        <label>Request More Information JSON</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>inscor__Exchange_Status__c</fullName>
        <label>Exchange Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Core Received</fullName>
                </value>
                <value>
                    <fullName>Core at Repair</fullName>
                </value>
                <value>
                    <fullName>Core Repaired</fullName>
                </value>
                <value>
                    <fullName>Stocked</fullName>
                </value>
                <value>
                    <fullName>Shipped to Exchange Vendor</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Original_Core_Due_Date__c</fullName>
        <label>Original Core Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>inscor__Original_SO_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original SO ID</label>
        <referenceTo>inscor__Sales_Order__c</referenceTo>
        <relationshipLabel>Customer Exchange Summaries</relationshipLabel>
        <relationshipName>Customer_Exchange_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Exchange Summary</label>
    <nameField>
        <displayFormat>EXS-{0}</displayFormat>
        <label>Customer Exchange Summary ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Exchange Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.inscor__Customer__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.inscor__Dropship_Site__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.inscor__Dropship_Site__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.inscor__Dropship_Site__c</field>
                <operation>equals</operation>
                <valueField>Contact.inscor__Account_Shipping_Address__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Sales Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RequestMoreInformationController.cls
/**************************************************************************************************
Description: Controller class for requestMoreInformation LWCs
====================================================================================================
====================================================================================================
TestClass: 
Code Coverage: %
====================================================================================================
====================================================================================================
History
<Version>   	<Date>             <Author Name>                <Brief description of change > 
1.0 -      		08/09/2021		    Vinod Kumar Sharma		        Initial Creation    
***************************************************************************************************/
public class RequestMoreInformationController {

    @AuraEnabled
    public static void saveRequestMoreInformationMessage(String customerExchangeSummaryId, String informationJSON){
        try {
            inscor__Customer_Exchange_Summary__c customerExchangeSummary = new inscor__Customer_Exchange_Summary__c(Id = customerExchangeSummaryId);
            customerExchangeSummary.Request_More_Information_JSON__c = informationJSON;
            update customerExchangeSummary;
            Customer_Exchange_Summary_Form_Response__c customerExchangeSummaryResponse = [SELECT Id, Locked__c 
                                                                                            FROM Customer_Exchange_Summary_Form_Response__c 
                                                                                            WHERE  Customer_Exchange_Summary__c = :customerExchangeSummaryId];
            customerExchangeSummaryResponse.Locked__c = false;
            update customerExchangeSummaryResponse;
            sendEmail(customerExchangeSummary.Id);
        } catch (Exception e) {
            System.debug('exception '+e);
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static inscor__Customer_Exchange_Summary__c getCustomerSummary(String customerExchangeSummaryId){
        try {
            return [SELECT inscor__Exchange_Status__c, inscor__Original_Core_Due_Date__c FROM inscor__Customer_Exchange_Summary__c
                                                            WHERE Id =:customerExchangeSummaryId];

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Boolean isCustomerExchangeFormResponseAvailable(String customerExchangeSummaryId){
        try {
            System.debug('recordId ->' + customerExchangeSummaryId);
            List<Customer_Exchange_Summary_Form_Response__c> customerExchangeSummaryResponse = [SELECT Id 
                                                                                        FROM Customer_Exchange_Summary_Form_Response__c 
                                                                                        WHERE  Customer_Exchange_Summary__c = :customerExchangeSummaryId ];
                                                                                        
            if (!customerExchangeSummaryResponse.isEmpty()) {
                return true;
            }else {
                return false;
            }
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * @date : 08/09/2021
     */
    private static void sendEmail(Id customerExchangeSummaryId){
        List<inscor__Customer_Exchange_Summary__c> customerExchangeSummary =  new List<inscor__Customer_Exchange_Summary__c>
                                                                                    ([
                                                                                        SELECT 
                                                                                            Id,
                                                                                            inscor__Original_SO_ID__c, 
                                                                                            inscor__Original_SO_ID__r.inscor__Assigned_To__r.Email,
                                                                                            inscor__Original_SO_ID__r.inscor__Contact__r.Email
                                                                                        FROM inscor__Customer_Exchange_Summary__c
                                                                                        WHERE Id =: customerExchangeSummaryId
                                                                                    ]);
                
        if(customerExchangeSummary != NULL && !customerExchangeSummary.isEmpty()){
            Id emailTemplateId = [  SELECT Id FROM EmailTemplate 
                                    WHERE DeveloperName =: Constants.EMAIL_TEMPLATE_REQUEST_MORE_INFORMATION 
                                    LIMIT 1]?.Id;
            inscor__Customer_Exchange_Summary__c iceRec = customerExchangeSummary[0];
            if(emailTemplateId == NULL) 
            {
                LogService.createErrorLog('RequestMoreInformationController.cls', NULL, NULL, Constants.EMAIL_TEMPLATE_REQUEST_MORE_INFORMATION+ ' Email template does not exist.');
                return;
            }
            /* Assumption : Only one record will come because we have recordId Check in Query */
            Map<Id, List<String>> cseIdtoTOAddressMap = new Map<Id, List<String>>();
            Map<Id, List<String>> objIdtoCCAddress = new Map<Id, List<String>>();
            List<String> ccEmailAddresses = new List<String>{Label.Core_Exchange_Customer_CC_EmailAddress};
            if(!cseIdtoTOAddressMap.containsKey(iceRec.Id))
            { 
                cseIdtoTOAddressMap.put(iceRec.Id, new List<String>());
                objIdtoCCAddress.put(iceRec.Id, ccEmailAddresses);
                if(String.isNotBlank(iceRec.inscor__Original_SO_ID__c))
                {
                    if(iceRec.inscor__Original_SO_ID__r.inscor__Contact__r != NULL && iceRec.inscor__Original_SO_ID__r.inscor__Contact__r.Email != NULL)
                        cseIdtoTOAddressMap.get(iceRec.Id)
                            .add(iceRec.inscor__Original_SO_ID__r.inscor__Contact__r.Email);
                }
                cseIdtoTOAddressMap.get(iceRec.Id)
                            .add(System.Label.Customer_Support_Email);
            }
            //CommonUtility.sendEmail(emailTemplateId, cseIdtoTOAddressMap, NULL, NULL);
            CommonUtility.sendEmailForCustomerExchangeSummary(emailTemplateId, cseIdtoTOAddressMap, objIdtoCCAddress, NULL);
        }
    }
}