src/objects/inscor__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_SO__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quote_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Number</label>
        <referenceTo>inscor__Customer_Quote__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Sales Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Line_Total__c</fullName>
        <formula>inscor__Quantity_Ordered__c *  inscor__Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Order__c</fullName>
        <label>Order</label>
        <referenceTo>inscor__Sales_Order__c</referenceTo>
        <relationshipName>Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity_Ordered__c</fullName>
        <label>Quantity Ordered</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{0}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trigger_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Trigger Configuration will be used for maintaining trigger toggle for its execution.</description>
    <fields>
        <fullName>Sales_Order_Line_Trigger_Disable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disable Sales Order Line Trigger</description>
        <inlineHelpText>Disable Sales Order Line Trigger</inlineHelpText>
        <label>Sales Order Line Trigger Disable</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Configuration</label>
</CustomObject>

src/classes/SalesOrderLineItemTriggerHelper.cls
/**************************************************************************************************
Description: Trigger class for inscor__Sales_Order_Line__c that will handle all types of trigger events.
====================================================================================================
====================================================================================================
TestClass: SalesOrderLineItemTriggerHelperTest
Code Coverage: 100%
====================================================================================================
====================================================================================================
History
<Version>   	<Date>             <Author Name>                <Brief description of change > 
1.0 -      		05/20/2021		    Gourav Goyal				Initial Creation     
***************************************************************************************************/
public class SalesOrderLineItemTriggerHelper implements TriggerHandler {
    
    /*Allows unit tests (or other code) to disable this trigger for the transaction */
    
    public static Boolean TriggerDisabled = false;
    
    Public static Set<String> statusToInclude = new Set<String>{'In Progress', 'Sent to Customer'};
        
        /*Checks to see if the trigger has been disabled either by custom setting or by running code*/
        
        public Boolean IsDisabled() {
            /*Use the option below if you set up Custom Settings to controll Triggers*/
            Trigger_Configuration__c configSetting = Trigger_Configuration__c.getInstance();   
            if(configSetting.Sales_Order_Line_Trigger_Disable__c == true) {
                return true;
            } else {
                return TriggerDisabled;
            }
        }

    /* CALLING */
    public void BeforeInsert(SObject[] newList) {}
    
    public void BeforeUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {}
    
    public void BeforeDelete(Map<Id, SObject> oldMap) {}
    
    public void AfterInsert(Map<Id, SObject> newMap) {
        SalesOrderLineItemTriggerHelper.updateCustomerScoreOnAccount((List<inscor__Sales_Order_Line__c>)newMap.values(), null);
    }
    
    public void AfterUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
        SalesOrderLineItemTriggerHelper.updateCustomerScoreOnAccount((List<inscor__Sales_Order_Line__c>)newMap.values(), (Map<Id, inscor__Sales_Order_Line__c>) oldMap);
    }
    
    public void AfterDelete(Map<Id, SObject> oldMap) {
        SalesOrderLineItemTriggerHelper.updateCustomerScoreOnAccount((List<inscor__Sales_Order_Line__c>)oldMap.values(), null);
    }
    
    public void AfterUndelete(Map<Id, SObject> oldMap) {}

    public static void updateCustomerScoreOnAccount(List<inscor__Sales_Order_Line__c> salesOrderLines, Map<Id, inscor__Sales_Order_Line__c> oldMap) {
        try {  
            Set<String> salesOrderIds = new Set<String>();
            if (oldMap != null) {
                for (inscor__Sales_Order_Line__c orderLine : salesOrderLines) {
                    if (orderLine.inscor__Quantity_Ordered__c != oldMap.get(orderLine.Id).inscor__Quantity_Ordered__c
                        || orderLine.inscor__Line_Total__c != oldMap.get(orderLine.Id).inscor__Line_Total__c) {
                            salesOrderIds.add(orderLine.inscor__Order__c);
                    }
                }
            }else {
                for (inscor__Sales_Order_Line__c orderLine : salesOrderLines) {
                    salesOrderIds.add(orderLine.inscor__Order__c);
                }
            }
            if (!salesOrderIds.isEmpty()) {
                Set<String> accountIds = new Set<String>();      
                Set<String> customerQuoteIds = new Set<String>();      
                for(inscor__Sales_Order__c soRec : [SELECT inscor__Customer__c, inscor__Quote_Number__c  FROM inscor__Sales_Order__c WHERE Id IN :salesOrderIds]){
                    accountIds.add(soRec.inscor__Customer__c);
                    customerQuoteIds.add(soRec.inscor__Quote_Number__c);
                }
                AccountUtility.updateCustomerSalesOrderValues(accountIds);
                System.debug('customerQuoteIds ->' + customerQuoteIds);
                //OpportunityUtility.calculateOpportunityProbablity(accountIds);
            }
        } catch (Exception error) {
            System.debug('error:' + error.getMessage());
            LogService.createErrorLog('SalesOrderLineItemTriggerHelper.apxc', NULL, error, NULL);
        }
    }
}