src/objects/inscor__Account_Ship_Address__c.object
<CustomObject>
    <fields>
        <fullName>Shipping__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Shipping?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>inscor__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Ship Addresses</relationshipLabel>
        <relationshipName>Account_Ship_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__State__c</fullName>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Street__c</fullName>
        <label>Street</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Account Ship Address</label>
    <nameField>
        <label>Account Ship Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Ship Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/shippingNewAddressController.cls
public class shippingNewAddressController {
    @AuraEnabled
    public static String shippingNewAddress(string street,string city,string state,string postalcode,string country,String name) {//,String Name
        //string contactId;
        string accountId;
		
         // User Info...
		List<User> UserDetails = new List<User>([SELECT Id,Contact.AccountID FROM User WHERE Id =:UserInfo.getUserId()]);
		if(!UserDetails.IsEmpty()){
			accountId = UserDetails[0].Contact?.AccountId;
		}
        
        //AddressType='Shipping';
        //Add New Shipping Address.
        ContactPointAddress NewAddress = new ContactPointAddress();
        NewAddress.ParentId = accountId;
        NewAddress.Name = name;
        NewAddress.Street = street;
        NewAddress.City = city;
        NewAddress.State = state;
        NewAddress.PostalCode = postalcode;
        NewAddress.Country = country;
        NewAddress.AddressType='Shipping';
        insert NewAddress;
        try{
            inscor__Account_Ship_Address__c newShippingAddress = new inscor__Account_Ship_Address__c();
            newShippingAddress.inscor__Account__c = accountId;
            newShippingAddress.inscor__City__c = city;
            newShippingAddress.inscor__Country__c = country;
            newShippingAddress.inscor__Postal_Code__c = postalcode;
            newShippingAddress.inscor__State__c = state;
            newShippingAddress.inscor__Street__c = street;
            newShippingAddress.Name = name;
            newShippingAddress.Shipping__c = true;
            insert newShippingAddress; 
        }catch(Exception e){
            System.debug('Error '+e.getStackTraceString());
        }
        return 'Sucesssfully added';

    }
    
    
   
}