src/objects/inscor__Alternate__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Alternate_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Alternate Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Alternates</relationshipLabel>
        <relationshipName>Alternates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Description__c</fullName>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <label>Alternate</label>
    <nameField>
        <displayFormat>AID-{0}</displayFormat>
        <label>Alternate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alternates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Contract_Price__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <formula>inscor__Product__r.inscor__Keyword__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Keyword</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Customer Contract Prices</relationshipLabel>
        <relationshipName>Customer_Contract_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Contract Price</label>
    <nameField>
        <displayFormat>CCP-{0}</displayFormat>
        <label>Customer Contract Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Contract Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Inventory_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Line</label>
        <referenceTo>inscor__Inventory_Line__c</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <formula>inscor__Product__r.inscor__Keyword__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Keyword</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Quote Line</label>
    <nameField>
        <displayFormat>QUL-{0}</displayFormat>
        <label>Quote Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Inventory_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <formula>inscor__Product__r.inscor__Keyword__c</formula>
        <label>Keyword</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Parent_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Inventory</label>
        <referenceTo>inscor__Inventory_Line__c</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{0}</displayFormat>
        <label>Inventory UID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Price__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Price Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Purchase_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Inventory_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Line</label>
        <referenceTo>inscor__Inventory_Line__c</referenceTo>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POL-{0}</displayFormat>
        <label>PO Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Repair_Contract_Price__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <formula>inscor__Product__r.inscor__Keyword__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Keyword</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Repair Contract Prices</relationshipLabel>
        <relationshipName>Repair_Contract_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Repair Contract Price</label>
    <nameField>
        <displayFormat>RCID-{0}</displayFormat>
        <label>Repair Contract Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repair Contract Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <formula>inscor__Product__r.inscor__Keyword__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Keyword</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Parent_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Line</label>
        <referenceTo>inscor__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quote_Line_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line Number</label>
        <referenceTo>inscor__Customer_Quote_Line__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quoted_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quoted Inventory</label>
        <referenceTo>inscor__Inventory_Line__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{0}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Vendor_Contract_Price__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <formula>inscor__Product__r.inscor__Keyword__c</formula>
        <label>Keyword</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Vendor Contract Prices</relationshipLabel>
        <relationshipName>Vendor_Contract_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Contract Price</label>
    <nameField>
        <displayFormat>VCID-{0}</displayFormat>
        <label>Vendor Contract Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Contract Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>inscor__Description__c</fullName>
        <label>Description</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <label>Keyword</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/unusedInventoryTableCTRL.cls
public class unusedInventoryTableCTRL {
    
    @AuraEnabled
    public static List<Product2> getunUsedInventory(){
        try {
            List<Product2> productsList = new List<Product2>();
            List<Product2> productsList2 = new List<Product2>();
            List<Product2> productsList3 = new List<Product2>();
            List<Product2> productsList4 = new List<Product2>();
            List<Product2> productsList5 = new List<Product2>();
            List<Product2> productsList6 = new List<Product2>();
            List<Product2> productsList7 = new List<Product2>();
            List<Product2> productsList8 = new List<Product2>();
            List<Product2> productsList9 = new List<Product2>();
            List<Product2> productsList10 = new List<Product2>();
            List<Product2> productsList11 = new List<Product2>();
            List<Product2> unUsedProductsList = new List<Product2>();
            productsList = [SELECT Id, ProductCode, Name, inscor__Keyword__c, inscor__Description__c 
                            , (select id, inscor__Price__c from inscor__Customer_Quote_Lines__r LIMIT 1)
                            , (select id from inscor__Sales_Order_Lines__r LIMIT 1)
                            , (select id from inscor__Purchase_Order_Lines__r LIMIT 1)
                            , (select id from inscor__Repair_Contract_Prices__r LIMIT 1)
                            , (select id from inscor__Customer_Contract_Prices__r LIMIT 1)
                            , (select id from inscor__Vendor_Contract_Prices__r LIMIT 1)
                            , (select id from inscor__Inventory__r LIMIT 1)
                            FROM Product2 order by ProductCode desc limit 15000 ];
            for(Product2 product: productsList){
                if(product.inscor__Customer_Quote_Lines__r.size() >0 
                   && product.inscor__Sales_Order_Lines__r.size() ==0
                   && product.inscor__Purchase_Order_Lines__r.size() ==0
                   && product.inscor__Inventory__r.size() ==0
                   && (product.inscor__Repair_Contract_Prices__r.size() > 0
                       || product.inscor__Customer_Contract_Prices__r.size()> 0
                       || product.inscor__Vendor_Contract_Prices__r.size() > 0) 
                  ){
                      system.debug('product.inscor__Customer_Quote_Lines__r >>'+product.inscor__Customer_Quote_Lines__r);
                      for(inscor__Customer_Quote_Line__c quoteLine: product.inscor__Customer_Quote_Lines__r){
                          if(quoteLine.inscor__Price__c == 0){
                              unUsedProductsList.add(product);
                          }
                          
                      }
                      
                      
                  }
            }
            
            return unUsedProductsList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static void deleteSelectedInventory( String selectedRows){
        try {
            List<inscor__Alternate__c> alternateRecords = new List<inscor__Alternate__c>();
            List<Product2>  resultsn = (List<Product2>)JSON.deserialize(selectedRows, List<Product2>.class);
            if(resultsn.size() > 0) {
                Set<Id> productIds = new Set<Id>();
                for(Product2 product: resultsn){
                    productIds.add(product.id);
                }
                if(!test.isRunningTest()){
                    delete [select id from inscor__Alternate__c where inscor__Alternate_Product__c IN : productIds];
                    delete [select id from inscor__Repair_Contract_Price__c where inscor__Product__c IN : productIds];
                    delete [select id from inscor__Customer_Contract_Price__c where inscor__Product__c IN : productIds];
                    delete [select id from inscor__Vendor_Contract_Price__c where inscor__Product__c IN : productIds];
                    delete resultsn;
                }
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}