src/objects/inscor__Alternate__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Alternate_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Alternate Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Alternates</relationshipLabel>
        <relationshipName>Alternates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Primary_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Alternates (Primary Part Number)</relationshipLabel>
        <relationshipName>Alternates1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Alternate</label>
    <nameField>
        <displayFormat>AID-{0}</displayFormat>
        <label>Alternate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alternates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AlternateController.cls
public with sharing class AlternateController {
    @AuraEnabled(cacheable=true)
    public static List<inscor__Alternate__c> AlternateProduct(string ProductId) {
        system.debug('ProductId'+ ProductId);
        List<inscor__Alternate__c> AlternateProductList = New List<inscor__Alternate__c>([SELECT Name, Id, inscor__Primary_Product__c,inscor__Primary_Product__r.Name FROM 
        inscor__Alternate__c where inscor__Alternate_Product__c= :ProductId]);
        system.debug('AlternateProductList' + AlternateProductList);
        return AlternateProductList;
    }
}