src/objects/inscor__Account_Ship_Address__c.object
<CustomObject>
    <fields>
        <fullName>Shipping__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Shipping?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>inscor__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Ship Addresses</relationshipLabel>
        <relationshipName>Account_Ship_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__State__c</fullName>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Street__c</fullName>
        <label>Street</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Account Ship Address</label>
    <nameField>
        <label>Account Ship Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Ship Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Company__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Address_1__c</fullName>
        <label>Address 1</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Company_Name__c</fullName>
        <label>Company Name</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>inscor__Country__c</fullName>
        <label>Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Company</label>
    <nameField>
        <displayFormat>CID-{0}</displayFormat>
        <label>Company ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Company_Location__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Company__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Company</label>
        <referenceTo>inscor__Company__c</referenceTo>
        <relationshipLabel>Company Locations</relationshipLabel>
        <relationshipName>Company_Locations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Company Location</label>
    <nameField>
        <label>Company Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Condition_Code__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Show_in_Summary__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show in Summary</label>
        <type>Checkbox</type>
    </fields>
    <label>Condition Code</label>
    <nameField>
        <label>Condition Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Inventory_Location__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Company_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Company Location</label>
        <referenceTo>inscor__Company_Location__c</referenceTo>
        <relationshipLabel>Inventory Locations</relationshipLabel>
        <relationshipName>Inventory_Locations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Inventory Location</label>
    <nameField>
        <label>Inventory Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Owner_Code__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Company__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Company</label>
        <referenceTo>inscor__Company__c</referenceTo>
        <relationshipLabel>Owner Codes</relationshipLabel>
        <relationshipName>Owner_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Owner Code</label>
    <nameField>
        <label>Owner Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Owner Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Warehouse__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Company_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Company Location</label>
        <referenceTo>inscor__Company_Location__c</referenceTo>
        <relationshipLabel>Warehouses</relationshipLabel>
        <relationshipName>Warehouses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Warehouse_Code__c</fullName>
        <label>Warehouse Code</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Condition_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_Type__c</fullName>
        <label>Price Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cost Plus</fullName>
                </value>
                <value>
                    <fullName>Flat Rate w/OH Core</fullName>
                </value>
                <value>
                    <fullName>Flat Rate w/SV Core</fullName>
                </value>
                <value>
                    <fullName>Flat Rate w/Repairable Core</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <label>Keyword</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__UOM__c</fullName>
        <label>UOM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EA</fullName>
                </value>
                <value>
                    <fullName>FT</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>YD</fullName>
                </value>
                <value>
                    <fullName>BG</fullName>
                </value>
                <value>
                    <fullName>BX</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>DR</fullName>
                </value>
                <value>
                    <fullName>FT2</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>GL</fullName>
                </value>
                <value>
                    <fullName>GLL</fullName>
                </value>
                <value>
                    <fullName>IN2</fullName>
                </value>
                <value>
                    <fullName>KT</fullName>
                </value>
                <value>
                    <fullName>LB</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>ML</fullName>
                </value>
                <value>
                    <fullName>MM</fullName>
                </value>
                <value>
                    <fullName>OZ</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>PT</fullName>
                </value>
                <value>
                    <fullName>QT</fullName>
                </value>
                <value>
                    <fullName>RL</fullName>
                </value>
                <value>
                    <fullName>SF</fullName>
                </value>
                <value>
                    <fullName>SH</fullName>
                </value>
                <value>
                    <fullName>SI</fullName>
                </value>
                <value>
                    <fullName>SP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateSOTest.cls
@isTest
public class CreateSOTest {
	@isTest
    public static void invokeSO(){
        
         Salesforce_Auth__c objSalesforceAuth = new Salesforce_Auth__c(
            Client_Id__c='test',
            Client_Secret__c='test',
            Login_Url__c='https://test.salesforce.com',
            Password__c='test',
            Security_Token__c='test',
            UserName__c='test');
        insert objSalesforceAuth;
        
        Account objAcc = new Account();
        objAcc.Name = 'Test';
        insert objAcc;
        
        inscor__Account_Ship_Address__c newShippingAddress = new inscor__Account_Ship_Address__c();
        newShippingAddress.inscor__Account__c = objAcc.Id;
        newShippingAddress.inscor__City__c = 'City';
        newShippingAddress.inscor__Country__c = 'country';
        newShippingAddress.inscor__Postal_Code__c = '411HK';
        newShippingAddress.inscor__State__c = 'MH';
        newShippingAddress.inscor__Street__c = 'street';
        newShippingAddress.Name = 'SHIPPING';
        newShippingAddress.Shipping__c = true;
        insert newShippingAddress; 
        
        List<ID> orderList = new List<ID>();
        Order objOrder = new Order();
        objOrder.Status = 'Draft';
        objOrder.AccountId =objAcc.Id;
        objOrder.EffectiveDate = System.today();
        insert objOrder;
        
        Product2 pr = new Product2(Name ='#16',inscor__Keyword__c = 'SCREW',inscor__UOM__c='EA');
        insert pr;
        
        inscor__Company__c  company = new inscor__Company__c(
            inscor__Address_1__c = '1111', inscor__City__c = '1111', inscor__Company_Name__c = '1111', inscor__Zip_Code__c = '1111');
        insert company;
        inscor__Company_Location__c companyLoc = new inscor__Company_Location__c( inscor__Company__c =company.Id );
        insert companyLoc;
        
        inscor__Inventory_Location__c invLocation  = new inscor__Inventory_Location__c(
            inscor__Company_Location__c = companyLoc.Id );
        insert invLocation;
        
        inscor__Owner_Code__c ownerCode = new inscor__Owner_Code__c(inscor__Company__c =company.Id);
        insert ownerCode;
        
        inscor__Warehouse__c warehouse = new inscor__Warehouse__c( 
            inscor__Company_Location__c = companyLoc.Id, inscor__Warehouse_Code__c ='1111' );
        insert warehouse; 
        
        
        inscor__Condition_Code__c code = new inscor__Condition_Code__c();
        code.Name='NE';
        code.inscor__Show_in_Summary__c=false;
        insert code;
        
        orderItem oi = new OrderItem();
        oi.Product2ID = pr.id;
        oi.Condition_Code__c = code.id;
        oi.OrderId = objOrder.Id;
        oi.UnitPrice = 10;
		oi.ListPrice = 10;
		oi.Quantity = 1;  
        oi.Price_Type__c = 'Cost Plus';
        insert oi;
        
        objOrder.Status='Activated';
        update objOrder;
        
        System.debug('oi -> '+oi);
        orderList.add(objOrder.Id);
        String jsonSTR = '{"OrderId":'+JSON.serialize(objOrder)+'}';
        InvokeSOcreationFlow.invokeFlow(orderList);
        CreateSO.justIncrement();
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CreateSO'; 
        req.httpMethod = 'POST';
        req.addHeader('Content-Type', 'application/json'); 
        //req.requestBody = Blob.valueOf(jsonSTR);
        RestContext.request = req;
        RestContext.response = res;
        test.startTest();
        	Test.setMock(HttpCalloutMock.class, new CustomerquoteTestcontroller());
        	CreateSO.doPost();
        
        test.stopTest();
        /*List<User> uList = new List<User>([SELECT ID FROM User WHERE IsActive = true AND Profile.Name = 'System Admin Clone' Limit 1]);
        System.runAs(uList[0]){        
            test.startTest();
            Test.setMock(HttpCalloutMock.class, new CustomerquoteTestcontroller());            	
                CreateSO.doPost();
            test.stopTest();
        }*/
    }
    
    /*@isTest
    public static void testRestClass(){
        
        
        Account objAcc = new Account();
        objAcc.Name = 'Test';
        insert objAcc;
        
        inscor__Account_Ship_Address__c newShippingAddress = new inscor__Account_Ship_Address__c();
        newShippingAddress.inscor__Account__c = objAcc.Id;
        newShippingAddress.inscor__City__c = 'City';
        newShippingAddress.inscor__Country__c = 'country';
        newShippingAddress.inscor__Postal_Code__c = '411HK';
        newShippingAddress.inscor__State__c = 'MH';
        newShippingAddress.inscor__Street__c = 'street';
        newShippingAddress.Name = 'SHIPPING';
        newShippingAddress.Shipping__c = true;
        insert newShippingAddress; 
        
        List<ID> orderList = new List<ID>();
        Order objOrder = new Order();
        objOrder.Status = 'Draft';
        objOrder.AccountId =objAcc.Id;
        objOrder.EffectiveDate = System.today();
        insert objOrder;
        
        Product2 pr = new Product2(Name ='#16',inscor__Keyword__c = 'SCREW',inscor__UOM__c='EA');
        insert pr;
        
        inscor__Company__c  company = new inscor__Company__c(
            inscor__Address_1__c = '1111', inscor__City__c = '1111', inscor__Company_Name__c = '1111', inscor__Zip_Code__c = '1111');
        insert company;
        inscor__Company_Location__c companyLoc = new inscor__Company_Location__c( inscor__Company__c =company.Id );
        insert companyLoc;
        
        inscor__Inventory_Location__c invLocation  = new inscor__Inventory_Location__c(
            inscor__Company_Location__c = companyLoc.Id );
        insert invLocation;
        
        inscor__Owner_Code__c ownerCode = new inscor__Owner_Code__c();
        insert ownerCode;
        
        inscor__Warehouse__c warehouse = new inscor__Warehouse__c( 
            inscor__Company_Location__c = companyLoc.Id, inscor__Warehouse_Code__c ='1111' );
        insert warehouse; 
        
        
        inscor__Condition_Code__c code = new inscor__Condition_Code__c();
        code.Name='NE';
        code.inscor__Show_in_Summary__c=false;
        insert code;
        
        orderItem oi = new OrderItem();
        oi.Product2ID = pr.id;
        oi.Condition_Code__c = code.id;
        oi.OrderId = objOrder.Id;
        oi.UnitPrice = 10;
		oi.ListPrice = 10;
		oi.Quantity = 1;        
        insert oi;
        
        objOrder.Status='Activated';
        update objOrder;
        
        System.debug('objOrder -> '+objOrder);
        orderList.add(objOrder.Id);
        
        List<User> uList = new List<User>([SELECT ID FROM User WHERE IsActive = true AND Profile.Name = 'System Admin Clone' Limit 1]);
        System.runAs(uList[0]){        
            test.startTest();
            Test.setMock(HttpCalloutMock.class, new CustomerquoteTestcontroller());
                CreateSO.doPost();
            test.stopTest();
        }
    }*/
}