src/objects/inscor__Customer_Quote__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_CQ__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Quotes</relationshipLabel>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Quote</label>
    <nameField>
        <displayFormat>QU-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Customer_Quote__c</fullName>
        <label>Customer Quote</label>
        <referenceTo>inscor__Customer_Quote__c</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer Quote Line</label>
    <nameField>
        <displayFormat>QUL-{0}</displayFormat>
        <label>Quote Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_SO__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Sales Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Order__c</fullName>
        <label>Order</label>
        <referenceTo>inscor__Sales_Order__c</referenceTo>
        <relationshipName>Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity_Ordered__c</fullName>
        <label>Quantity Ordered</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{0}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PartOrderController.cls
public class PartOrderController {
   
    @AuraEnabled
    public static List<ResponseWrapper> getCustomerQuotes(String accountId){
		AggregateResult[] groupedResultsAllTime = [SELECT inscor__Product__c Id,inscor__Product__r.name partName,SUM(inscor__Quantity__c), COUNT(inscor__Customer_Quote__c)  
                                                    FROM inscor__Customer_Quote_Line__c 
                                                    WHERE inscor__Customer_Quote__r.inscor__Customer__c = : accountId AND inscor__Product__c != NULL AND inscor__Quantity__c != NULL
                                                    GROUP BY inscor__Product__c,inscor__Product__r.name order by SUM(inscor__Quantity__c) desc limit 5];
        Map<Id, AggregateResult> last365DaysMap = new Map<Id, AggregateResult>(
                                                                        [SELECT inscor__Product__c Id, 
                                                                        COUNT(inscor__Customer_Quote__c)  
                                                                        FROM inscor__Customer_Quote_Line__c 
                                                                        WHERE inscor__Customer_Quote__r.inscor__Customer__c = : accountId AND inscor__Quantity__c != NULL
                                                                        AND createdDate =LAST_N_DAYS:365  AND inscor__Product__c != NULL
                                                                        GROUP BY inscor__Product__c,inscor__Product__r.name order by SUM(inscor__Quantity__c) desc limit 5]
        );
        List<ResponseWrapper> responseWrappers = new List<ResponseWrapper>();
        for (AggregateResult result : groupedResultsAllTime) {
            ResponseWrapper responseWrapper = new ResponseWrapper();
            responseWrapper.partId = (Id)result.get('Id');
            responseWrapper.partName = (String)result.get('partName');
            responseWrapper.Qty = (Decimal)result.get('expr0');
            responseWrapper.last365 = (Decimal)(last365DaysMap.containsKey((Id)result.get('Id')) ? last365DaysMap.get((Id)result.get('Id')).get('expr0') : 0);
            responseWrapper.allTime = (Decimal)result.get('expr1');
            responseWrappers.add(responseWrapper);
        }
        return responseWrappers;
    }
    
    @AuraEnabled
    public static List<ResponseWrapper> getCustomerQuotesLineItem(String accountId){

        AggregateResult[] groupedResultsAllTime = [SELECT inscor__Product__c Id,inscor__Product__r.name partName, SUM(inscor__Quantity__c), COUNT(inscor__Customer_Quote__c)  
                                                    FROM inscor__Customer_Quote_Line__c 
                                                    WHERE inscor__Customer_Quote__r.inscor__Customer__c = : accountId AND inscor__Quantity__c != NULL AND inscor__Product__c != NULL
                                                    GROUP BY inscor__Product__c,inscor__Product__r.name 
                                                    ORDER BY SUM(inscor__Quantity__c) desc];
        Map<Id, AggregateResult> last365DaysMap = new Map<Id, AggregateResult>(
                                                                        [SELECT inscor__Product__c Id, 
                                                                        COUNT(inscor__Customer_Quote__c)  from inscor__Customer_Quote_Line__c 
                                                                        WHERE inscor__Customer_Quote__r.inscor__Customer__c = : accountId AND createdDate =LAST_N_DAYS:365  AND inscor__Product__c != NULL
                                                                        GROUP BY inscor__Product__c,inscor__Product__r.name
                                                                        ORDER BY SUM(inscor__Quantity__c) desc]
        );

        List<ResponseWrapper> responseWrappers = new List<ResponseWrapper>();
        for (AggregateResult result : groupedResultsAllTime) {
            ResponseWrapper responseWrapper = new ResponseWrapper();
            responseWrapper.partId = (Id)result.get('Id');
            responseWrapper.partName = (String)result.get('partName');
            responseWrapper.Qty = (Decimal)result.get('expr0');
            responseWrapper.last365 = (Decimal)(last365DaysMap.containsKey((Id)result.get('Id')) ? last365DaysMap.get((Id)result.get('Id')).get('expr0') : 0);
            responseWrapper.allTime = (Decimal)result.get('expr1');
            responseWrappers.add(responseWrapper);
        }
        return responseWrappers;
    }
     
  
    @AuraEnabled
    public static List<ResponseWrapper> getSalesOrder(String accountId){
        AggregateResult[] groupedResultsAllTime = [SELECT inscor__Product__c Id,inscor__Product__r.name partName,SUM(inscor__Quantity_Ordered__c), COUNT(inscor__Order__C)
                                            FROM inscor__Sales_Order_Line__c 
                                            WHERE inscor__Order__r.inscor__Customer__c =: accountId AND inscor__Quantity_Ordered__c != NULL  AND inscor__Product__c != NULL
                                            GROUP BY inscor__Product__c,inscor__Product__r.name 
                                            ORDER BY SUM(inscor__Quantity_Ordered__c) desc limit 5];
        Map<Id, AggregateResult> last365DaysMap = new Map<Id, AggregateResult>(
                                                                [SELECT inscor__Product__c Id,inscor__Product__r.name,
                                                                COUNT(inscor__Order__C)
                                                                FROM inscor__Sales_Order_Line__c 
                                                                WHERE inscor__Order__r.inscor__Customer__c =: accountId AND inscor__Product__c != NULL AND createdDate =LAST_N_DAYS:365
                                                                GROUP BY inscor__Product__c,inscor__Product__r.name 
                                                                ORDER BY SUM(inscor__Quantity_Ordered__c) desc limit 5]
        );

        List<ResponseWrapper> responseWrappers = new List<ResponseWrapper>();
        for (AggregateResult result : groupedResultsAllTime) {
            ResponseWrapper responseWrapper = new ResponseWrapper();
            responseWrapper.partId = (Id)result.get('Id');
            responseWrapper.partName = (String)result.get('partName');
            responseWrapper.Qty = (Decimal)result.get('expr0');
            responseWrapper.last365 = (Decimal)(last365DaysMap.containsKey((Id)result.get('Id')) ? last365DaysMap.get((Id)result.get('Id')).get('expr0') : 0);
            responseWrapper.allTime = (Decimal)result.get('expr1');
            responseWrappers.add(responseWrapper);
        }
        return responseWrappers;
    }
    
   @AuraEnabled
    public static List<ResponseWrapper> getSalesQuotesLineItem(String accountId){
        AggregateResult[] groupedResultsAllTime = [SELECT inscor__Product__c Id,inscor__Product__r.name partName,SUM(inscor__Quantity_Ordered__c), COUNT(inscor__Order__C)
                                            FROM inscor__Sales_Order_Line__c 
                                            WHERE inscor__Order__r.inscor__Customer__c =: accountId AND inscor__Quantity_Ordered__c != NULL AND inscor__Product__c != NULL
                                            GROUP BY inscor__Product__c,inscor__Product__r.name 
                                            ORDER BY SUM(inscor__Quantity_Ordered__c) desc];
        Map<Id, AggregateResult> last365DaysMap = new Map<Id, AggregateResult>(
                                                                [SELECT inscor__Product__c Id,inscor__Product__r.name,
                                                                COUNT(inscor__Order__C)
                                                                FROM inscor__Sales_Order_Line__c 
                                                                WHERE inscor__Order__r.inscor__Customer__c =: accountId  AND inscor__Product__c != NULL AND createdDate =LAST_N_DAYS:365
                                                                GROUP BY inscor__Product__c,inscor__Product__r.name 
                                                                ORDER BY SUM(inscor__Quantity_Ordered__c) desc]
        );

        List<ResponseWrapper> responseWrappers = new List<ResponseWrapper>();
        for (AggregateResult result : groupedResultsAllTime) {
            ResponseWrapper responseWrapper = new ResponseWrapper();
            responseWrapper.partId = (Id)result.get('Id');
            responseWrapper.partName = (String)result.get('partName');
            responseWrapper.Qty = (Decimal)result.get('expr0');
            responseWrapper.last365 = (Decimal)(last365DaysMap.containsKey((Id)result.get('Id')) ? last365DaysMap.get((Id)result.get('Id')).get('expr0') : 0);
            responseWrapper.allTime = (Decimal)result.get('expr1');
            responseWrappers.add(responseWrapper);
        }
        return responseWrappers;
    }
    
    private static void getResponseWrapperData() {
        
    }

    public class ResponseWrapper{
        @AuraEnabled public Id partId{get; set;} 
        @AuraEnabled public String partName{get; set;} 
        @AuraEnabled public Decimal Qty{get; set;} 
        @AuraEnabled public Decimal last365{get; set;} 
        @AuraEnabled public Decimal allTime{get; set;} 
    }
}