src/objects/inscor__Customer_Quote__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Business_Category__c</fullName>
        <label>Business Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Business_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_CQ__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Quotes</relationshipLabel>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Closed - Won</fullName>
                </value>
                <value>
                    <fullName>Closed - Lost</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Quote</label>
    <nameField>
        <displayFormat>QU-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Business_Category__c</fullName>
        <label>Business Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Business_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Customer_Quote__c</fullName>
        <label>Customer Quote</label>
        <referenceTo>inscor__Customer_Quote__c</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Ready to Quote</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Queued to Quote</fullName>
                </value>
                <value>
                    <fullName>Quoted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Quote Line</label>
    <nameField>
        <displayFormat>QUL-{0}</displayFormat>
        <label>Quote Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Business_Category__c</fullName>
        <label>Business Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Business_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_SO__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In_Progress</fullName>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Partially_Allocated</fullName>
                    <label>Partially Allocated</label>
                </value>
                <value>
                    <fullName>Allocated</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Sales Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Quote</label>
        <referenceTo>inscor__Customer_Quote__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Winning_Probablity__c</fullName>
        <label>Winning Probablity(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/OpportunityUtility.cls
public class OpportunityUtility {
    Public static Decimal ProbablityPartMultiplier = 75;
    Public static Decimal ProbablityConversionMultiplier = 25;

    
    public static void calculateOpportunityProbablity(Set<String> accIds){
        System.debug('OpportunityUtility.calculateOpportunityProbablity.accIds:' + accIds);
        
        List<inscor__Customer_Quote__c> customerQuotes = [Select Id,inscor__Customer__c,inscor__Status__c,
                                                          (Select Id,inscor__Quantity__c,inscor__Business_Category__c from inscor__Customer_Quote_Lines__r LIMIT 200),
                                                          (Select Id,Winning_Probablity__c,accountId,Customer_Quote__c from Opportunities__r)
                                                          FROM inscor__Customer_Quote__c 
                                                          WHERE inscor__Customer__c IN : accIds AND CreatedDate = LAST_N_DAYS:30 AND inscor__Status__c = 'Closed - Won'];
        if (!customerQuotes.isEmpty()) {
            List<Opportunity> oppList = new List<Opportunity>();
            Map<Id,Decimal> accConvertionMap = new Map<Id,Decimal>();
            Map<Id, Integer> noOfCustomreQuotesByAccountId = new Map<Id, Integer>();
            for (AggregateResult result : [SELECT COUNT(Id) noOfQuotes, inscor__Customer__c accountId FROM inscor__Customer_Quote__c 
                                            WHERE inscor__Customer__c IN :accIds AND CreatedDate = LAST_N_DAYS:30
                                            GROUP BY inscor__Customer__c]) {
                noOfCustomreQuotesByAccountId.put((Id)result.get('accountId'), (Integer)result.get('noOfQuotes'));
            }
    
            for (AggregateResult result : [SELECT COUNT(Id) noOfSalesOrders, inscor__Customer__c accountId FROM inscor__Sales_Order__c 
                                            WHERE inscor__Customer__c IN :accIds AND CreatedDate = LAST_N_DAYS:30
                                            GROUP BY inscor__Customer__c]) {
                Id accountId = (Id)result.get('accountId');
                Decimal quoteCount = noOfCustomreQuotesByAccountId.containsKey(accountId) ? noOfCustomreQuotesByAccountId.get(accountId) : 0;
                Decimal salesCount = (Integer)result.get('noOfSalesOrders');
                if (quoteCount != 0) {
                    accConvertionMap.put(accountId, ((salesCount/quoteCount) * ProbablityConversionMultiplier));
                }
                System.debug(accConvertionMap);
            }
    
            for(inscor__Customer_Quote__c quoteRec : customerQuotes){
                Decimal categoryParts = 0;
                Decimal totalParts = 0;
                if(quoteRec.inscor__Customer_Quote_Lines__r.size() > 0){
                    for(inscor__Customer_Quote_Line__c quoteLine : quoteRec.inscor__Customer_Quote_Lines__r){
                        if(quoteLine.inscor__Business_Category__c != null && quoteLine.inscor__Quantity__c != null){
                            if(quoteLine.inscor__Business_Category__c == 'Surplus'){
                                categoryParts += quoteLine.inscor__Quantity__c * 1;
                            }else if(quoteLine.inscor__Business_Category__c == 'Distribution'){
                                categoryParts += quoteLine.inscor__Quantity__c * 0.7;
                            }else if(quoteLine.inscor__Business_Category__c == 'Broker'){
                                categoryParts += quoteLine.inscor__Quantity__c * 0.4;
                            }
                            totalParts += quoteLine.inscor__Quantity__c;
                        }
                    } 
                    Decimal PartNumberValue = totalParts == 0 ? null :  ((categoryParts/totalParts) * ProbablityPartMultiplier);
                    System.debug('PartNumberValue:' + PartNumberValue);
                    for(Opportunity opp : quoteRec.Opportunities__r){
                        opp.Winning_Probablity__c = (PartNumberValue != null ? PartNumberValue : 0) + (accConvertionMap.containsKey(opp.AccountId) ? accConvertionMap.get(opp.AccountId) : 0);
                        opp.Winning_Probablity__c = opp.Winning_Probablity__c != null ? (opp.Winning_Probablity__c > 100 ? 100 : opp.Winning_Probablity__c) : 0;
                        if(opp.Winning_Probablity__c != 0)    oppList.add(opp);
                    }
                }else {
                    for(Opportunity opp : quoteRec.Opportunities__r){
                        opp.Winning_Probablity__c = 0 + (accConvertionMap.containsKey(opp.AccountId) ? accConvertionMap.get(opp.AccountId) : 0);
                        oppList.add(opp);
                    }
                }
            }
            if(oppList.size() > 0)    update oppList;
        }
    } 
}