src/objects/inscor__Customer_Quote__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_CQ__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Quotes</relationshipLabel>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Quote</label>
    <nameField>
        <displayFormat>QU-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Customer_Quote__c</fullName>
        <label>Customer Quote</label>
        <referenceTo>inscor__Customer_Quote__c</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer Quote Line</label>
    <nameField>
        <displayFormat>QUL-{0}</displayFormat>
        <label>Quote Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trigger_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Trigger Configuration will be used for maintaining trigger toggle for its execution.</description>
    <fields>
        <fullName>Customer_Quote_Line_Trigger_Disable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disable Customer Quote Line Trigger</description>
        <inlineHelpText>Disable Customer Quote Line Trigger</inlineHelpText>
        <label>Customer Quote Line Trigger Disable</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Configuration</label>
</CustomObject>

src/classes/CustomerQuoteLineTriggerHelper.cls
/**************************************************************************************************
Description: Trigger Helper class for inscor__Customer_Quote_Line__c that will handle all types of trigger events.
====================================================================================================
====================================================================================================
TestClass: CustomerQuoteLineTriggerHelperTest
Code Coverage: 100%
====================================================================================================
====================================================================================================
History
<Version>   	<Date>             <Author Name>                <Brief description of change > 
1.0 -      		05/22/2021		    Gourav Goyal				Initial Creation    
2.0 -      		10/28/2021		    Vinod Kumar Sharma		    Removed unUsed methods and Added method updateCustomerScoreOnAccount
***************************************************************************************************/
public class CustomerQuoteLineTriggerHelper implements TriggerHandler {
    
    /*Allows unit tests (or other code) to disable this trigger for the transaction */
    
    public static Boolean TriggerDisabled = false;
        
    public Boolean IsDisabled() {
        /*Use the option below if you set up Custom Settings to controll Triggers*/
        Trigger_Configuration__c configSetting = Trigger_Configuration__c.getInstance();   
        if(configSetting.Customer_Quote_Line_Trigger_Disable__c == true) {
            return true;
        } else {
            return TriggerDisabled;
        }
    }
    
    /* CALLING */
    public void BeforeInsert(SObject[] newList) {}
    
    public void BeforeUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {}
    
    public void BeforeDelete(Map<Id, SObject> oldMap) {}
    
    public void AfterInsert(Map<Id, SObject> newMap) {
        CustomerQuoteLineTriggerHelper.updateCustomerScoreOnAccount((List<inscor__Customer_Quote_Line__c>)newMap.values(), null);
    }
    
    public void AfterUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
        CustomerQuoteLineTriggerHelper.updateCustomerScoreOnAccount((List<inscor__Customer_Quote_Line__c>)newMap.values(), (Map<Id, inscor__Customer_Quote_Line__c>) oldMap);
    }
    
    public void AfterDelete(Map<Id, SObject> oldMap) {
        CustomerQuoteLineTriggerHelper.updateCustomerScoreOnAccount((List<inscor__Customer_Quote_Line__c>)oldMap.values(), null);
     }
    
    public void AfterUndelete(Map<Id, SObject> oldMap) {}

    public static void updateCustomerScoreOnAccount(List<inscor__Customer_Quote_Line__c> customerQuoteLines, Map<Id, inscor__Customer_Quote_Line__c> oldMap) {
        try {
            Set<String> customerQuoteIds = new Set<String>();
            if (oldMap != null) {
                for (inscor__Customer_Quote_Line__c orderLine : customerQuoteLines) {
                    if (orderLine.inscor__Quantity__c != oldMap.get(orderLine.Id).inscor__Quantity__c) {
                            customerQuoteIds.add(orderLine.inscor__Customer_Quote__c);
                    }
                }
            }else {
                for (inscor__Customer_Quote_Line__c orderLine : customerQuoteLines) {
                    customerQuoteIds.add(orderLine.inscor__Customer_Quote__c);
                }
            }
            if (!customerQuoteIds.isEmpty()) {
                Set<String> accountIds = new Set<String>();        
                for(inscor__Customer_Quote__c customerQuote : [SELECT inscor__Customer__c FROM inscor__Customer_Quote__c WHERE Id IN :customerQuoteIds]){
                    accountIds.add(customerQuote.inscor__Customer__c);
                }
                AccountUtility.updateCustomerQuoteOrderLineCount(accountIds);
                OpportunityUtility.calculateOpportunityProbablity(accountIds);
            }
        } catch (Exception error) {
            System.debug('error:' + error.getMessage());
            LogService.createErrorLog('CustomerQuoteLineTriggerHelper.apxc', NULL, error, NULL);
        }
    }
}