src/objects/inscor__Condition_Code__c.object
<CustomObject>
    <label>Condition Code</label>
    <nameField>
        <label>Condition Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contact must be associated with the selected customer.</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.inscor__Customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_CQ__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Quotes</relationshipLabel>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quote_Source__c</fullName>
        <label>Quote Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Quote_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Temp_Quote__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Temp Quote?</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Quote</label>
    <nameField>
        <displayFormat>QU-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Condition_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Core_Disposition__c</fullName>
        <label>Core Disposition</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Overhaul</fullName>
                </value>
                <value>
                    <fullName>Serviceable</fullName>
                </value>
                <value>
                    <fullName>Receive ‘As Is’</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Core_Due__c</fullName>
        <label>Core Due (In Days)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>inscor__Customer_Part_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Customer_Quote_Lines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Customer_Quote__c</fullName>
        <label>Customer Quote</label>
        <referenceTo>inscor__Customer_Quote__c</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Exchange_Type__c</fullName>
        <label>Exchange Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Exchange_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Outright_Price__c</fullName>
        <label>Outright Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>inscor__Quote_Type__c</fullName>
        <label>Quote Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Outright</fullName>
                    <default>true</default>
                    <label>Outright</label>
                </value>
                <value>
                    <fullName>Exchange</fullName>
                </value>
                <value>
                    <fullName>No Quote</fullName>
                </value>
                <value>
                    <fullName>Managed Repair</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Stock_Disposition__c</fullName>
        <label>Stock Disposition</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Return to Stock</fullName>
                </value>
                <value>
                    <fullName>Return to Exchange Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Quote Line</label>
    <nameField>
        <displayFormat>QUL-{0}</displayFormat>
        <label>Quote Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateCustomerQuoteAndItsLine.cls
@RestResource(urlMapping='/CreateCQ/*') 
global class CreateCustomerQuoteAndItsLine {
  @HttpPost
    global static void doPost(){
        try{
            RestRequest req = RestContext.request;
            String jsonBody = '';
            If(test.isRunningTest()){
                jsonBody = '{"Quote":{"attributes":{"type":"inscor__Customer_Quote__c"},"inscor__Customer__c":"0016s00000OZT47AAH","inscor__Temp_Quote__c":true,"inscor__Quote_Source__c":"Storefront"},"QuoteLine":[{"attributes":{"type":"inscor__Customer_Quote_Line__c"},"inscor__Customer_Quote__c":null,"inscor__Customer_Part_Number__c":"01t6s000000zBxKAAU","inscor__Product__c":"01t6s000000zBxKAAU","inscor__Condition_Code__c":"a096s000000e2dHAAQ","inscor__Quote_Type__c":"Outright","inscor__Quantity__c":2}]}';
            } else {
                jsonBody = req.requestBody.toString();
            }
            //jsonBody = req.requestBody.toString();
            System.debug('jsonBody -> '+jsonBody);
            Map<String,Object> productList = (Map<String,Object>)JSON.deserializeUntyped(jsonBody);
            Map<String,Object> quoteMap = (Map<String,Object>)productList.get('Quote');
            inscor__Customer_Quote__c customerQuote = new inscor__Customer_Quote__c();
            customerQuote.inscor__Customer__c = (String)quoteMap.get('inscor__Customer__c');
            customerQuote.inscor__Temp_Quote__c = (Boolean)quoteMap.get('inscor__Temp_Quote__c');
            customerQuote.inscor__Quote_Source__c = 'Storefront';
            customerQuote.OwnerId = (String)quoteMap.get('OwnerId');
            customerQuote.inscor__Contact__c = (String)quoteMap.get('inscor__Contact__c');
            customerQuote.inscor__Assigned_To__c = (String)quoteMap.get('inscor__Assigned_To__c');
            //customerQuote = (inscor__Customer_Quote__c)productList.get('Quote');
            If(!test.isRunningTest()){
                insert customerQuote;
            }
            
            System.debug('customerQuote -> '+customerQuote);
            
            List<inscor__Customer_Quote_Line__c> quoteLineList = new List<inscor__Customer_Quote_Line__c>(); 
            
            List<Object> lineList =(List<Object>)productList.get('QuoteLine'); 
            for(Object eachLine : lineList){  
                Map<String,Object> quoteLineMap = (Map<String,Object>)eachLine;
                inscor__Customer_Quote_Line__c quoteLine = new inscor__Customer_Quote_Line__c();
                quoteLine.inscor__Customer_Quote__c = customerQuote.Id;
                
                quoteLine.inscor__Customer_Part_Number__c = (String)quoteLineMap.get('inscor__Customer_Part_Number__c');
                quoteLine.inscor__Product__c = (String)quoteLineMap.get('inscor__Product__c');            
                quoteLine.inscor__Condition_Code__c = (String)quoteLineMap.get('inscor__Condition_Code__c');
                
                quoteLine.inscor__Quote_Type__c = (String)quoteLineMap.get('inscor__Quote_Type__c');
                quoteLine.inscor__Exchange_Type__c = (String)quoteLineMap.get('inscor__Exchange_Type__c');
                quoteLine.inscor__Outright_Price__c = (Decimal)quoteLineMap.get('inscor__Outright_Price__c');
                quoteLine.inscor__Core_Due__c = (Decimal)quoteLineMap.get('inscor__Core_Due__c');
                quoteLine.inscor__Core_Disposition__c = (String)quoteLineMap.get('inscor__Core_Disposition__c');
                quoteLine.inscor__Stock_Disposition__c = (String)quoteLineMap.get('inscor__Stock_Disposition__c');
                
                quoteLine.inscor__Quantity__c = (Decimal)quoteLineMap.get('inscor__Quantity__c');
                quoteLineList.add(quoteLine);
            }
            
            if(!quoteLineList.isEmpty()){
                insert quoteLineList;
                System.debug('quoteLineList -> '+quoteLineList.size());
            }
        }catch(exception e){
            System.debug('Error '+e.getLineNumber());
            System.debug('Error '+e.getMessage());
            //return 'Something went wrong '+e.getMessage();
        }
    } 
}