src/objects/inscor__Company__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Address_1__c</fullName>
        <label>Address 1</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Company_Name__c</fullName>
        <label>Company Name</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>inscor__Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Company</label>
    <nameField>
        <displayFormat>CID-{0}</displayFormat>
        <label>Company ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Form_Options__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>inscor__Company__c</referenceTo>
        <relationshipLabel>Form Options</relationshipLabel>
        <relationshipName>Form_Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Footer__c</fullName>
        <label>Footer</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Form Options</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Invoice__c.object
<CustomObject>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>inscor__Company__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INVC-{0}</displayFormat>
        <label>Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>inscor__Invoice__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>ILID-{0}</displayFormat>
        <label>Invoice Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InvoicePDFSaveAsFileControllerTest.cls
@isTest
public class InvoicePDFSaveAsFileControllerTest {
    @testSetup static void setupData() {
		inscor__Invoice__c invoiceInstance = new inscor__Invoice__c();
        invoiceInstance.inscor__City__c = 'Jaipur';
        insert invoiceInstance;
        
        inscor__Invoice_Line__c invoiceLineInstance= new inscor__Invoice_Line__c();
        invoiceLineInstance.inscor__Invoice__c = invoiceInstance.Id;
        insert invoiceLineInstance;
        
        inscor__Company__c companyInstance = new inscor__Company__c();
        companyInstance.inscor__Company_Name__c = 'inscor Company' ;
        companyInstance.inscor__Address_1__c = 'address';
        companyInstance.inscor__City__c = 'xyz';
        companyInstance.inscor__Zip_Code__c = '21321';
        insert companyInstance;
        
        inscor__Form_Options__c formOption = new inscor__Form_Options__c();
        formOption.name = 'Invoice';
        formOption.inscor__Footer__c = 'test footer';
        formOption.inscor__Company__c = companyInstance.Id;
        insert formOption;
	}
    
    @isTest 
    static void insertRecord(){
    	
        List<inscor__Invoice__c> invoices = [SELECT Id FROM inscor__Invoice__c];
        System.debug('invoices->' + invoices);
        Test.startTest();
        	PageReference testPage = Page.InvoicePDFSaveAsFile; 
           Test.setCurrentPage(testPage);
           testPage.getParameters().put('Id', invoices[0].Id);
        
           ApexPages.StandardController sc = new  ApexPages.StandardController(invoices[0]);
        try{
           InvoicePDFSaveAsFileController ext = new InvoicePDFSaveAsFileController(sc);
        }catch(Exception e){
            System.debug(e);
        }         
       
         Test.stopTest();
    }
}