src/objects/inscor__Condition_Code__c.object
<CustomObject>
    <label>Condition Code</label>
    <nameField>
        <label>Condition Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_CQ__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Quotes</relationshipLabel>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quote_Source__c</fullName>
        <label>Quote Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Quote_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Temp_Quote__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Temp Quote?</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Quote</label>
    <nameField>
        <displayFormat>QU-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Condition_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Customer_Part_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Customer_Quote_Lines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Customer_Quote__c</fullName>
        <label>Customer Quote</label>
        <referenceTo>inscor__Customer_Quote__c</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>inscor__Quote_Type__c</fullName>
        <label>Quote Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Outright</fullName>
                    <default>true</default>
                    <label>Outright</label>
                </value>
                <value>
                    <fullName>Exchange</fullName>
                </value>
                <value>
                    <fullName>No Quote</fullName>
                </value>
                <value>
                    <fullName>Managed Repair</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Quote Line</label>
    <nameField>
        <displayFormat>QUL-{0}</displayFormat>
        <label>Quote Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CustomerquoteTestcontroller.cls
@isTest
global class CustomerquoteTestcontroller implements HttpCalloutMock {
    global HTTPResponse respond(HTTPRequest request) {
        HttpResponse response = new HttpResponse();
        if(request.getEndpoint() == 'https://test.salesforce.com'){
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{"access_token":"test","instance_url":"https://test.salesforce.com"}');
            response.setStatusCode(200);
        } else if(request.getEndpoint() == 'https://test.salesforce.com/services/apexrest/CreateCQ/'){
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{"Quote":{"attributes":{"type":"inscor__Customer_Quote__c"},"inscor__Customer__c":"0016s00000OZT47AAH","inscor__Temp_Quote__c":true,"inscor__Quote_Source__c":"Storefront"},"QuoteLine":[{"attributes":{"type":"inscor__Customer_Quote_Line__c"},"inscor__Customer_Quote__c":null,"inscor__Customer_Part_Number__c":"01t6s000000zBxKAAU","inscor__Product__c":"01t6s000000zBxKAAU","inscor__Condition_Code__c":"a096s000000e2dHAAQ","inscor__Quote_Type__c":"Outright","inscor__Quantity__c":2}]}');
            response.setStatusCode(200);
        }
        else if(request.getEndpoint() == 'https://test.salesforce.com/services/apexrest/CreateSO/'){
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{"OrderId":'+JSON.serialize('8016s000000KNHUAA4')+'}');
            response.setStatusCode(200);
        }
        return response; 
    }

}