src/objects/inscor__Customer_Quote__c.object
<CustomObject>
    <fields>
        <fullName>Lost_Reason__c</fullName>
        <label>Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Wrong price</fullName>
                </value>
                <value>
                    <fullName>High Price</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Closed - Won</fullName>
                </value>
                <value>
                    <fullName>Closed - Lost</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Quote</label>
    <nameField>
        <displayFormat>QU-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProcessQuoteStatusBatch.cls
global class ProcessQuoteStatusBatch implements Database.Batchable<sObject>, Schedulable {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query;
        if(Test.isRunningTest()){
            query = 'SELECT Id, Name,inscor__Status__c, Lost_Reason__c FROM inscor__Customer_Quote__c where  LastModifiedDate = Today';
        } else {
           query = 'SELECT Id, Name,inscor__Status__c, Lost_Reason__c FROM inscor__Customer_Quote__c where  LastModifiedDate < LAST_N_DAYS:30'; 
        }
        return Database.getQueryLocator(query);
    }
     
    global void execute(Database.BatchableContext BC, List<inscor__Customer_Quote__c> scope) {
        
        for(inscor__Customer_Quote__c quoteRec : scope){
            quoteRec.Lost_Reason__c = 'High Price';
            quoteRec.inscor__Status__c = 'Closed - Lost';
        }
        
        if(scope.size() > 0){
            update scope;
        }
         
    }   
     
    global void finish(Database.BatchableContext BC) {
        
    }
    
    global void execute(SchedulableContext sc) {
       
      Database.executeBatch(new ProcessQuoteStatusBatch());
   }
}