src/objects/inscor__Condition_Code__c.object
<CustomObject>
    <label>Condition Code</label>
    <nameField>
        <label>Condition Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Inventory_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Condition_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <referenceTo>inscor__Inventory_Location__c</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Owner_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Owner Code</label>
        <referenceTo>inscor__Owner_Code__c</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity_on_Exchange__c</fullName>
        <label>Quantity on Exchange</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity_on_Repair__c</fullName>
        <label>Quantity on Repair</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>inscor__Serial_Number__c</fullName>
        <label>Serial Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Warehouse__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Warehouse</label>
        <referenceTo>inscor__Warehouse__c</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INV-{0}</displayFormat>
        <label>Inventory UID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Inventory_Location__c.object
<CustomObject>
    <label>Inventory Location</label>
    <nameField>
        <label>Inventory Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Owner_Code__c.object
<CustomObject>
    <label>Owner Code</label>
    <nameField>
        <label>Owner Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Owner Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Warehouse__c.object
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InventoryWithoutFilesCtrl.cls
/**************************************************************************************************
Description: class used to get report for most part number for customer quotes
====================================================================================================
====================================================================================================
Class: InventoryWithoutFilesCtrl
====================================================================================================
====================================================================================================
History
<Version>       <Date>             <Author Name>                <Brief description of change > 
1.0 -           10/03/2021        Gourav Goyal                      Initial Creation    
***************************************************************************************************/
public class InventoryWithoutFilesCtrl {
    
    //@AuraEnabled(cacheable=true) 
    @AuraEnabled
    public static List<ReportWrapper> getInventoryResults(){
        List<ReportWrapper> reportWrappers = getInventoryResultsHelper();
        return reportWrappers;
    }

    @AuraEnabled
    public static List<ReportWrapper> getInventoryResultsBySearch(String searchKey){
        List<ReportWrapper> reportWrappers = getInventoryResultsHelperBySearchKey(searchKey + '%');
        return reportWrappers;
    }
    
    public static List<ReportWrapper> getInventoryResultsHelper(){
        List<ReportWrapper> reportWrappers = new List<ReportWrapper>();
        for(inscor__Inventory_Line__c result : [SELECT Id, Name, inscor__Condition_Code__r.Name, inscor__Warehouse__r.Name,
                                                inscor__Owner_Code__r.Name, inscor__Serial_Number__c, inscor__Location__r.Name,
                                                inscor__Quantity__c, inscor__Quantity_on_Repair__c, inscor__Quantity_on_Exchange__c,
                                                (SELECT Id from AttachedContentDocuments limit 1) FROM inscor__Inventory_Line__c
                                                WHERE inscor__Quantity__c > 0 AND CreatedDate = LAST_N_DAYS:365 limit 500]){
                                                    if(result.AttachedContentDocuments.size() == 0){
                                                        ReportWrapper reportWrapper = new ReportWrapper();
                                                        reportWrapper.name = String.valueOf(result.name);
                                                        reportWrapper.nameUrl = '/' + result.Id;
                                                        reportWrapper.conditionCode = String.valueOf(result.inscor__Condition_Code__r.Name);
                                                        reportWrapper.warehouse =  String.valueOf(result.inscor__Warehouse__r.Name);
                                                        reportWrapper.ownerCode = String.valueOf(result.inscor__Owner_Code__r.Name);
                                                        reportWrapper.serialNumber = String.valueOf(result.inscor__Serial_Number__c);
                                                        reportWrapper.location = String.valueOf(result.inscor__Location__r.Name);
                                                        reportWrapper.quantity = result.inscor__Quantity__c != null ? Integer.valueOf(result.inscor__Quantity__c) : 0;
                                                        reportWrapper.quantityOnRepair = result.inscor__Quantity_on_Repair__c != null ? Integer.valueOf(result.inscor__Quantity_on_Repair__c) : 0;
                                                        reportWrapper.quantityOnExchange = result.inscor__Quantity_on_Exchange__c != null ? Integer.valueOf(result.inscor__Quantity_on_Exchange__c) : 0;
                                                        reportWrappers.add(reportWrapper);
                                                        
                                                    }                    
                                                    
                                                }
        return reportWrappers;
        
    }

    public static List<ReportWrapper> getInventoryResultsHelperBySearchKey(String searchKey){
        List<ReportWrapper> reportWrappers = new List<ReportWrapper>();
        for(inscor__Inventory_Line__c result : [SELECT Id, Name, inscor__Condition_Code__r.Name, inscor__Warehouse__r.Name,
                                                inscor__Owner_Code__r.Name, inscor__Serial_Number__c, inscor__Location__r.Name,
                                                inscor__Quantity__c, inscor__Quantity_on_Repair__c, inscor__Quantity_on_Exchange__c,
                                                (SELECT Id from AttachedContentDocuments limit 1) FROM inscor__Inventory_Line__c
                                                WHERE inscor__Location__r.Name LIKE :searchKey AND CreatedDate = LAST_N_DAYS:365 limit 200]){
                                                    if(result.AttachedContentDocuments.size() == 0){
                                                        ReportWrapper reportWrapper = new ReportWrapper();
                                                        reportWrapper.name = String.valueOf(result.name);
                                                        reportWrapper.nameUrl = '/' + result.Id;
                                                        reportWrapper.conditionCode = String.valueOf(result.inscor__Condition_Code__r.Name);
                                                        reportWrapper.warehouse =  String.valueOf(result.inscor__Warehouse__r.Name);
                                                        reportWrapper.ownerCode = String.valueOf(result.inscor__Owner_Code__r.Name);
                                                        reportWrapper.serialNumber = String.valueOf(result.inscor__Serial_Number__c);
                                                        reportWrapper.location = String.valueOf(result.inscor__Location__r.Name);
                                                        reportWrapper.quantity = result.inscor__Quantity__c != null ? Integer.valueOf(result.inscor__Quantity__c) : 0;
                                                        reportWrapper.quantityOnRepair = result.inscor__Quantity_on_Repair__c != null ? Integer.valueOf(result.inscor__Quantity_on_Repair__c) : 0;
                                                        reportWrapper.quantityOnExchange = result.inscor__Quantity_on_Exchange__c != null ? Integer.valueOf(result.inscor__Quantity_on_Exchange__c) : 0;
                                                        reportWrappers.add(reportWrapper);
                                                        
                                                    }                    
                                                    
                                                }
        return reportWrappers;
        
    }
    
    public class ReportWrapper{
        @AuraEnabled public String name;
        @AuraEnabled public String nameUrl;
        @AuraEnabled public String conditionCode;
        @AuraEnabled public String warehouse;
        @AuraEnabled public String ownerCode;
        @AuraEnabled public String serialNumber;
        @AuraEnabled public String location;
        @AuraEnabled public Integer quantity;
        @AuraEnabled public Integer quantityOnRepair;
        @AuraEnabled public Integer quantityOnExchange;
    }
}