src/objects/inscor__Condition_Code__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Description__c</fullName>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Condition Code</label>
    <nameField>
        <label>Condition Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contact must be associated with the selected customer.</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.inscor__Customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Create_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Create Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_CQ__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Quotes</relationshipLabel>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quote_Total__c</fullName>
        <label>Quote Total</label>
        <summarizedField>inscor__Customer_Quote_Line__c.inscor__Line_Total__c</summarizedField>
        <summaryForeignKey>inscor__Customer_Quote_Line__c.inscor__Customer_Quote__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Closed - Won</fullName>
                </value>
                <value>
                    <fullName>Closed - Lost</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Quote</label>
    <nameField>
        <displayFormat>QU-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Condition_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Create_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Create Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>inscor__Customer_Quote__c</fullName>
        <label>Customer Quote</label>
        <referenceTo>inscor__Customer_Quote__c</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Line_Total__c</fullName>
        <formula>inscor__Quantity__c *  inscor__Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Part_Number_UOM__c</fullName>
        <formula>TEXT( inscor__Product__r.inscor__UOM__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Part Number UOM</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>inscor__Quote_Type__c</fullName>
        <label>Quote Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Outright</fullName>
                    <default>true</default>
                    <label>Outright</label>
                </value>
                <value>
                    <fullName>Exchange</fullName>
                </value>
                <value>
                    <fullName>No Quote</fullName>
                </value>
                <value>
                    <fullName>Managed Repair</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Ready to Quote</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Queued to Quote</fullName>
                </value>
                <value>
                    <fullName>Quoted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Quote Line</label>
    <nameField>
        <displayFormat>QUL-{0}</displayFormat>
        <label>Quote Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Price__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Condition_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipLabel>Prices</relationshipLabel>
        <relationshipName>Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Price Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>inscor__Create_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Create Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>inscor__Description__c</fullName>
        <label>Description</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unverified</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QuotesHistoryController.cls
/**
 * @author - Keykloud
 * @description - Class created for the lwc component name as quoteHistory
 * @TestClass - pending
 * @createdDate - 12/17/2021
 * @lastModifiedDate - 12/22/2021
 * @lastModifiedBy - KeyKloud
 */
public without sharing class QuotesHistoryController {

    
    @AuraEnabled(cacheable=true)
    public static List<QuotesHistoryWrapper> getCustomerQuote(){

        List<QuotesHistoryWrapper> quotesHistoryWrapperList = new List<QuotesHistoryWrapper>();
        User usr = getLoggedInUser();
        if (usr.Contact.Is_Super_User__c && usr.Contact.AccountId != null) {
            List<inscor__Customer_Quote__c> quotes = [SELECT id, Name, inscor__Quote_Total__c, inscor__Create_Date__c, inscor__Status__c, 
                            inscor__Contact__c, inscor__Contact__r.Name 
                            FROM inscor__Customer_Quote__c WHERE  inscor__Customer__c = :usr.Contact.AccountId ORDER BY inscor__Create_Date__c DESC LIMIT 10000];
            for(inscor__Customer_Quote__c quote : quotes){
                quotesHistoryWrapperList.add(createQuoteHistoryWrapper(quote));
            }
        }else if (!usr.Contact.Is_Super_User__c && usr.ContactId != null) {
            List<inscor__Customer_Quote__c> quotes = [SELECT id, Name, inscor__Quote_Total__c, inscor__Create_Date__c, inscor__Status__c, 
                            inscor__Contact__c, inscor__Contact__r.Name 
                            FROM inscor__Customer_Quote__c WHERE  inscor__Contact__c = :usr.ContactId ORDER BY inscor__Create_Date__c DESC LIMIT 10000];

            for(inscor__Customer_Quote__c quote : quotes){
                quotesHistoryWrapperList.add(createQuoteHistoryWrapper(quote));
            }
        }
        return quotesHistoryWrapperList;
    }

    @AuraEnabled
    public static List<QuotesHistoryWrapper> getQuotesBySearch(string quoteName, string quoteAmount, string quoteDate, string quoteType, string status, string partNumber){
        try {
            Decimal quoteAmountDecimal = (quoteAmount != null && quoteAmount != '') ? decimal.valueOf(quoteAmount) : null;
            Date cDate = (quoteDate != null && quoteDate != '') ? Date.valueOf(quoteDate) : null;
            quoteName = (quoteName != null && quoteName != '') ? quoteName + '%' : null;
            List<QuotesHistoryWrapper> quotesHistoryWrapperList = new List<QuotesHistoryWrapper>();
            String query = 'SELECT id, Name, inscor__Quote_Total__c, inscor__Create_Date__c, inscor__Status__c, inscor__Contact__c, inscor__Contact__r.Name ';
            query += 'FROM inscor__Customer_Quote__c ';
            query += 'WHERE';
            User usr = getLoggedInUser();
            String customerId = usr.Contact.AccountId;
            String contactId = usr.ContactId;
            if (contactId != null ) {
                if (usr.Contact.Is_Super_User__c) {
                    query += ' inscor__Customer__c = :customerId AND';
                }else {
                    query += ' inscor__Contact__c = :contactId AND';
                }
                // Boolean isConditionAdded = false;
                if (quoteName != null &&  quoteName != '') {
                    query += ' Name LIKE :quoteName AND';
                    // isConditionAdded = true;
                }
                if (quoteAmountDecimal != null) {
                    query += ' inscor__Quote_Total__c =:quoteAmountDecimal AND';
                    // isConditionAdded = true;
                }
                if (status != null &&  status != '') {
                    query += ' inscor__Status__c =:status AND';
                    // isConditionAdded = true;
                }
                if (cDate != null) {
                    query += ' DAY_ONLY(inscor__Create_Date__c) =: cDate AND';
                    // isConditionAdded = true;
                }
                if (partNumber != null &&  partNumber != '') {
                    query += ' Id IN (SELECT inscor__Customer_Quote__c FROM inscor__Customer_Quote_Line__c WHERE inscor__Product__r.Name =:partNumber ';
                    if (quoteType != null) {
                        query += 'AND inscor__Quote_Type__c =: quoteType';
                    }
                    query +=') ';
                    // isConditionAdded = true;
                }else if (quoteType != null) {
                    query += ' Id IN (SELECT inscor__Customer_Quote__c FROM inscor__Customer_Quote_Line__c WHERE inscor__Quote_Type__c =: quoteType) ';
                    // isConditionAdded = true;
                }
    
                query = query.removeEnd('AND');
                query+= ' ORDER BY inscor__Create_Date__c DESC LIMIT 10000';
    
                System.debug(query);
    
                List<inscor__Customer_Quote__c> quotes = Database.Query(query);
                system.debug('quotes >> '+ quotes);
                for(inscor__Customer_Quote__c quote : quotes){
                    system.debug('inside for loop >>');
                    quotesHistoryWrapperList.add(createQuoteHistoryWrapper(quote));
                }
            }
                                                            
            return quotesHistoryWrapperList;
        } catch (Exception e) {
            System.debug(e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<QuoteLineWrapper> getQuoteLinesById(String quoteId){
        try {
            List<QuoteLineWrapper> quoteLineWrappers = new List<QuoteLineWrapper>();
            Integer count = 1;
            for(inscor__Customer_Quote_Line__c lineItem : [SELECT id, inscor__Product__r.Name, inscor__Product__r.inscor__Description__c, inscor__Condition_Code__r.Name, 
                            inscor__Quantity__c, inscor__Part_Number_UOM__c, inscor__Price__c, inscor__Line_Total__c 
                            FROM inscor__Customer_Quote_Line__c 
                            WHERE inscor__Customer_Quote__c =:quoteId]){
                quoteLineWrappers.add(createQuoteLineWrapper(lineItem, count));
                count++;
            }
            return quoteLineWrappers;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    /**
     * @description : method used to create instance of quote History wrapper as per customer quote
     * @createdDate : 12.20.2021
     */
    public static QuotesHistoryWrapper createQuoteHistoryWrapper(inscor__Customer_Quote__c quote) {
        QuotesHistoryWrapper QuotesHistoryWrapperInstance = new QuotesHistoryWrapper();
        QuotesHistoryWrapperInstance.id = quote.Id;
        QuotesHistoryWrapperInstance.quoteType = ''; //customerQuoteLine.inscor__Quote_Type__c;
        QuotesHistoryWrapperInstance.quoteNumber = quote.Name;
        QuotesHistoryWrapperInstance.quoteAmount = quote.inscor__Quote_Total__c == null ? 0 : quote.inscor__Quote_Total__c;
        QuotesHistoryWrapperInstance.quoteDate = quote.inscor__Create_Date__c;
        QuotesHistoryWrapperInstance.status = quote.inscor__Status__c;
        QuotesHistoryWrapperInstance.contactName = quote.inscor__Contact__r.Name == null ? '-' : quote.inscor__Contact__r.Name;
        QuotesHistoryWrapperInstance.isShowLines = false;

        return QuotesHistoryWrapperInstance;
    }

    /**
     * @description : method used to create instance of quote line wrapper as per customer quote line
     * @createdDate : 12.20.2021
     */
    public static QuoteLineWrapper createQuoteLineWrapper(inscor__Customer_Quote_Line__c lineItem, Integer count) {
        QuoteLineWrapper lineWrapper = new QuoteLineWrapper();
        lineWrapper.rowNumber = count;
        lineWrapper.partNumber = lineItem.inscor__Product__r.Name == null ? '-' : lineItem.inscor__Product__r.Name;
        lineWrapper.description = lineItem.inscor__Product__r.inscor__Description__c == null ? '-' : lineItem.inscor__Product__r.inscor__Description__c;
        lineWrapper.conditionCode = lineItem.inscor__Condition_Code__r.Name == null ? '-' : lineItem.inscor__Condition_Code__r.Name;
        lineWrapper.orderQty = lineItem.inscor__Quantity__c == null ? 0 : lineItem.inscor__Quantity__c;
        lineWrapper.shipQty = '';
        lineWrapper.um = lineItem.inscor__Part_Number_UOM__c == null ?  '-' : lineItem.inscor__Part_Number_UOM__c;
        lineWrapper.price = lineItem.inscor__Price__c == null ? 0 : lineItem.inscor__Price__c;
        lineWrapper.total = lineItem.inscor__Line_Total__c;
        return lineWrapper;
    }

    @AuraEnabled(cacheable=true)
    public static List<String> getPickListValueHelper(String objectType, String selectedField){
        List<String> picklistValues = new List<String>();
        Schema.SObjectType sObjectType = Schema.getGlobalDescribe().get(objectType);
        Schema.DescribeSObjectResult sObjectResult = sObjectType.getDescribe();
        Schema.DescribeFieldResult fieldResult = sObjectResult.fields.getMap().get(selectedField).getDescribe();
        List<Schema.PicklistEntry> picklistEntries = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListEntry : picklistEntries){
            picklistValues.add(pickListEntry.getLabel());
        }     
        return picklistValues;
    }

    @AuraEnabled
    public static Picklist getPicklistValueWrapper(){
        try {
            Picklist pickList = new Picklist();
            pickList.quoteTypes = getPickListValueHelper('inscor__Customer_Quote_Line__c', 'inscor__Quote_Type__c');
            pickList.status = getPickListValueHelper('inscor__Customer_Quote__c', 'inscor__Status__c');
            return pickList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    private static User getLoggedInUser() {
        Id userId = UserInfo.getUserId();
        User usr = [SELECT Id, ContactId, Contact.AccountId, Contact.Is_Super_User__c FROM User WHERE Id = :userId];
        return usr;
    }



    public class QuotesHistoryWrapper{
        @AuraEnabled public String id {get; set;}
        @AuraEnabled public String quoteNumber {get; set;}
        @AuraEnabled public Decimal quoteAmount {get; set;}
        @AuraEnabled public DateTime quoteDate {get; set;}
        @AuraEnabled public String quoteType {get; set;}
        @AuraEnabled public String status {get; set;}
        @AuraEnabled public String contactName {get; set;}
        @AuraEnabled public Boolean isShowLines {get; set;}
    }

    public class QuoteLineWrapper{
        @AuraEnabled public Integer rowNumber{get;set;}
        @AuraEnabled public string partNumber{get;set;}
        @AuraEnabled public string description{get;set;}
        @AuraEnabled public string conditionCode{get;set;}
        @AuraEnabled public Decimal orderQty{get;set;}
        @AuraEnabled public string shipQty{get;set;}
        @AuraEnabled public string um{get;set;}
        @AuraEnabled public Decimal price{get;set;}
        @AuraEnabled public Decimal total{get;set;}
    }

    public class Picklist{
        @AuraEnabled public List<String> status{get;set;}
        @AuraEnabled public List<String> quoteTypes{get;set;}
    }

}