src/objects/inscor__Customer_Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <formula>inscor__Product__r.inscor__Keyword__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Keyword</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>inscor__Quote_Type__c</fullName>
        <label>Quote Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Outright</fullName>
                    <default>true</default>
                    <label>Outright</label>
                </value>
                <value>
                    <fullName>Exchange</fullName>
                </value>
                <value>
                    <fullName>No Quote</fullName>
                </value>
                <value>
                    <fullName>Managed Repair</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Quote Line</label>
    <nameField>
        <displayFormat>QUL-{0}</displayFormat>
        <label>Quote Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/inscor__Price__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Price Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <formula>inscor__Product__r.inscor__Keyword__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Keyword</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Order_Type__c</fullName>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Outright</fullName>
                    <default>true</default>
                    <label>Outright</label>
                </value>
                <value>
                    <fullName>Exchange</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Send Repaired</fullName>
                </value>
                <value>
                    <fullName>Return Core</fullName>
                </value>
                <value>
                    <fullName>Return Part</fullName>
                </value>
                <value>
                    <fullName>Core Repair</fullName>
                </value>
                <value>
                    <fullName>Managed Repair</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity_Ordered__c</fullName>
        <label>Quantity Ordered</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{0}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <label>Keyword</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reports_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Minimum_No_of_Orders__c</fullName>
        <label>Minimum No. of Orders</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_No_of_Quotes__c</fullName>
        <label>Minimum No. of Quotes</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Reports Configuration</label>
</CustomObject>

src/classes/customerQuoteReportByPartNameCtrl.cls
/**************************************************************************************************
Description: class used to get report for most part number for customer quotes
====================================================================================================
====================================================================================================
Class: customerQuoteReportByPartNameCtrl
====================================================================================================
====================================================================================================
History
<Version>   	<Date>             <Author Name>                <Brief description of change > 
1.0 -      		09/23/2021		  Vinod Kumar Sharma				Initial Creation    
***************************************************************************************************/
public  class customerQuoteReportByPartNameCtrl {

    public static Reports_Configuration__c configurationValues = Reports_Configuration__c.getInstance();
    
    @AuraEnabled(cacheable=true) 
    public static List<ReportWrapper> getQuoteReportResults(){
        List<ReportWrapper> reportWrappers = getQuoteResults();
        return reportWrappers;
    }
    
    @AuraEnabled(cacheable=true) 
    public static List<ReportWrapper> getOrderReportResults(){
        List<ReportWrapper> reportWrappers = getOrderResults();
        return reportWrappers;
    }
    
    public static List<ReportWrapper> getOrderResults(){
        Integer orderSize = 0;
        if(configurationValues.Minimum_No_of_Orders__c != null){
            orderSize = Integer.valueOf(configurationValues.Minimum_No_of_Orders__c);
        }
        
        List<ReportWrapper> reportWrappers = new List<ReportWrapper>();
        for(AggregateResult result : [SELECT COUNT(Id) numberOfOrders, inscor__Product__r.Name partName, inscor__Product__r.inscor__Keyword__c	keyword, 
                                        inscor__Order_Type__c orderType, AVG(inscor__Price__c) averagePrice, 
                                        AVG(inscor__Quantity_Ordered__c) averageQty, MAX(inscor__Quantity_Ordered__c) maxQty
                                        FROM inscor__Sales_Order_Line__c
                                        WHERE CreatedDate = LAST_N_DAYS:365 AND inscor__Product__r.Name != null
                                        GROUP BY inscor__Product__r.Name, inscor__Order_Type__c, inscor__Product__r.inscor__Keyword__c
                                        HAVING count(Id) > :orderSize 
                                      	ORDER BY COUNT(Id) desc limit 500]){
                                
            ReportWrapper reportWrapper = new ReportWrapper();
            reportWrapper.partNumber = (String)result.get('partName');
            reportWrapper.pnKeyword = (String)result.get('keyword');
            reportWrapper.totalQuotes = (Integer)result.get('numberOfOrders');
            reportWrapper.averagePrice =  (Decimal)result.get('averagePrice') != null ? ((Decimal)result.get('averagePrice')).round() : 0 ;
            reportWrapper.purchaseType = (String)result.get('orderType');
            reportWrapper.averageQty = (Decimal)result.get('averageQty') != null ? ((Decimal)result.get('averageQty')).round() : 0 ;
            reportWrapper.maxQty = (Decimal)result.get('maxQty') != null ? ((Decimal)result.get('maxQty')).round() : 0 ;
            reportWrappers.add(reportWrapper);
        }
        return reportWrappers;
        
    }
    
    
    public static List<ReportWrapper> getQuoteResults(){
        Integer quoteSize = 0;
        if(configurationValues.Minimum_No_of_Quotes__c != null){
            quoteSize = Integer.valueOf(configurationValues.Minimum_No_of_Quotes__c);
        }
        
        List<ReportWrapper> reportWrappers = new List<ReportWrapper>();
        for(AggregateResult result : [SELECT COUNT(Id) numberOfQuotes, inscor__Product__r.Name partName, inscor__Product__r.inscor__Keyword__c	keyword, 
                                        inscor__Quote_Type__c quoteType, AVG(inscor__Price__c) averagePrice, 
                                        AVG(inscor__Quantity__c) averageQty, MAX(inscor__Quantity__c) maxQty
                                        FROM inscor__Customer_Quote_Line__c
                                        WHERE CreatedDate = LAST_N_DAYS:365 AND inscor__Product__r.Name != null
                                        GROUP BY inscor__Product__r.Name, inscor__Quote_Type__c, inscor__Product__r.inscor__Keyword__c
                                        HAVING count(Id) > :quoteSize 
                                      	ORDER BY COUNT(Id) desc limit 500]){
                                
            ReportWrapper reportWrapper = new ReportWrapper();
            reportWrapper.partNumber = (String)result.get('partName');
            reportWrapper.pnKeyword = (String)result.get('keyword');
            reportWrapper.totalQuotes = (Integer)result.get('numberOfQuotes');
            reportWrapper.averagePrice =  (Decimal)result.get('averagePrice') != null ? ((Decimal)result.get('averagePrice')).round() : 0 ;
            reportWrapper.purchaseType = (String)result.get('quoteType');
            reportWrapper.averageQty = (Decimal)result.get('averageQty') != null ? ((Decimal)result.get('averageQty')).round() : 0 ;
            reportWrapper.maxQty = (Decimal)result.get('maxQty') != null ? ((Decimal)result.get('maxQty')).round() : 0 ;
            reportWrappers.add(reportWrapper);
        }
        return reportWrappers;
        
    }
    
    public class ReportWrapper{
        @AuraEnabled public String partNumber;
        @AuraEnabled public String pnKeyword;
        @AuraEnabled public Integer totalQuotes;
        @AuraEnabled public Decimal averagePrice;
        @AuraEnabled public String purchaseType;
        @AuraEnabled public Decimal averageQty;
        @AuraEnabled public Decimal maxQty;
    }
}