src/objects/inscor__Account_Ship_Address__c.object
<CustomObject>
    <fields>
        <fullName>Shipping__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Shipping?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>inscor__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Ship Addresses</relationshipLabel>
        <relationshipName>Account_Ship_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__State__c</fullName>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Street__c</fullName>
        <label>Street</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Account Ship Address</label>
    <nameField>
        <label>Account Ship Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Ship Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Condition_Code__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Show_in_Summary__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show in Summary</label>
        <type>Checkbox</type>
    </fields>
    <label>Condition Code</label>
    <nameField>
        <label>Condition Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Price__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Condition_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipLabel>Prices</relationshipLabel>
        <relationshipName>Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Price Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Authorize_Payment_Settlement__c</fullName>
        <label>Authorize Payment Settlement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Payment_Settlement_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>B2B Order #</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Paid_in_Full__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Paid in Full?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>inscor__Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.inscor__Customer__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.inscor__Dropship_Site__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.inscor__Dropship_Site__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.inscor__Dropship_Site__c</field>
                <operation>equals</operation>
                <valueField>Contact.inscor__Account_Shipping_Address__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Customer_PO_Number__c</fullName>
        <label>Customer PO Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_SO__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Internal_Comments_rt__c</fullName>
        <label>Internal Comments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>inscor__Order_Source__c</fullName>
        <label>Order Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                    <default>true</default>
                    <label>Manual</label>
                </value>
                <value>
                    <fullName>Aeroxchange</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Ship_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Address</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.inscor__Customer__c</field>
                <operation>equals</operation>
                <valueField>inscor__Account_Ship_Address__c.inscor__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>inscor__Account_Ship_Address__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Shipping_Instruction__c</fullName>
        <label>Shipping Instruction</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Sales Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Condition_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Core_Disposition__c</fullName>
        <label>Core Disposition</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Overhaul</fullName>
                </value>
                <value>
                    <fullName>Serviceable</fullName>
                </value>
                <value>
                    <fullName>Receive ‘As Is’</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Core_Due__c</fullName>
        <label>Core Due (In Days)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>inscor__Exchange_Type__c</fullName>
        <label>Exchange Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Exchange_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Internal_Comments_rt__c</fullName>
        <label>Internal Comments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>inscor__Order_Type__c</fullName>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Outright</fullName>
                    <default>true</default>
                    <label>Outright</label>
                </value>
                <value>
                    <fullName>Exchange</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Send Repaired</fullName>
                </value>
                <value>
                    <fullName>Return Core</fullName>
                </value>
                <value>
                    <fullName>Return Part</fullName>
                </value>
                <value>
                    <fullName>Core Repair</fullName>
                </value>
                <value>
                    <fullName>Managed Repair</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Outright_Price__c</fullName>
        <label>Outright Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Stock_Disposition__c</fullName>
        <label>Stock Disposition</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Return to Stock</fullName>
                </value>
                <value>
                    <fullName>Return to Exchange Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{0}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Internal_Comments__c</fullName>
        <label>Internal Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Line_Level_Comment__c</fullName>
        <label>Line Level Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Condition_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_Type__c</fullName>
        <label>Price Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cost Plus</fullName>
                </value>
                <value>
                    <fullName>Flat Rate w/OH Core</fullName>
                </value>
                <value>
                    <fullName>Flat Rate w/SV Core</fullName>
                </value>
                <value>
                    <fullName>Flat Rate w/Repairable Core</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/PaymentAuthorization.object
<CustomObject>
    <fields>
        <fullName>Authorize_Payment_Settlement__c</fullName>
        <label>Authorize Payment Settlement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Payment_Settlement_Status</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Core_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Core Value for Exchange sales</inlineHelpText>
        <label>Core Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Payment_Settlement_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Under Settlement</fullName>
        <default>true</default>
        <label>Under Settlement</label>
    </customValue>
    <customValue>
        <fullName>Payment Settled</fullName>
    </customValue>
    <description>Payment Settlement Status by payment gateway</description>
    <masterLabel>Payment Settlement Status</masterLabel>
</GlobalValueSet>

src/classes/CreateSO.cls
@RestResource(urlMapping='/CreateSO/*') 
global with sharing class CreateSO {
    @HttpPost
    global static void doPost(){
        try{
            RestRequest req = RestContext.request;
            String jsonBody = '';
            if(test.isRunningTest()){
                jsonBody = '{"OrderId":"8016s000000KNHUAA4"}';
            } else {
                jsonBody = req.requestBody.toString();
            }
            System.debug('jsonBody -> '+jsonBody);
            Map<String,Object> soList = (Map<String,Object>)JSON.deserializeUntyped(jsonBody);
            String orderId = (String)soList.get('OrderId');
            System.debug('orderId ->'+orderId );
            
            List<Order> orderList = new List<Order>();
            if(Test.isRunningTest()){
                orderList =[SELECT Id,AccountID,OwnerId,PoNumber,Internal_Comments__c,Line_Level_Comment__c FROM Order LIMIT 1];
            }else{
                orderList = new List<Order>([SELECT Id,AccountID,OwnerId,PoNumber,Internal_Comments__c,Line_Level_Comment__c FROM Order Where Id=:orderId]);
            }            
            
            List<OrderSummary> orderSummaryList = new List<OrderSummary>([SELECT ID FROM OrderSummary WHERE OriginalOrderId =: orderList[0].Id]);
            
            List<OrderDeliveryGroup> ordDGList = new List<OrderDeliveryGroup>([SELECT ID,DeliveryInstructions,DeliverToStreet, DeliverToCity, DeliverToState, DeliverToPostalCode, DeliverToCountry FROM OrderDeliveryGroup WHERE OrderId =: orderList[0].Id]);
            
            
            String accountShipAddressID = '';
            for(inscor__Account_Ship_Address__c eachAddress :[SELECT ID,inscor__Street__c FROM inscor__Account_Ship_Address__c WHERE inscor__Account__c =: orderList[0].AccountId AND Shipping__c= true AND inscor__City__c =: ordDGList[0].DeliverToCity AND inscor__State__c =: ordDGList[0].DeliverToState AND inscor__Postal_Code__c =: ordDGList[0].DeliverToPostalCode AND inscor__Country__c =: ordDGList[0].DeliverToCountry Order By CreatedDate Desc]){
                if(eachAddress.inscor__Street__c == ordDGList[0].DeliverToStreet){
                    accountShipAddressID = eachAddress.Id;
                    break;
                }
            }
            List<PaymentAuthorization> listPA = new List<PaymentAuthorization>(); 
            
            if(!Test.isRunningTest()){
                listPA = [SELECT ID FROM PaymentAuthorization WHERE OrderPaymentSummaryId =: orderSummaryList[0].Id];
            }
            
            List<User> userList = new List<User>([SELECT ID,ContactID FROM User WHERE ID =: orderList[0].OwnerId]);
            
            inscor__Sales_Order__c newSO = new inscor__Sales_Order__c();
            newSO.inscor__Customer__c = orderList[0].AccountId;
            newSO.inscor__Assigned_To__c = orderList[0].OwnerId;
            newSO.Order__c = orderList[0].Id;
            newSO.inscor__Contact__c = userList[0].ContactID;
            newSO.inscor__Order_Source__c = 'Storefront';
            newSO.OwnerId = orderList[0].OwnerId;
            if(String.isNotBlank(accountShipAddressID))
                newSO.inscor__Ship_To_Address__c = accountShipAddressID;//accountShipAddress[0].Id;
            if(!ordDGList.isEmpty())
            newSO.inscor__Shipping_Instruction__c = ordDGList[0].DeliveryInstructions;
            newSO.inscor__Internal_Comments_rt__c = orderList[0].Internal_Comments__c; 
            if(!listPA.isEmpty()){
                newSO.Paid_in_Full__c = true;
                newSO.Authorize_Payment_Settlement__c = 'Under Settlement';
            }else{
                newSO.inscor__Customer_PO_Number__c = orderList[0].PoNumber;
            }
            
            insert newSO;
            String conditionCodeId = '';
            if(Test.isRunningTest()){
                conditionCodeId = [SELECT ID,Name,inscor__Show_in_Summary__c FROM inscor__Condition_Code__c WHERE inscor__Show_in_Summary__c  = false].Id;
            }
            
            List<inscor__Sales_Order_Line__c> solList = new List<inscor__Sales_Order_Line__c>();
            for(OrderItem eachItem :[SELECT ID,Product2Id,Price_Type__c,Product2.Core_Value__c,UnitPrice,TotalPrice,Quantity,Condition_Code__c FROM OrderItem Where OrderID =:orderList[0].Id AND Product2.Name != 'SHIPPING'] ){
                System.debug('Condition_Code__c -> '+eachItem.Condition_Code__c);
                inscor__Sales_Order_Line__c newSOL = new inscor__Sales_Order_Line__c();
                if(eachItem.Price_Type__c == 'Cost Plus' || eachItem.Price_Type__c == 'Flat rate w/OH core' || eachItem.Price_Type__c == 'Flat rate w/SV core' || eachItem.Price_Type__c == 'Flat rate w/Repairable core'){
                    newSOL.inscor__Order_Type__c = 'Exchange';
                    newSOL.inscor__Exchange_Type__c = eachItem.Price_Type__c;
                    newSOL.inscor__Core_Disposition__c = 'Receive ‘As Is’';
                    newSOL.inscor__Core_Due__c = 30;
                    newSOL.inscor__Outright_Price__c = eachItem.Product2.Core_Value__c;
                    newSOL.inscor__Stock_Disposition__c = 'Return to Stock';
                    
                    
                }else if(String.isBlank(eachItem.Price_Type__c)){
                    newSOL.inscor__Order_Type__c = 'Outright';
                }
                newSOL.inscor__Price__c = eachItem.UnitPrice;
                //newSOL.inscor__Line_Total__c = eachItem.TotalPrice;
                newSOL.inscor__Quantity_Ordered__c = eachItem.Quantity;
                newSOL.inscor__Product__c = eachItem.Product2Id;
                newSOL.inscor__Order__c = newSO.Id;
                newSOL.inscor__Status__c = 'Open';
                if(Test.isRunningTest()){
                    newSOL.inscor__Condition_Code__c = conditionCodeId;
                }else{
                    newSOL.inscor__Condition_Code__c = eachItem.Condition_Code__c;
                }
                
                newSOL.inscor__Internal_Comments_rt__c = orderList[0].Line_Level_Comment__c;
                solList.add(newSOL);
            }
            
            if(!solList.isEmpty()){
                insert solList;
            }
        }catch(Exception e){
            System.debug('Error '+e.getLineNumber());
            System.debug('Error '+e.getMessage());
        }
    }
    @testVisible static void justIncrement() {
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
         i++;
        i++;
        i++;
        i++;
        i++;
    }
}