src/objects/inscor__Condition_Code__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Show_in_Summary__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show in Summary</label>
        <type>Checkbox</type>
    </fields>
    <label>Condition Code</label>
    <nameField>
        <label>Condition Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_CQ__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Quotes</relationshipLabel>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quote_Source__c</fullName>
        <label>Quote Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>inscor__Quote_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Temp_Quote__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Temp Quote?</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Quote</label>
    <nameField>
        <displayFormat>QU-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Customer_Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Condition_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Customer_Part_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Customer_Quote_Lines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Customer_Quote__c</fullName>
        <label>Customer Quote</label>
        <referenceTo>inscor__Customer_Quote__c</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <formula>inscor__Product__r.inscor__Keyword__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Keyword</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Customer_Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>inscor__Quote_Type__c</fullName>
        <label>Quote Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Outright</fullName>
                    <default>true</default>
                    <label>Outright</label>
                </value>
                <value>
                    <fullName>Exchange</fullName>
                </value>
                <value>
                    <fullName>No Quote</fullName>
                </value>
                <value>
                    <fullName>Managed Repair</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Quote Line</label>
    <nameField>
        <displayFormat>QUL-{0}</displayFormat>
        <label>Quote Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <label>Keyword</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__UOM__c</fullName>
        <label>UOM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EA</fullName>
                </value>
                <value>
                    <fullName>FT</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>YD</fullName>
                </value>
                <value>
                    <fullName>BG</fullName>
                </value>
                <value>
                    <fullName>BX</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>DR</fullName>
                </value>
                <value>
                    <fullName>FT2</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>GL</fullName>
                </value>
                <value>
                    <fullName>GLL</fullName>
                </value>
                <value>
                    <fullName>IN2</fullName>
                </value>
                <value>
                    <fullName>KT</fullName>
                </value>
                <value>
                    <fullName>LB</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>ML</fullName>
                </value>
                <value>
                    <fullName>MM</fullName>
                </value>
                <value>
                    <fullName>OZ</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>PT</fullName>
                </value>
                <value>
                    <fullName>QT</fullName>
                </value>
                <value>
                    <fullName>RL</fullName>
                </value>
                <value>
                    <fullName>SF</fullName>
                </value>
                <value>
                    <fullName>SH</fullName>
                </value>
                <value>
                    <fullName>SI</fullName>
                </value>
                <value>
                    <fullName>SP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomerQuoteControllerTest.cls
@isTest
public class CustomerQuoteControllerTest {
    
    @isTest
    public static void CustomerQuoteCheck(){
        list<Map<String, String>> QuoteLineItems = new list<Map<String, String>>();
        Map<String, String> LineItems = new Map<String, String>();

        
        Product2 pr = new Product2(Name ='#101',inscor__Keyword__c = 'SCREW',inscor__UOM__c='EA');
        insert pr;
        LineItems.put('value',pr.name);
        LineItems.put('key',pr.Id);
        LineItems.put('qty','5');
        LineItems.put('code','NE - Flat Rate w/OH Core');
        LineItems.put('code_id','NE - Flat Rate w/OH Core');
        QuoteLineItems.add(LineItems);
        
        //Salesforce_Auth__c objSalesforceAuth = [SELECT Id, Client_Id__c, Client_Secret__c, Login_Url__c, Password__c, Security_Token__c, UserName__c FROM Salesforce_Auth__c];
        Salesforce_Auth__c objSalesforceAuth = new Salesforce_Auth__c(
            Client_Id__c='test',
            Client_Secret__c='test',
            Login_Url__c='https://test.salesforce.com',
            Password__c='test',
            Security_Token__c='test',
            UserName__c='test');
        insert objSalesforceAuth;
        test.startTest();
        Test.setMock(HttpCalloutMock.class, new CustomerquoteTestcontroller());
            CustomerQuoteController.createQuoteAndLine(QuoteLineItems); 
            CustomerQuoteController.ProductName(pr.id);
        test.stopTest();
        //Salesforce_Auth__c objSalesforceAuth = [SELECT Id, Client_Id__c, Client_Secret__c, Login_Url__c, Password__c, Security_Token__c, UserName__c FROM Salesforce_Auth__c];
            
        //List<inscor__Customer_Quote_Line__c> createQuoteLineItems = CustomerQuoteController.createQuoteAndLine(QuoteLineItems);        
        
    }
    
    @isTest
    public static void CustomerQuoteandlinItemCheck(){
        list<Map<String, String>> QuoteLineItems = new list<Map<String, String>>();
        Map<String, String> LineItems = new Map<String, String>();

        //string communityId;// = '0DB6s000000Gmmy';
        //Id ac = [select accountId from User where Profile.name='Customer Community Plus Login User' limit 1].accountId;
        //Id ac = [select id from Account where name='Seattle Account'].id;
        Account ac = new Account(name ='Grazitti') ;
        insert ac; 
        
        Product2 pr = new Product2(Name ='#110',inscor__Keyword__c = 'SCREW',inscor__UOM__c='EA');
        //List<inscor__Condition_Code__c> CondCode =  [SELECT Id, Name FROM inscor__Condition_Code__c limit 1];
        insert pr;
        inscor__Condition_Code__c code = new inscor__Condition_Code__c();
        code.Name='NE';
        code.inscor__Show_in_Summary__c=false;
        insert code;
        system.debug('Condition code Details => '+code);
        
        //Product2 pr = new Product2(Name ='#10',inscor__Keyword__c = 'SCREW',inscor__UOM__c='EA');
        LineItems.put('value',pr.name);
        LineItems.put('key',pr.Id);
        LineItems.put('qty','5');
        LineItems.put('code','NE - Flat Rate w/OH Core');
        LineItems.put('code_id','NE - Flat Rate w/OH Core');
        QuoteLineItems.add(LineItems);
        
        inscor__Customer_Quote__c customerQuote = new inscor__Customer_Quote__c();
        customerQuote.inscor__Customer__c = ac.id;
        customerQuote.inscor__Temp_Quote__c = true;
        customerQuote.inscor__Quote_Source__c = 'Storefront';
        //insert customerQuote;
            
        List<inscor__Customer_Quote_Line__c> lineList = new List<inscor__Customer_Quote_Line__c>(); 
        inscor__Customer_Quote_Line__c eachLine = new inscor__Customer_Quote_Line__c();        
        //String cond_code = customerQuote.get(code_id[0]);
        eachLine.inscor__Customer_Quote__c = customerQuote.Id;
        eachLine.inscor__Customer_Part_Number__c = pr.Id;
        eachLine.inscor__Product__c = pr.Id;            
        eachLine.inscor__Condition_Code__c = code.Id;//row.get('code_id');
        eachLine.inscor__Quote_Type__c = 'Outright';            
        eachLine.inscor__Quantity__c = 2;
        lineList.add(eachLine);
        //insert eachLine;
        string JsonString = '{"Quote":'+JSON.serialize(customerQuote)+',';
        JsonString += '"QuoteLine":'+JSON.Serialize(lineList)+'}' ;
        
        /*RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CreateCQ'; //Request URL
        req.httpMethod = 'POST';
        //req.setBody(JsonString);
        
        RestContext.request = req;
        RestContext.response= res;*/
        system.debug('JsonString'+JsonString);
        List<User> uList = new List<User>([SELECT ID FROM User WHERE IsActive = true AND Profile.Name = 'System Admin Clone' Limit 1]);
        System.runAs(uList[0]){
            test.startTest();
            Test.setMock(HttpCalloutMock.class, new CustomerquoteTestcontroller());
            //CustomerQuoteController.createQuoteAndLine(QuoteLineItems);
            CreateCustomerQuoteAndItsLine.doPost(); 
            test.stopTest();
        }
        
        
    }
    
    /*@isTest
    public static void ProductNameCheck(){        
        
        Product2 prod = new Product2();
        prod.Name='#10';
        prod.StockKeepingUnit='10';
        prod.inscor__Keyword__c='10';
        insert prod;
        system.debug('product Details => '+prod);

        String productId = prod.Id;//'01t6s000000LVkKAAW';
        String Product_Name = CustomerQuoteController.ProductName(productId);
    }*/
}