src/objects/inscor__Condition_Code__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Description__c</fullName>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Condition Code</label>
    <nameField>
        <label>Condition Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Price__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Condition_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipLabel>Prices</relationshipLabel>
        <relationshipName>Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Price Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.inscor__Customer__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.inscor__Dropship_Site__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.inscor__Dropship_Site__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.inscor__Dropship_Site__c</field>
                <operation>equals</operation>
                <valueField>Contact.inscor__Account_Shipping_Address__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Create_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Create Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>inscor__Customer_PO_Number__c</fullName>
        <label>Customer PO Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_SO__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Expected_Ship_Date__c</fullName>
        <description>expected ship date</description>
        <inlineHelpText>expected ship date</inlineHelpText>
        <label>Expected Ship Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>inscor__Sales_Order_Total_Value__c</fullName>
        <label>Sales Order Total Value</label>
        <summarizedField>inscor__Sales_Order_Line__c.inscor__Line_Total__c</summarizedField>
        <summaryForeignKey>inscor__Sales_Order_Line__c.inscor__Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Sales Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Condition_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Condition Code</label>
        <referenceTo>inscor__Condition_Code__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Create_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Create Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>inscor__Expected_Ship_Date__c</fullName>
        <description>expected ship date</description>
        <inlineHelpText>Our best guess of the date we will ship.</inlineHelpText>
        <label>Expected Ship Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>inscor__Line_Total__c</fullName>
        <formula>inscor__Quantity_Ordered__c *  inscor__Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Order__c</fullName>
        <label>Order</label>
        <referenceTo>inscor__Sales_Order__c</referenceTo>
        <relationshipName>Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>inscor__Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>inscor__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Number</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Promised_Date__c</fullName>
        <inlineHelpText>Date calculated from quoted delivery</inlineHelpText>
        <label>Promised Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity_Ordered__c</fullName>
        <label>Quantity Ordered</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>inscor__Quantity_Shipped__c</fullName>
        <label>Quantity Shipped</label>
        <summarizedField>inscor__Allocation__c.inscor__Quantity_Shipped__c</summarizedField>
        <summaryForeignKey>inscor__Allocation__c.inscor__Sales_Order_Line__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{0}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>inscor__Avg_Lead_Time__c</fullName>
        <label>Avg Lead Time</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>inscor__Create_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Create Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>inscor__Description__c</fullName>
        <label>Description</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__UOM__c</fullName>
        <label>UOM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EA</fullName>
                </value>
                <value>
                    <fullName>FT</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>YD</fullName>
                </value>
                <value>
                    <fullName>BG</fullName>
                </value>
                <value>
                    <fullName>BX</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CS</fullName>
                </value>
                <value>
                    <fullName>DR</fullName>
                </value>
                <value>
                    <fullName>FT2</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>GL</fullName>
                </value>
                <value>
                    <fullName>GLL</fullName>
                </value>
                <value>
                    <fullName>IN2</fullName>
                </value>
                <value>
                    <fullName>KT</fullName>
                </value>
                <value>
                    <fullName>LB</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>ML</fullName>
                </value>
                <value>
                    <fullName>MM</fullName>
                </value>
                <value>
                    <fullName>OZ</fullName>
                </value>
                <value>
                    <fullName>PK</fullName>
                </value>
                <value>
                    <fullName>PT</fullName>
                </value>
                <value>
                    <fullName>QT</fullName>
                </value>
                <value>
                    <fullName>RL</fullName>
                </value>
                <value>
                    <fullName>SF</fullName>
                </value>
                <value>
                    <fullName>SH</fullName>
                </value>
                <value>
                    <fullName>SI</fullName>
                </value>
                <value>
                    <fullName>SP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BackOrdersController.cls
/**
 * @author - Keykloud
 * @description - Class created for the lwc component name as quoteHistory
 * @TestClass - pending
 * @createdDate - 12/18/2021
 * @lastModifiedDate - 12/23/2021
 * @lastModifiedBy - KeyKloud
 */
public without sharing class BackOrdersController {

    @AuraEnabled(cacheable = true)
    public static List<BackOrderWrapper> getOrders(){
        List<BackOrderWrapper> BackOrderWrapperList = new List<BackOrderWrapper>();
        //User usr = getLoggedInUser();
        // if (usr.Contact.Is_Super_User__c && usr.Contact.AccountId != null) {
        //     List<inscor__Sales_Order__c> orders = [SELECT Id, Name, inscor__Sales_Order_Total_Value__c,
        //                                             inscor__Create_Date__c, inscor__Customer_PO_Number__c,
        //                                             inscor__Contact__c, inscor__Contact__r.Name
        //                                             FROM inscor__Sales_Order__c 
        //                                             WHERE Id IN (SELECT inscor__Order__c 
        //                                                         FROM inscor__Sales_Order_Line__c 
        //                                                         // WHERE inscor__Product__r.inscor__Avg_Lead_Time__c > 30 
        //                                                         WHERE inscor__Order__r.inscor__Customer__c = :usr.Contact.AccountId 
        //                                                         AND ((inscor__Expected_Ship_Date__c != NULL AND inscor__Expected_Ship_Date__c > DAY_ONLY(inscor__Create_Date__c))
        //                                                                 OR (inscor__Expected_Ship_Date__c = NULL AND inscor__Promised_Date__c > inscor__Create_Date__c))
        //                                                         )
        //                                             ORDER BY inscor__Create_Date__c DESC
        //                                             LIMIT 10000];
    
        //     for(inscor__Sales_Order__c order : orders){
        //         BackOrderWrapperList.add(createBackOrderWrapper(order));
        //     }
        // }else if (!usr.Contact.Is_Super_User__c && usr.ContactId != null) {
            System.debug('getBackOrderIds >> '+getBackOrderIds());
        List<inscor__Sales_Order__c> orders = [SELECT Id, Name, inscor__Sales_Order_Total_Value__c,
                                                inscor__Create_Date__c, inscor__Customer_PO_Number__c,
                                                inscor__Contact__c, inscor__Contact__r.Name
                                                FROM inscor__Sales_Order__c 
                                                WHERE Id IN :getBackOrderIds()
                                                ORDER BY inscor__Create_Date__c DESC
                                                LIMIT 10000];

        System.debug('orders >> '+ orders);
        for(inscor__Sales_Order__c order : orders){
            System.debug('inside for loop >>>');
            BackOrderWrapperList.add(createBackOrderWrapper(order));
        }
        //}
        System.debug('BackOrderWrapperList >> '+ BackOrderWrapperList);                                               
        return BackOrderWrapperList;
    }

    @AuraEnabled
    public static List<BackOrderLineWrapper> getOrderLinesById(String orderId){

        try {
            List<BackOrderLineWrapper> BackOrderLineWrappers = new List<BackOrderLineWrapper>();
            Integer count = 1;
            for(inscor__Sales_Order_Line__c lineItem : [SELECT id, inscor__Product__r.Name, inscor__Product__r.inscor__Description__c, inscor__Condition_Code__r.Name, 
                            inscor__Quantity_Ordered__c,inscor__Quantity_Shipped__c, inscor__Product__r.inscor__UOM__c, inscor__Price__c, inscor__Line_Total__c 
                            FROM inscor__Sales_Order_Line__c 
                            WHERE inscor__Order__c =:orderId]){
                BackOrderLineWrappers.add(createBackOrderLineWrapper(lineItem, count));
                count++;
            }
            return BackOrderLineWrappers;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public static Set<Id> getBackOrderIds() {
        Set<Id> backOrderIds = new Set<Id>();
        List<inscor__Sales_Order_Line__c> orderLines = new List<inscor__Sales_Order_Line__c>();
        User usr = getLoggedInUser();
        if (usr.Contact.Is_Super_User__c && usr.Contact.AccountId != null){
            orderLines = [SELECT inscor__Order__c, inscor__Expected_Ship_Date__c, inscor__Promised_Date__c, inscor__Create_Date__c FROM inscor__Sales_Order_Line__c
                            WHERE inscor__Order__r.inscor__Customer__c = :usr.Contact.AccountId AND (inscor__Expected_Ship_Date__c != NULL OR inscor__Promised_Date__c != NULL)
                            LIMIT 10000];
        }else if (!usr.Contact.Is_Super_User__c && usr.ContactId != null) {
            orderLines = [SELECT inscor__Order__c, inscor__Expected_Ship_Date__c, inscor__Promised_Date__c, inscor__Create_Date__c FROM inscor__Sales_Order_Line__c 
                            WHERE inscor__Order__r.inscor__Contact__c = :usr.ContactId AND (inscor__Expected_Ship_Date__c != NULL OR inscor__Promised_Date__c != NULL)
                            LIMIT 10000];
        }

        System.debug('orderLines >> '+ orderLines);
        for (inscor__Sales_Order_Line__c orderLine : orderLines) {
            System.debug('inside for loop >>');
            if (orderLine.inscor__Expected_Ship_Date__c != null && orderLine.inscor__Expected_Ship_Date__c > orderLine.inscor__Create_Date__c) {
                backOrderIds.add(orderLine.inscor__Order__c);
            }else if (orderLine.inscor__Expected_Ship_Date__c == null && orderLine.inscor__Promised_Date__c > orderLine.inscor__Create_Date__c) {
                backOrderIds.add(orderLine.inscor__Order__c);
            }
        }
        System.debug('backOrderIds >>' +backOrderIds);
        return backOrderIds;
    }

    /**
     * @description : method used to create instance of Order History wrapper as per Sales order
     * @createdDate : 12.23.2021
     */
    public static BackOrderWrapper createBackOrderWrapper(inscor__Sales_Order__c order) {

        BackOrderWrapper BackOrderWrapperInstance = new BackOrderWrapper();
        BackOrderWrapperInstance.id = order.Id;
        BackOrderWrapperInstance.orderType = ''; 
        BackOrderWrapperInstance.orderNumber = order.Name;
        BackOrderWrapperInstance.orderAmount = order.inscor__Sales_Order_Total_Value__c == null ? 0 : order.inscor__Sales_Order_Total_Value__c;
        BackOrderWrapperInstance.orderDate = order.inscor__Create_Date__c;
        BackOrderWrapperInstance.customerPO = order.inscor__Customer_PO_Number__c == null ? '-' : order.inscor__Customer_PO_Number__c;
        BackOrderWrapperInstance.contactName = order.inscor__Contact__r.Name == null ? '-' : order.inscor__Contact__r.Name;
        BackOrderWrapperInstance.isShowLines = false;

        return BackOrderWrapperInstance;
    }

    /**
     * @description : method used to create instance of order line wrapper as per sales order line
     * @createdDate : 12.23.2021
     */
    public static BackOrderLineWrapper createBackOrderLineWrapper(inscor__Sales_Order_Line__c lineItem, Integer count) {

        BackOrderLineWrapper lineWrapper = new BackOrderLineWrapper();
        lineWrapper.rowNumber = count;
        lineWrapper.partNumber = lineItem.inscor__Product__r.Name == null ? '-' : lineItem.inscor__Product__r.Name;
        lineWrapper.description = lineItem.inscor__Product__r.inscor__Description__c == null ? '-' : lineItem.inscor__Product__r.inscor__Description__c;
        lineWrapper.conditionCode = lineItem.inscor__Condition_Code__r.Name == null ? '-' : lineItem.inscor__Condition_Code__r.Name;
        lineWrapper.orderQty = lineItem.inscor__Quantity_Ordered__c == null ? 0 : lineItem.inscor__Quantity_Ordered__c;
        lineWrapper.shipQty = lineItem.inscor__Quantity_Shipped__c == null ? 0 : lineItem.inscor__Quantity_Shipped__c;  
        lineWrapper.um = lineItem.inscor__Product__r.inscor__UOM__c == null ?  '-' : lineItem.inscor__Product__r.inscor__UOM__c;
        lineWrapper.price = lineItem.inscor__Price__c == null ? 0 : lineItem.inscor__Price__c;
        lineWrapper.total = lineItem.inscor__Line_Total__c;
        return lineWrapper;
    }

    @AuraEnabled 
    public static List<BackOrderWrapper> getOrdersBySearch(String custPO, String orderDate){
        try {
            String businessCategory_Surpuls = 'Surplus';
            Date cOrderDate = (orderDate != null && orderDate != '') ? Date.valueOf(orderDate) : null;
            custPo = String.isNotBlank(custPo) ? custPo + '%' : null;
            List<BackOrderWrapper> BackOrderWrapperList = new List<BackOrderWrapper>();
            // User usr = getLoggedInUser();
            // String customerId = usr.Contact.AccountId;
            // String contactId = usr.ContactId;
            Set<Id> backOrderIds = getBackOrderIds();
            String query = 'SELECT id, Name, inscor__Sales_Order_Total_Value__c, inscor__Create_Date__c,inscor__Customer_PO_Number__c, inscor__Contact__c, inscor__Contact__r.Name ';
            query += 'FROM inscor__Sales_Order__c ';
            query += 'WHERE Id IN :backOrderIds AND'; 
            if(cOrderDate != null){
                query = query + ' DAY_ONLY(inscor__Create_Date__c) = :cOrderDate AND';
            }
            if(custPo != null && custPo !=''){
                query = query + ' inscor__Customer_PO_Number__c LIKE :custPo AND';
            }
            query = query.removeEnd('AND');
            query = query + ' ORDER BY inscor__Create_Date__c DESC LIMIT 10000';
            //System.debug(query);
            List<inscor__Sales_Order__c> orders = Database.Query(query);
            for(inscor__Sales_Order__c order : orders){
                BackOrderWrapperList.add(createBackOrderWrapper(order));
            }
                                                                
            return BackOrderWrapperList;
        } catch (Exception e) {

            System.debug(e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }

    }

    private static User getLoggedInUser() {
        Id userId = UserInfo.getUserId();
        User usr = [SELECT Id, ContactId, Contact.AccountId, Contact.Is_Super_User__c FROM User WHERE Id = :userId];
        return usr;
    }

    public class BackOrderWrapper{
        @AuraEnabled public String id {get; set;}
        @AuraEnabled public String orderNumber {get; set;}
        @AuraEnabled public Decimal orderAmount {get; set;}
        @AuraEnabled public DateTime orderDate {get; set;}
        @AuraEnabled public String orderType {get; set;}
        @AuraEnabled public String customerPO {get; set;}
        @AuraEnabled public String contactName {get; set;}
        @AuraEnabled public Boolean isShowLines {get; set;}
    }

    public class BackOrderLineWrapper{
        @AuraEnabled public Integer rowNumber{get;set;}
        @AuraEnabled public string partNumber{get;set;}
        @AuraEnabled public string description{get;set;}
        @AuraEnabled public string conditionCode{get;set;}
        @AuraEnabled public Decimal orderQty{get;set;}
        @AuraEnabled public Decimal shipQty{get;set;}
        @AuraEnabled public string um{get;set;}
        @AuraEnabled public Decimal price{get;set;}
        @AuraEnabled public Decimal total{get;set;}
    }
}