src/objects/inscor__Release__c.object
<CustomObject>
    <fields>
        <fullName>Compliance_Request__c</fullName>
        <label>Compliance Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Compliance_Response__c</fullName>
        <label>Compliance Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Compliance_Status__c</fullName>
        <label>Compliance Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment_Response__c</fullName>
        <label>Shipment Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>inscor__Dropship_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dropship Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.inscor__Dropship_to_Account__c</field>
                <operation>equals</operation>
                <valueField>inscor__Account_Ship_Address__c.inscor__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>inscor__Account_Ship_Address__c</referenceTo>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Dropship_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dropship to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Export_Status__c</fullName>
        <label>Export Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Hold</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>inscor__Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>inscor__Sales_Order__c</referenceTo>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Ship_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Address</label>
        <referenceTo>inscor__Account_Ship_Address__c</referenceTo>
        <relationshipName>Releases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Release</label>
    <nameField>
        <displayFormat>RLS-{0}</displayFormat>
        <label>Release Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_SO__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Dropship_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If a Dropship to Account has been selected, use this to override the default address with any of the optional shipping addresses.</inlineHelpText>
        <label>Dropship Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.inscor__Dropship_to_Account__c</field>
                <operation>equals</operation>
                <valueField>inscor__Account_Ship_Address__c.inscor__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>inscor__Account_Ship_Address__c</referenceTo>
        <relationshipLabel>Sales Orders (Dropship Site)</relationshipLabel>
        <relationshipName>Sales_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Dropship_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Use this to dropship to another Account.</inlineHelpText>
        <label>Dropship to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders (Dropship to Account)</relationshipLabel>
        <relationshipName>Sales_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Ship_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Address</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.inscor__Customer__c</field>
                <operation>equals</operation>
                <valueField>inscor__Account_Ship_Address__c.inscor__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>inscor__Account_Ship_Address__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Sales Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ReleaseToShipmentAPIService.cls
public class ReleaseToShipmentAPIService {

    public static void sendShipmentToCompliance(List<inscor__Release__c> releases){
        Set<Id> salesOrderIds = new Set<Id>();
        Set<Id> customerIds = new Set<Id>();
        for(inscor__Release__c release : releases){
            salesOrderIds.add(release.inscor__Sales_Order__c);
            if(release.inscor__Ship_To_Address__c != null){
                customerIds.add(release.inscor__Sales_Order__r.inscor__Customer__c);
            }else if(release.inscor__Dropship_Site__c != null){
                customerIds.add(release.inscor__Dropship_to_Account__c);
            }
        }
        
        Map<Id, inscor__Sales_Order__c> salesOrderMap = ComplianceUtility.getSalesOrderWithLineItems(salesOrderIds);
        Map<Id, Account> accountMap = ComplianceUtility.getAccountWithContacts(customerIds);
        //System.assert( false, releaseLineIds );
        inscor__Sales_Order__c salesOrder;
        Account customer;
        for(inscor__Release__c release : releases){
            try{
                salesOrder = salesOrderMap.get(release.inscor__Sales_Order__c);
                //releaseLine = salesOrderMap.get(release.inscor__Sales_Order__c);
                
                if(release.inscor__Ship_To_Address__c != null){
                customer = accountMap.get(release.inscor__Sales_Order__r.inscor__Customer__c);
                }else if(release.inscor__Dropship_Site__c != null){
                    customer = accountMap.get(release.inscor__Dropship_to_Account__c);
                }
                
                String errorString = ComplianceValidation.validateUploadFileRequest(release, salesOrder, customer);
                //System.assert(false, errorString);
                if(String.isBlank(errorString)){
                    String requestXMLWIthSpecialChar = ComplianceRequestHelper.createRequestXMLToSendShipment(release, salesOrder, customer);
                    String requestXML = ComplianceUtility.formatSpecialCharXML( requestXMLWIthSpecialChar );
                    //System.assert(false, requestXML);
                    release.Compliance_Request__c = requestXML;
                    HttpResponse res = ComplianceAPIHelper.sendShipmentDetails(requestXML, release.Name);
                    if(res.getStatusCode() == 200){
                        String responseBody = res.getBody();
                        release.Compliance_Response__c = responseBody;
                        //System.assert(false, responseBody);
                        ComplianceResponseHelper.parseUploadFileResponse(responseBody, release);    
                    }else{
                        release.Compliance_Response__c = 'Response :'+res.getStatus()+ '\n Response Code : '+res.getStatusCode()+' \n Response Body: '+res.getBody();
                    }    
                }else{
                    release.Compliance_Response__c = errorString;
                    release.Compliance_Status__c = 'Uploaded Failed';
                    release.inscor__Export_Status__c = 'On Hold';
                }
            }catch(Exception e){
                release.Compliance_Response__c = e.getMessage() + '\n\n\n '+e.getStackTraceString();
                release.Compliance_Status__c = 'Uploaded Failed';
                release.inscor__Export_Status__c = 'On Hold';
            }
        }
        Database.DMLOptions opt = new Database.DMLOptions();
        opt.allowFieldTruncation = true;
        Database.update(releases, opt);
    }
    
    
    
    public static void checkShipmentStatus(List<inscor__Release__c> releases){
        for(inscor__Release__c release : releases){
            try{                
                HttpResponse res = ComplianceAPIHelper.checkShipmentStatus(release.Name);
                if(res.getStatusCode() == 200){
                    String responseBody = res.getBody();
                    release.Shipment_Response__c = responseBody;
                    //System.assert(false, responseBody);
                    ComplianceResponseHelper.parseShipmentResponse(responseBody, release);    
                }else{
                    release.Shipment_Response__c = 'Response :'+res.getStatus()+ '\n Response Code : '+res.getStatusCode()+' \n Response Body: '+res.getBody();
                }    
                
            }catch(Exception e){
                release.Shipment_Response__c = e.getMessage() + '\n\n\n '+e.getStackTraceString();
            }
        }
        Database.DMLOptions opt = new Database.DMLOptions();
        opt.allowFieldTruncation = true;
        Database.update(releases, opt);
    }
}