src/objects/inscor__Customer_Quote__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_CQ__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Quotes</relationshipLabel>
        <relationshipName>Customer_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Quote</label>
    <nameField>
        <displayFormat>QU-{0}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/inscor__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>inscor__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.inscor__Hide_from_SO__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>inscor__Quote_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Number</label>
        <referenceTo>inscor__Customer_Quote__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0}</displayFormat>
        <label>Sales Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Lead_Managment__mdt.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Lead Managment</label>
    <pluralLabel>Lead Managment</pluralLabel>
</CustomObject>

src/classes/ProcessObsoleteLeadBatch.cls
global class ProcessObsoleteLeadBatch implements Database.Batchable<sObject>, Schedulable {
    global static Map<String,Lead_Managment__mdt> leadManagmentSettings = new Map<String,Lead_Managment__mdt>();
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        String query = 'Select id,Name,OwnerId,(Select Name,Id from inscor__Customer_Quotes__r),(Select Id from inscor__Sales_Orders__r),(Select Id from Leads__r) from Account';
        return Database.getQueryLocator(query);
    }
     
    global void execute(Database.BatchableContext BC, List<Account> scope) {
        if(leadManagmentSettings.size()  == 0){
             leadManagmentSettings = Lead_Managment__mdt.getall();
        }
        List<Lead> leadRecToInsert = new List<Lead>();
        for(Account accRec : scope){
            if(accRec.Leads__r.size() == 0 && accRec.inscor__Sales_Orders__r.size() == 0
               && accRec.inscor__Customer_Quotes__r.size() > 50 ){
                   leadRecToInsert.add(createLeadRecord(accRec));
               }
        }
        
        if(leadRecToInsert.size() > 0){
            insert leadRecToInsert;
        }
         
    }   
     
    global void finish(Database.BatchableContext BC) {
        
    }
    
    global void execute(SchedulableContext sc) {
       
      Database.executeBatch(new ProcessObsoleteLeadBatch());
   }
    
    private static Lead createLeadRecord(Account acc){
        Lead leadRec = new Lead();
        leadRec.LastName = acc.Name;
        leadRec.Company = acc.Name;
        leadRec.Customer__c = acc.id;
        leadRec.Status =  leadManagmentSettings.containsKey('Lead_Status') ? 
                    leadManagmentSettings.get('Lead_Status').Value__C : 'New';
        leadRec.ownerId = leadManagmentSettings.containsKey('Lead_OwnerId') ? 
                   ( leadManagmentSettings.get('Lead_OwnerId').Value__c != null ? 
                    leadManagmentSettings.get('Lead_OwnerId').Value__c : acc.ownerId) : acc.ownerId;
        return leadRec;        
    } 
}