src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>inscor__Country_of_Origin__c</fullName>
        <inlineHelpText>If left blank, Country of Origin will automatically fill in after the MFR Code is selected. If you do not want the Country of Origin to be filled in from the MFR Code selected, fill in with &quot;Unknown&quot; or the appropriate Country.</inlineHelpText>
        <label>Country of Origin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__Description__c</fullName>
        <label>Description</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__HazMat_Id__c</fullName>
        <inlineHelpText>UN Number</inlineHelpText>
        <label>HazMat Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>inscor__HazMat__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HazMat?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>inscor__Keyword__c</fullName>
        <label>Keyword</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchProcessProductToItems.cls
global class BatchProcessProductToItems implements Database.Batchable<sObject>,Database.AllowsCallouts,Database.Stateful {

    Public Set<Id> productIds;
    global BatchProcessProductToItems(){
        productIds = new Set<Id>();
    }
    global BatchProcessProductToItems(Set<Id> Ids){
        productIds = Ids;
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'SELECT Id, Name, inscor__Keyword__c, '+
            			'inscor__Description__c, inscor__Country_of_Origin__c, '+
            			'inscor__HazMat__c, inscor__HazMat_Id__c, IsActive '+
            			'FROM  Product2 ';
        
        if(productIds.size() > 0){
            query += ' WHERE Id IN: productIds';
        }
        //system.assert(false,query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Product2> productList){
        ProductToItemAPIService.sendProductsToCompliance(productList);
    }
    
    global void finish(Database.BatchableContext bc){
    }

}