src/objects/Trigger_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Trigger Configuration will be used for maintaining trigger toggle for its execution.</description>
    <fields>
        <fullName>Contact_Trigger_Disable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contact Trigger Disable</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Configuration</label>
</CustomObject>

src/classes/UpdateContactEmailsToInvalidBatch.cls
global without sharing class UpdateContactEmailsToInvalidBatch implements Database.Batchable<SObject> {
    global String query = 'SELECT Id, Email FROM Contact WHERE NOT(Email LIKE \'%invalid\')';

    global UpdateContactEmailsToInvalidBatch(String query) {
        if(query == null || String.isBlank(query)) {
            this.query = query;
        }
    }

    global Database.QueryLocator start(Database.BatchableContext bc){
        Trigger_Configuration__c configSetting = Trigger_Configuration__c.getInstance();
        configSetting.Contact_Trigger_Disable__c = true;
        upsert configSetting;

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Contact> scope){
        for(Contact contact : scope) {
            contact.Email = contact.Email + '.invalid';
        }
        update scope;
    }

    global void finish(Database.BatchableContext BC){
        Trigger_Configuration__c configSetting = Trigger_Configuration__c.getInstance();
        configSetting.Contact_Trigger_Disable__c = false;
        upsert configSetting;
    }
}